### ISSUE TITLE
FlatList and SectionList aren't mentioned in Animated API

### ISSUE THREAD

**Issue by shau-kote** [facebook/react-native-website#1048]
The Animated Library [provides](https://github.com/facebook/react-native/blob/master/Libraries/Animated/src/Animated.js) the FlatList and SectionList components, but they aren't mentioned in [the Animations Guide](https://facebook.github.io/react-native/docs/animations) neither in [the Animated Reference](https://facebook.github.io/react-native/docs/animated).

I've made a PR for this: https://github.com/facebook/react-native-website/pull/1049

**Comment by ecreeth** [comment]
@shau-kote you can close this now! Thanks! :100:
