### ISSUE TITLE
Double Display of hide show password field

### ISSUE THREAD

**Issue by divs246** [facebook/react-native-website#1061]
![Simulator Screen Shot - iPhone X - 2019-06-26 at 19 17 52](https://user-images.githubusercontent.com/46372904/60185274-38874580-9847-11e9-8e30-282ff5757d7c.png)
Whenever we are including hide show password input package it is taking icon also as a one field it is appearing two input boxes as output.

**Comment by Simek** [comment]
Hi @divs246, I'm sorry but this is the React Native __Website__ repository. The bugs or issues in the React Native framework should be reported in the [`facebook/react-native`](https://github.com/facebook/react-native/issues) repository.
