### ISSUE TITLE
get latest captured image from gallery in react-native (IOS)?

### ISSUE THREAD

**Issue by ppv94** [facebook/react-native-website#1078]
After capturing the image, I am triggering the CameraRoll.getPhotos method. In android, I am able to get the latest captured image in android, but in IOS I am getting the last image in the gallery but not the latest captured image.
### This is my camera roll method.

Get_PhotosIos() {
     CameraRoll.getPhotos({
         first: 1,
         groupTypes: 'All',
         assetType: 'All'
     })
     .then((r) => {
          this.setState({ photos: r.edges, summary: `Number of photos found ${r.edges.length}` })
     .catch((error) => {
       alert('error')
     })
   };

How can I get the latest captured image after capturing the image in react-native(IOS)?

**Comment by kiranjd** [comment]
Please post issues related to react-native on [react-native](https://github.com/facebook/react-native) repository. Before you post an issue, consider posting it on StackOverflow.
