### ISSUE TITLE
Update PushNotificationIOS documentation to use Podfile (RN v60+)

### ISSUE THREAD

**Issue by moritzmhmk** [facebook/react-native-website#1089]
Manually linking the PushNotificationIOS library is no longer required!

Simply add

``pod 'React-RCTPushNotification', :path => '../node_modules/react-native/Libraries/PushNotificationIOS'``

to ``./ios/Podfile``

Then run ``cd ios && pod install && cd ..`` to update the Pods.

Then the usual ``react-native run-ios`` :)

**Comment by sgup** [comment]
This page should be updated: https://facebook.github.io/react-native/docs/pushnotificationios

**Comment by jkeam** [comment]
Agreed, and I don't even know what I'm looking at here with this code snippet:

<img width="860" alt="wat" src="https://user-images.githubusercontent.com/48856/69171502-162de700-0aca-11ea-9ff1-af4f3ee05128.png">

**Comment by jkeam** [comment]
Ya, this is safe to close.  The docs have been updated.
