### ISSUE TITLE
documentation inconsistency stylesheet absoluteFill

### ISSUE THREAD

**Issue by chakrihacker** [facebook/react-native-website#1093]
What's the difference between absoluteFill
https://github.com/facebook/react-native-website/blob/master/docs/stylesheet.md#L161 and absoluteFillObject https://github.com/facebook/react-native-website/blob/master/docs/stylesheet.md#L177

Can we remove absoluteFillObject from stylesheet??

**Comment by charpeni** [comment]
Description of both has been improved.
