### ISSUE TITLE
sectionlist doesn't display properly

### ISSUE THREAD

**Issue by getaaron** [facebook/react-native-website#110]
https://github.com/facebook/react-native-website/blob/master/docs/sectionlist.md shows several props like `initialNumToRender`, `keyExtractor`, etc

https://facebook.github.io/react-native/docs/sectionlist.html shows only `stickySectionHeadersEnabled` with a blank type and no description:

![image](https://user-images.githubusercontent.com/789577/34470069-82ca534c-eeef-11e7-899c-f3c70d29508a.png)

**Comment by getaaron** [comment]
CC @hramos

**Comment by lwinkyawmyat** [comment]
Now, I can see it. 

![sectionlist](https://user-images.githubusercontent.com/13135332/35105304-b3c1169a-fc99-11e7-9e6a-3107c0de137b.png)

**Comment by tapanprakasht** [comment]
@hramos I think this issue has resolved. Need to close this issue.
