### ISSUE TITLE
Update README for npm and pod install instruction

### ISSUE THREAD

**Issue by akshaygore06** [facebook/react-native-website#1112]
Need to add the instruction to install the node modules and pods in the readme file.
[Old issue](https://github.com/facebook/react-native-website/issues/676)

**Comment by Simek** [comment]
As stated in mentioned PR, you shouldn't have to install dependencies by yourself. There were also a PR #1444 which improved Getting Started guide and includes tweaks related to the issue reported here.

If you still having any issues with latest version of React Native and Pods please create the new issue.
