### ISSUE TITLE
Link needed in blurb about App Transport Security exception

### ISSUE THREAD

**Issue by carlbennettnz** [facebook/react-native-website#112]
From the [Networking page](https://facebook.github.io/react-native/docs/network.html):

> By default, iOS will block any request that's not encrypted using SSL. If you need to fetch from a cleartext URL (one that begins with http) you will first need to add an App Transport Security exception. If you know ahead of time what domains you will need access to, it is more secure to add exceptions just for those domains; if the domains are not known until runtime you can disable ATS completely. Note however that from January 2017, Apple's App Store review will require reasonable justification for disabling ATS. See Apple's documentation for more information.

The part about disabling it completely has a link, but how to add an exception for specific domains is not. Linking to a resource that explains how to do this would be useful, particularly for users of create-react-native-app, which seems to hide things like the info.plist file mentioned in [this article that appears if you google it](https://medium.com/react-native-institute/a-gotcha-with-fetch-3702e82a09db).

**Comment by isaacchien** [comment]
I'll work on this.

**Comment by charpeni** [comment]
@carlbennettnz does the PR #177 is enough?

**Comment by carlbennettnz** [comment]
Hey, sorry, just saw this. Good improvement, thanks 👍 

Only concern is that the `Info.plist` referred to in the linked resource is hidden by create-react-native-app. When I tried to create my first app, I found similar instructions, but never found this file.

**Comment by isaacchien** [comment]
Oh, I see what you mean. In that case, would the developer have to add React Native to a native iOS app then?

**Comment by carlbennettnz** [comment]
Not sure. I gave up after getting stuck on this and went back to PWAs instead.

**Comment by divyanshu-rawat** [comment]
@charpeni it would be great if you can close this issue as PR for the same has already been merged.
