### ISSUE TITLE
use [snack.io][WEB SUPPORT] instead of react-native-web-player

### ISSUE THREAD

**Issue by ecreeth** [facebook/react-native-website#1131]
As shown in the following image, snack.io now has web support.

The reason for this change is that the examples in the `snack` player are more similar to what they would look like on a real device.

![image](https://user-images.githubusercontent.com/20761166/61547097-b1c62280-aa18-11e9-89f0-7e901eb05297.png)

cc @hramos

**Comment by hramos** [comment]
This seems fine to me. Are all existing uses of the react-native-web-player well supported when switched to use the Snack Web player?

**Comment by ecreeth** [comment]
I'm not 100% sure, I've tried all the examples in the "The Basics" section and they all work. Maybe @brentvatne can clarify this for us.

**Comment by brentvatne** [comment]
yeah they should work fine! 

@ecreeth - can you open a PR for this so we can test it out with the automatically deployed netlify preview? (eg: https://github.com/facebook/react-native-website/pull/1142#issuecomment-514781241)

**Comment by ecreeth** [comment]
Of course!! :100: thanks for the clarification

**Comment by ecreeth** [comment]
the PR was created. I have noticed that the web player option does not appear. Any ideas
![imagen](https://user-images.githubusercontent.com/20761166/61841721-a84b1900-ae63-11e9-9db5-c465ad79cc13.png)

**Comment by tcdavis** [comment]
@ecreeth I believe this needs to be bumped to 33.0.0

**Comment by ecreeth** [comment]
@brentvatne it seems that the snack Embed Preview does not have the option of the web player
Thank you @tcdavis, once you sent the message I thought that could be the problem
![image](https://user-images.githubusercontent.com/20761166/61907761-20fdb400-aefc-11e9-9e58-e5af8d956daf.png)

**Comment by tcdavis** [comment]
@ecreeth Sorry about that.  Embeds should have the web preview now
