### ISSUE TITLE
Document which CSS features are not supported

### ISSUE THREAD

**Issue by o-t-w** [facebook/react-native-website#1149]
It would be incredibly helpful to have a list of the CSS properties that are not supported for native. I have read that you don't support CSS grid but have been unable to find out what else is missing.

**Comment by sunnylqm** [comment]
Are these docs what you are asking? 

https://facebook.github.io/react-native/docs/layout-props  
https://facebook.github.io/react-native/docs/view-style-props
https://facebook.github.io/react-native/docs/image-style-props
https://facebook.github.io/react-native/docs/text-style-props
https://facebook.github.io/react-native/docs/transforms
https://facebook.github.io/react-native/docs/shadow-props

Apparently properties not listed are not supported

**Comment by rachelnabors** [comment]
The CSS standard is already evolving and adding new properties. Maintaining a list of what we _don't_ support would easily fall out of date! Are there particular things that have cause you to stumble in development? Perhaps we could add a gotcha or warning for common use case :)

**Comment by o-t-w** [comment]
I had been thinking of writing a blog post about it - I'd be happy to add something to the docs instead. I honestly think a partial and incomplete list of properties RN doesn't support would be more useful than nothing - just to make clear to people that there is a bunch of properties that won't be available to them in RN. As somebody coming from the web it's been bewildering to grapple with something that kinda pretends to be CSS while also being very different in loads of ways.
