### ISSUE TITLE
Add in docs that "location" is now an extracted module

### ISSUE THREAD

**Issue by giacomocerquone** [facebook/react-native-website#1151]
We should add in this page: https://facebook.github.io/react-native/docs/geolocation
that the module is extracted here (and so it's not global anymore): https://github.com/react-native-community/react-native-geolocation

If someone gives me the ok, I'll prepare the PR

**Comment by abhinavsagar** [comment]
Go for it.

**Comment by giacomocerquone** [comment]
@abhinavsagar sorry but I can't find the geolocation md file inside the docs folder but I can't find it under versioned_docs.
What should I do? As you see under 0.60 the geolocation api is still there: https://facebook.github.io/react-native/docs/geolocation

**Comment by Simek** [comment]
The deprecation note has been added in the PR #1673 so the reported issue should be fixed now.
