### ISSUE TITLE
[Docs] Internal URLs are broken

### ISSUE THREAD

**Issue by abumostafa** [facebook/react-native-website#1154]
* Go to https://facebook.github.io/react-native/docs/webview#props or https://facebook.github.io/react-native/docs/webview#methods
* Click on any prop ex. `source`
* You will get 404 `https://facebook.github.io/react-native/docs/webview.md#source`

The correct URL is `https://facebook.github.io/react-native/docs/webview#source`

**Comment by raajnadar** [comment]
I tried the steps you mentioned but I couldn't reproduce the issue.
