### ISSUE TITLE
Add "space-evenly" as a valid value to "justifyContent" 

### ISSUE THREAD

**Issue by twelve17** [facebook/react-native-website#1188]
Hello,

It looks like support for "space-evenly" was added here: https://github.com/facebook/yoga/pull/658

Though it seems like the docs do not mention it here: https://facebook.github.io/react-native/docs/flexbox

<img width="808" alt="Screenshot 2019-08-16 at 11 25 20" src="https://user-images.githubusercontent.com/788325/63161762-bdf1cf80-c018-11e9-96f3-6dc82c4b67a9.png">

Cheers

**Comment by ecreeth** [comment]
I have already sent a pull request in #1115. Thanks for notifying!

**Comment by ecreeth** [comment]
You can close this now! PR **merged** in #1115
