### ISSUE TITLE
Some images in "Debugging" page are not loading. 

### ISSUE THREAD

**Issue by onstash** [facebook/react-native-website#119]
<img width="1440" alt="screen shot 2018-01-07 at 12 39 50" src="https://user-images.githubusercontent.com/4272832/34647405-055fc5be-f3a8-11e7-8edc-eaed2852eef4.png">

This issue is most likely present because the latest `master` changes haven't been deployed, perhaps. All / most images related issues have been fixed in https://github.com/facebook/react-native-website/pull/70, as far as I understand.

**Comment by hramos** [comment]
Looks like this is now fixed.
