### ISSUE TITLE
Facing issue with react-native bundle build

### ISSUE THREAD

**Issue by manojdp73** [facebook/react-native-website#1190]
![Issue_with_react_native_bundle_build](https://user-images.githubusercontent.com/54257237/63238221-fbe23400-c262-11e9-828f-b7e1fa519a03.PNG)
Hi ,
Pls help me with the issue. Facing issue during react-native bundle build
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
    Memory: 5.47 GB / 7.91 GB
  Binaries:
    Node: 10.16.0 - E:\Manoj\nodejs\node.EXE
    npm: 6.9.0 - E:\Manoj\nodejs\npm.CMD

Thanks and Regards,
Manoj Prithiani

**Comment by M1seRy** [comment]
Hi, you can try report your case in react native issues page => https://github.com/facebook/react-native/issues

**Comment by charpeni** [comment]
As said ^
