### ISSUE TITLE
Animation Documentation seems to have a Typo error on its first example

### ISSUE THREAD

**Issue by chandanSigncatch** [facebook/react-native-website#1249]
https://facebook.github.io/react-native/docs/animations#animated-api
fadeAdnim should be fadeAdmin on Animated Api example. Added a screenshot

<img width="635" alt="Screenshot 2019-09-08 at 9 22 56 PM" src="https://user-images.githubusercontent.com/52560427/64490853-0e0e2b80-d27f-11e9-94f2-08dac19a16ba.png">

**Comment by pureinx** [comment]
See pull #1241

**Comment by charpeni** [comment]
Fixed, thanks for reporting this!
