### ISSUE TITLE
React Native Docs Refresh plan through 2019

### ISSUE THREAD

**Issue by rachelnabors** [facebook/react-native-website#1272]
2019 React Native Docs Refresh

The docs site has grown organically since its conception, and because of this, has grown uneven in quality and quantity of content across different topics. Realigning the docs with what today’s learners need will require a bit of analysis to make sure our best efforts are put into the most important materials that learners need the most!

Over the past two months, I dove into analyzing our users, our offerings, and the landscape with:

* Content Analysis 
* Community Interviews 
* Community Surveys

## Goals for Rest of 2019

_The following goals informed by the above work and are subject to change as we proceed._

**Polish Component docs**—React Native developers refer to our components and API docs regularly each week. The following will make these docs even more useful to them.

- [ ] Round out code examples
- [ ] Refactor them to include hooks
- [ ] Add visual examples of each component
- [ ] Expand props definitions
- [ ] Bring props definitions up higher on the page via a sidebar
- [ ] Cross link to related or similar components
- [ ] Performance tips for each component (not lost in a guide in another location no one visits)

**Site retooling** including the following:

- [ ] **Version dropdown** because folks have been struggling to find version-specific information.
- [x] **Better analytics** to follow learners on their journey.
- [x] **“Was this helpful?” thumbs up/down** to help us measure how the new docs are doing
- [ ] **Reducing content size**—the site content has grown over the years. Conciseness and clarity, in addition to being a good measure of solid documentation, helps more people people learn faster.
- [x] **Style guide** for future contributions to be edited against (“we” vs “you”, “they” vs “he”, tone, etc).
- [x] **Automation** for checking contributions against the style guide, possibly using something like Alex.js (https://alexjs.com/); @rickhanlonii implementedintegrated.
- [ ] **Speak to everyone**—people with non-web backgrounds can have a longer ramp up with our getting starting docs. We can improve incorporating vocabulary and examples from Android and iOS communities.

**Reform the guides**—community interviews show that our learners need a bridge between our Getting Started tutorial and our Guides. At this intersection, they frequently go offroading on Google or Youtube or send their new hires to crash courses like Wix’s (https://github.com/wix/react-native-crash-course) —but we and they would prefer to come to the official docs as a Source of Truth for all things app dev related. If the guides were updated, culled, and organized, we could create a proper learning path for them to walk featuring:

- [x] A more skimmable sidebar in Docs
- [ ] Updated docs for readability
- [ ] Remove unused docs
- [x] Consolidate similar docs
- [x] Use hooks-driven code in examples

**Critical missing docs**—Through surveys and interviews we’ve identified the following important areas to invest in, and they also provide a fantastic opportunity to partner with domain expert community members and help spread their expertise:

- [ ] Performance—Anna Doubkova, Ram as tech reviewer
- [x] Testing—Vojtěch Novák
- [x] Privacy—Kadi Kraman
- [ ] Offline—Chi
- [ ] Native Modules—Ioannis Kokkinidis
- [ ] iOS Deployment
- [ ] Internationalization
- [ ] Navigation
- [ ] Intro to Debugging
- [ ] Animations
- [ ] iOS (tech reviewer for metaphor and wording)
- [ ] Android (tech reviewer for metaphor and wording)

**Basic maintenance** and other tasks that fall to the wayside:

- [ ] Add alt text to 36 images missing them
- [ ] Reduce overall wordcount
- [ ] Introduce real meta descriptions—80% are currently restatements of the h1 tag, broken, or missing
- [ ] Fix 48 broken links
- [x] Lint all pages for exclusionary language

**Comment by ecreeth** [comment]
### Reducing content size
I think it would be great to delete the old documentation

**Comment by rachelnabors** [comment]
@ecreeth Which ones in particular?

**Comment by ecreeth** [comment]
I'm not sure which versions are currently obsolete in React Native. I can see that in the upgrade helper it only supports versions greater than **0.23.1**

**Comment by haruelrovix** [comment]
> Why do you feel the older versions' docs are problematic?

See this changes on React Native for example.

- https://github.com/facebook/react-native/blob/v0.59.10/Libraries/Components/View/ViewAccessibility.js#L43
- https://github.com/facebook/react-native/blob/v0.60.0/Libraries/Components/View/ViewAccessibility.js#L16

Based on the changes, `AccessibilityRole` **before** v0.60 should contain **11** items only, from `none` to `summary`.

But here's the LIVE website on React Native docs.

![image](https://user-images.githubusercontent.com/17120764/67630862-9c3a8180-f8c0-11e9-8234-e92f4de0f4ee.png)

**Comment by rickhanlonii** [comment]
@haruelrovix why would we delete them instead of fixing them?

**Comment by ezranbayantemur** [comment]
@rachelnabors I could help about Turkish language support to docs. ReactJS has that option and it's been really useful. Do we have any plan about multi-language option for React Native too?

**Comment by rachelnabors** [comment]
Internationalization is high on our radar! We're currently solving for:

1) Updating the docs (so translations will be up to date, too)
2) Automating component and API docs updates (we'll need to select a translation option that works with our process)

We are definitely keeping an eye on this!

**Comment by Naturalclar** [comment]
I can help with the Japanese translation of the docs once the docs are ready 🤗

**Comment by rachelnabors** [comment]
Closing because it's 2020. These were ambitious goals, and we were just able to bring several of them to fruit with the help of the community (see #1579 #1633 #1469—thank you, everyone!).

The effort continues! Still looking for volunteers to write Offline, Internationalization, Intro to Debugging and Animations!
