### ISSUE TITLE
TV documentation fixes needed

### ISSUE THREAD

**Issue by brodybits** [facebook/react-native-website#1279]
__updated:__

On **Building For TV Devices** web page:

* ~~an internal Android tab seems to have no information~~
* it looks like some info _still_ needs to be updated now that Apple TV support was moved into the fork
* ~~The internal page URL and title are not consistent (see below)~~

Out of tree page:

* clarify or revert the changes from PR #1250 since the tvOS support is a fork and not a separate, out-of-tree module (see react-native-community/react-native-tvos#11 & react-native-community/react-native-tvos#14), my bad

Open question:

I am not certain whether or not Apple TV (tvOS) and Android TV will be supported in the same fork in the future. react-native-community/react-native-tvos#14 indicates that this may be the case, maybe the fork should be renamed if it will cover both tvOS and Android TV.

see also: #333

/cc @dlowder-salesforce @cpojer @charpeni

**Comment by rickhanlonii** [comment]
cc @rachelnabors, the [Building For TV Devices](https://reactnative.dev/docs/building-for-apple-tv) is out of date - starting with 0.62 users will need to begin using https://github.com/react-native-community/react-native-tvos to develop TV devices.

**Comment by brodybits** [comment]
This issue still does not seem to be resolved.

**Comment by Simek** [comment]
> This issue still does not seem to be resolved.

Hi @brodybits, can you elaborate on that? What is still missing in the TV devices docs?

**Comment by brodybits** [comment]
The info in the tvOS tab still seems to have information like this:

> - _Native layer_: React Native Xcode projects all now have Apple TV build targets, with names ending in the string '-tvOS'.

> - _react-native init_: New React Native projects created with `react-native init` will have Apple TV target automatically created in their XCode projects.

The out-of-tree page seems to still have some incorrect info, which should be corrected in PR #2308.

**Comment by Simek** [comment]
> The info in the tvOS tab still seems to have information like this:

True, but before those bullets you can see a notice that part of documentation is deprecated. Do you think it will be better to remove the whole Android TV content? It is not what we usually do, for example `Geolocoation` has been removed from the core in [`0.60`](https://reactnative.dev/blog/2019/07/03/version-60), but the docs content is still in there - https://reactnative.dev/docs/geolocation.
