### ISSUE TITLE
react-native run-android

### ISSUE THREAD

**Issue by detroit007** [facebook/react-native-website#1286]
When I run this command "react-native run -android" the error showed up:
Command `run` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project.

the solution it says "npm install" so I follow the instruction and it showed the error as well:

npm WARN hami No description
npm WARN hami No repository field.
npm WARN hami No license field.

npm install : solution I found on stackOverflow is :  "node your-script.jsnode your-script.js"
but it also showing error :

internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module '/home/hami/your-script.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

pls help!

**Comment by raajnadar** [comment]
`react-native run-android` this is the right cmd (No space)

**Comment by detroit007** [comment]
@raajnadar Thanks!
