### ISSUE TITLE
Outdated page in Android component docs

### ISSUE THREAD

**Issue by AbelTesfaye** [facebook/react-native-website#1291]
Hello,

There's a slightly outdated page I recently encountered: https://facebook.github.io/react-native/docs/native-components-android

Can I fix it and send a PR ( for Hacktoberfest ) ?

**Comment by Simek** [comment]
Hi @AbelTesfaye, I can see that your PR has been merged. Can I close this issue or are there more changes you want to introduce?

**Comment by AbelTesfaye** [comment]
Hi @Simek ,

Yeah, my PR has already been merged, I'll go ahead and close this issue. 

Thanks!
