### ISSUE TITLE
Getting Started Width Typescript

### ISSUE THREAD

**Issue by GreatAuk** [facebook/react-native-website#1298]
[React Native official doc](https://facebook.github.io/react-native/docs/0.60/typescript):
![image](https://user-images.githubusercontent.com/20253809/65763730-9da84b00-e156-11e9-80a6-dd63364f1a7a.png)
[react-native-template-typescript doc](https://github.com/react-native-community/react-native-template-typescript):
![image](https://user-images.githubusercontent.com/20253809/65763810-c7617200-e156-11e9-81d3-9e26e63bef50.png)

**Comment by Ildarik** [comment]
I think this issue isn't actual already
