### ISSUE TITLE
The react-native version number is wrong in the react-native website header. It shows 0.60 instead of 0.61.

### ISSUE THREAD

**Issue by gablabelle** [facebook/react-native-website#1313]
Hello,

The react-native version number is wrong in web site header at https://facebook.github.io/react-native/. It shows **0.60** instead of **0.61**.

<img width="1312" alt="Screen Shot 2019-10-01 at 2 07 53 PM" src="https://user-images.githubusercontent.com/1565793/65988036-11976b80-e455-11e9-8532-9b6e337a88ad.png">

**Comment by gablabelle** [comment]
https://github.com/facebook/react-native-website/pull/1296

**Comment by ecreeth** [comment]
Fixed in #1309
