### ISSUE TITLE
Add useWindowDimensions section

### ISSUE THREAD

**Issue by betoharres** [facebook/react-native-website#1315]
Hello,
I couldn't find a single search result for `useWindowDimension` mentioned by Dan in the last blog post about 0.61 release. Though, through debugging, I found that `useWindowDimwnsions` returns this object: 
```
iPhone 5s
{fontScale: 1, height: 568, width: 320, scale: 2}
```

Let me know if you guys would like me to do a PR.
Thanks

**Comment by ferrannp** [comment]
Came here to talk about the same :D. This is the PR and the description https://github.com/facebook/react-native/commit/5ec382d.

Where in the docs would make sense to have it? https://facebook.github.io/react-native/docs/dimensions page?

**Comment by rachelnabors** [comment]
Actually, it should have its own reactnative.dev/docs/useWindowDimensions page. `dimensions` is a separate API!
