### ISSUE TITLE
Lint docs for insensitive and inconsiderate language

### ISSUE THREAD

**Issue by rickhanlonii** [facebook/react-native-website#1338]
## Overview

**Update: All of the docs have been claimed 🚧🎉**

Now that we have landed the lint process and fixed the lint issues in the `docs/` directory, we're looking to also lint all of the instances of insensitive and inconsiderate language in the `versioned_docs` directory (i.e. the docs for old versions of React Native.

## How
If you want to lint one of these directories, follow these steps!

### Install
1. Fork the repo
2. Clone your fork
3. Go to the `website` directory and then `yarn install`

### Lint
1. Pick a version, comment here
2. Remove your version from the list in [`.alexignore`](https://github.com/facebook/react-native-website/blob/master/.alexignore#L7-L12)
3. Run this command:

```
yarn lintv website/versioned_docs/version-{version number}
```

This will output all of your errors as in:
<img width="1438" alt="Screen Shot 2019-10-14 at 8 26 40 PM" src="https://user-images.githubusercontent.com/2440089/66777448-f3a02100-eec0-11e9-9c3d-4df867b77747.png">

Once you fix all of the errors, commit all of the changes including the .alexignore file.

To be considerate to the reviewer, please submit each version in different PRs.
## How to fix

In most cases the work can be removed or replace (e.g. "just" could be changed to "only").

In other cases, where a word is quoted or a prop and cannot be changed, we can add  this to the line above:

```
<!-- alex ignore {rule name} -->
```

Where `{rule name}` is the name of the rule you want to ignore. So if you want to ignore the 'host-hostess' rule on a line, you would add this to the line above it:

```
<!-- alex ignore host-hostess -->
```

If you're stuck on what to change, check out the way it's used in the current `docs/` directory. If that doc is no longer there, feel free to ask for advice!

## Submitting PR
To make it easier to merge your PRs, please enable this setting so we can fix any minor issues (like merge conflicts) and merge your PR right away:

![image](https://user-images.githubusercontent.com/2440089/66912004-9d8ac500-f009-11e9-8a6c-806aa5d52cc0.png)

## Versions

| status | owner | version |
| ----- | ----- | ----- |
| ✅ Done | @thackley | `website/versioned_docs/version-0.5` |
| ✅ Done | @carolstran | `website/versioned_docs/version-0.6` |
| ✅ Done | @carolstran | `website/versioned_docs/version-0.7` |
| ✅ Done | @thackley | `website/versioned_docs/version-0.8` |
| ✅ Done | @salvariable | `website/versioned_docs/version-0.9` |
| ✅ Done | @carolstran | `website/versioned_docs/version-0.10` |
| ✅ Done | @thackley | `website/versioned_docs/version-0.11` |
| ✅ Done | @thackley | `website/versioned_docs/version-0.12` |
| ✅Done | @medeirosjoaquim | `website/versioned_docs/version-0.13` |
| ✅ Done | @thackley | `website/versioned_docs/version-0.14` |
| ✅ Done | @medeirosjoaquim | `website/versioned_docs/version-0.15` |
| ✅ Done | @mitulsavani  | `website/versioned_docs/version-0.16` |
| ✅ Done | @salvariable  | `website/versioned_docs/version-0.17` |
| ✅ Dome | @mitulsavani | `website/versioned_docs/version-0.18` |
| ✅ Done | @matthew-was | `website/versioned_docs/version-0.19` |
| ✅ Done | @matthew-was | `website/versioned_docs/version-0.20` |
| ✅ Done | @kirsty-simmonds | `website/versioned_docs/version-0.21` |
| ✅ Done | @isabelacmor | `website/versioned_docs/version-0.22` |
| ✅ Done | @walaura | `website/versioned_docs/version-0.23` |
| ✅ Done | @kirsty-simmonds | `website/versioned_docs/version-0.24` |
| ✅ Done | @mesaugat | `website/versioned_docs/version-0.25` |
| ✅ Done | @tchayen | `website/versioned_docs/version-0.26` |
| ✅ Done | @salvariable  | `website/versioned_docs/version-0.27` |
| ✅ Done | @eamoses | `website/versioned_docs/version-0.28` |
| ✅ Done | @eamoses | `website/versioned_docs/version-0.29` |
| ✅Done | @medeirosjoaquim  | `website/versioned_docs/version-0.30` |
| ✅ Done | @walaura | `website/versioned_docs/version-0.31` |
| ✅ Done | @hatwell | `website/versioned_docs/version-0.32` |
| ✅ Done | @walaura | `website/versioned_docs/version-0.33` |
| ✅ Done | @bolah2009 | `website/versioned_docs/version-0.34` |
| ✅ Done | @bolah2009 | `website/versioned_docs/version-0.35` |
| ✅ Done | @bolah2009 | `website/versioned_docs/version-0.36` |
| ✅ Done | @mats-codes | `website/versioned_docs/version-0.37` |
| ✅ Done | @bolah2009  | `website/versioned_docs/version-0.38` |
| ✅ Done | @leiteszeke | `website/versioned_docs/version-0.39` |
| ✅ Done | @jonodavis | `website/versioned_docs/version-0.40` |
| ✅ Done | @YutamaKotaro | `website/versioned_docs/version-0.41` |
| ✅ Done | @takutakutakujiro | `website/versioned_docs/version-0.42` |
| ✅ Done  | @dibosh | `website/versioned_docs/version-0.43` |
| ✅ Done | @salvariable  | `website/versioned_docs/version-0.44` |
| ✅ Done | @sogafish | `website/versioned_docs/version-0.45` |
| ✅ Done | @shukubota  | `website/versioned_docs/version-0.46` |
| ✅ Done | @salvariable | `website/versioned_docs/version-0.47` |
| ✅ Done | @Naturalclar | `website/versioned_docs/version-0.48` |
| ✅ Done | @sasurau4 | `website/versioned_docs/version-0.49` |
| ✅ Done | @lahin31 | `website/versioned_docs/version-0.50` |
| ✅ Done | @salvariable | `website/versioned_docs/version-0.51` |
| ✅ Done | @mats-codes | `website/versioned_docs/version-0.52` |
| ✅ Done | @mats-codes | `website/versioned_docs/version-0.53` |
| ✅ Done | @nitaking | `website/versioned_docs/version-0.54` |
| ✅ Done | @yakovleva-tanya | `website/versioned_docs/version-0.55` |
| ✅ Done | @salvariable | `website/versioned_docs/version-0.56` |
| ✅ Done | @mateosilguero | `website/versioned_docs/version-0.57` |
| ✅ Done | @hatwell | `website/versioned_docs/version-0.58` |
| ✅ Done | @anselb | `website/versioned_docs/version-0.59` |
| ✅ Done | @bolah2009 | `website/versioned_docs/version-0.60` |
| ✅ Done | @bolah2009 | `website/versioned_docs/version-0.61` |

**Comment by bolah2009** [comment]
I am working on `version-0.61`.

**Comment by thackley** [comment]
I'll start on `version-0.5`

**Comment by carolstran** [comment]
I can take `version-0.6` 🙋

**Comment by anselb** [comment]
I can work on `version-0.59`

**Comment by rickhanlonii** [comment]
Heads up @thackle, 0.5 will have the most issues (there are 179) because it's the initial docs so it has all of the files. All of the versions after that only include docs that are different the the previous version

If this is more than you signed up for then feel free to select another version!

**Comment by thackley** [comment]
@rickhanlonii Thanks for the heads up! 

Only thing left to do is modify `pop` in navigator.md but since that's not in the current `docs/` directory, thoughts on what to do?

**Comment by medeirosjoaquim** [comment]
I'll  work on version-0.59  !  :)

**Comment by medeirosjoaquim** [comment]
I also made a PR for version-015!

**Comment by jonodavis** [comment]
I will work on version 0.40

**Comment by rickhanlonii** [comment]
@thackley you could also change any instances that reference the method to \`pop\`, and any instances that reference the concept to "Get and remove the late item"

Examples:
And change

>  The `renderScene` method is changed to either push or pop the navigator depending on the current route's index.

To

>  The `renderScene` method is changed to either `push` or `pop` the navigator depending on the current route's index.

Change
> Pop to a particular scene, as specified by its route. All scenes after it will be unmounted.

To:
> Get a particular scene by its route, and remove all routes after it.

**Comment by lahin31** [comment]
I will work on version 0.50

**Comment by carolstran** [comment]
I can pick up `version-0.7` now 🍬

**Comment by lahin31** [comment]
Hi Ricky,
I found POP is a lint error it suggested to change Pop to Parent. But Pop is a Facebook's own open source project.

**Comment by hatwell** [comment]
I can take version-0.58 :)

**Comment by mateosilguero** [comment]
I want to work to 0.57 ! :)

**Comment by rickhanlonii** [comment]
@lahin31 for this instance I changed pop to \`pop\`

**Comment by salvariable** [comment]
I'll take version 0.56 💃

**Comment by yakovleva-tanya** [comment]
I'd like to work on 0.55 :)

**Comment by eduardocappellotto** [comment]
i'd like to work on 0.54

**Comment by nitaking** [comment]
I'll take version 0.53 😎

**Comment by rickhanlonii** [comment]
@nitaking could you pick another version?

**Comment by lahin31** [comment]
@rickhanlonii ok got it. I am working on the 0.50 then.

**Comment by mats-codes** [comment]
Hi, I'd love to work on 

0.53

**Comment by dibosh** [comment]
Taking `version-0.43`

**Comment by salvariable** [comment]
Taking 0.51 as well

**Comment by mats-codes** [comment]
I'll go for 0.52 as well :)

**Comment by rickhanlonii** [comment]
Hey all!

Great work so far!

One note on ignoring rules: I've noticed that I worded this poorly in the original description and I didn't specify that you'll need to provide the rule name you're ignoring.

So you can ignore with:

```
<!-- alex ignore {rule name} -->
```

Where `{rule name}` is the name of the rule you want to ignore. So if you want to ignore the 'host-hostess' rule on a line, you would add this to the line above it:

```
<!-- alex ignore host-hostess -->
```

I updated in the description as well👍

**Comment by salvariable** [comment]
Working on 0.47

**Comment by thackley** [comment]
i'll also take `version-0.8` 😀

**Comment by salvariable** [comment]
Sorry, version 0.9 is taken

**Comment by sasurau4** [comment]
I'll take `website/versioned_docs/version-0.49`

**Comment by Naturalclar** [comment]
Hello! I'd like to work on `website/versioned_docs/version-0.48`

**Comment by sogafish** [comment]
I will take version-0.47!

**Comment by shukubota** [comment]
I will take version-0.46

**Comment by takutakutakujiro** [comment]
I will take version-0.42!

**Comment by salvariable** [comment]
> I will take version-0.47!

0.47 is already in process

**Comment by sogafish** [comment]
> 0.47 is already in process
oh..
i take version-0.45

**Comment by rickhanlonii** [comment]
Hey all,

Great work! I'm amazed so many people are interested in helping out here, thank you all so much!

One note, to make it easier to merge your PRs: If you enable this setting then I can fix any minor issues (like merge conflicts) and merge your PR right away:

![image](https://user-images.githubusercontent.com/2440089/66912004-9d8ac500-f009-11e9-8a6c-806aa5d52cc0.png)

**Comment by YutamaKotaro** [comment]
I will take version-0.41!

**Comment by leiteszeke** [comment]
I'll take version-0.39 :D

**Comment by carolstran** [comment]
I can take `version-0.10` 🤸‍♀

**Comment by thackley** [comment]
I can take `version-0.11`

**Comment by thackley** [comment]
i'll also take `version-0.12` and `version-0.14` 🤓

**Comment by salvariable** [comment]
Closing that 0.44 gap 💪

**Comment by salvariable** [comment]
Will take on 0.17 too

**Comment by matheusmonte** [comment]
I can take 0.16

**Comment by salvariable** [comment]
Don't be afraid of the twenties... going for 0.27

**Comment by medeirosjoaquim** [comment]
Hi, Im doing version 0.30 :)

**Comment by mats-codes** [comment]
I'll take 0.37 as well.

**Comment by walaura** [comment]
hi! can I take `0.33`?

**Comment by mehtavishwa30** [comment]
Hello! I can take `version-0.18`! ✨

**Comment by matthew-was** [comment]
Hi, I can take `version-0.19`

**Comment by matthew-was** [comment]
changes to `version-0.20` are similar to `0.19` so I'll pick that up as well

**Comment by bolah2009** [comment]
Can I do 34, 35 and 36? I submitted PR for 38 now.

**Comment by rickhanlonii** [comment]
@matthew-was @bolah2009 sounds good! Please remember to put the different versions in different PRs branched from master so it's easier for us to review/merge 👌

**Comment by hatwell** [comment]
I can take 32 now :)

**Comment by kirsty-simmonds** [comment]
I would like website/versioned_docs/version-0.21 🐽

**Comment by tchayen** [comment]
I can take `version-0.26`

**Comment by kirsty-simmonds** [comment]
May I please have `website/versioned_docs/version-0.24` 🐽🐽

**Comment by rickhanlonii** [comment]
Saving 0.22 for @isabelacmor 👯‍♀️

**Comment by walaura** [comment]
Can I do `0.31` next? I'm hooked!

**Comment by mesaugat** [comment]
Can I take 0.25? I see that it is not taken.

**Comment by walaura** [comment]
`0.23` pls?

**Comment by rickhanlonii** [comment]
Wow, thanks everyone!

All of the docs have been claimed and there are only 13 left in progress!!

**Comment by rickhanlonii** [comment]
Just a few left now! If you need anything to wrap your version up just let me know! You can message here or if you feel more comfortable you can DM me on [twitter](https://twitter.com/rickhanlonii) 🛸

**Comment by dibosh** [comment]
Opened the PR(https://github.com/facebook/react-native-website/pull/1412/files) for `0.43`

**Comment by bolah2009** [comment]
@rickhanlonii I think `website/versioned_docs/version-0.38` is done in #1392 :thinking:

**Comment by rickhanlonii** [comment]
Just four more to go! It would be great to wrap this up by Monday so let's set a deadline of tomorrow morning to finish the remaining four - if you can't finish by then, no worries we're all here to help and someone else can take it over ✨

**Comment by mitulsavani** [comment]
Hi Ricky, 
I did not claim to work on v0.16, but I still submitted a PR (#1416). Feel free to merge it if you want to wrap this up sooner! Also, let me know if you want me to work on the other two remaining versions I can submit it in an hour.

**Comment by salvariable** [comment]
> Hi Ricky,
> I did not claim to work on v0.16, but I still submitted a PR (#1416). Feel free to merge it if you want to wrap this up sooner! Also, let me know if you want me to work on the other two remaining versions I can submit it in an hour.

Glad to help with one more if needed

**Comment by rickhanlonii** [comment]
Thanks you!

Yeah if either of you want to do the last version (0.18) that would be great!

**Comment by mitulsavani** [comment]
I got it

**Comment by rickhanlonii** [comment]
WOW YOU ALL FINISHED THIS IN 6 DAYS 🎉

THANKS SO MUCH 💖✨

**Comment by rickhanlonii** [comment]
Huge shout out to all of the people who helped out, you all make me proud to be a part of this community: @salvariable @bolah2009 @thackley @walaura @medeirosjoaquim @mats-codes @carolstran @mitulsavani @matthew-was @kirsty-simmonds @hatwell @eamoses @YutamaKotaro @yakovleva-tanya @tchayen @rickhanlonii @takutakutakujiro @sogafish @shukubota @sasurau4 @nitaking @Naturalclar @mesaugat @mateosilguero @leiteszeke @lahin31 @jonodavis @isabelacmor @dibosh @anselb ⚛️✨
