### ISSUE TITLE
Right sidebar breaking when end of the page is reached

### ISSUE THREAD

**Issue by kaueDM** [facebook/react-native-website#1358]
```
MacOS Mojave 10.14.3
Chrome 77.0.3865.120 (64 bits)
```

<img width="1440" alt="snap" src="https://user-images.githubusercontent.com/20171863/66871046-332a4400-ef79-11e9-86d0-edf6db3b5af9.png">

**Comment by elharony** [comment]
I see!
Give me a few minutes, and I will fix it 👍

**Comment by elharony** [comment]
Noticed.
I will try to fix it today 🙏

**Comment by cpojer** [comment]
Fixed in https://github.com/facebook/react-native-website/pull/1506
