### ISSUE TITLE
Learn the Basics example "Hello World" window is blank

### ISSUE THREAD

**Issue by dannypike** [facebook/react-native-website#1368]
I just tried reading the introduction ("Learn the Basics") and I was presented with a [blank window](http://prntscr.com/pjwgqa) for the Hello World example.

I am using Firefox Quantum 69.0.3 (64-bit) on Windows 10 1809 (build 17763.737)

**Comment by dannypike** [comment]
More info:

1. The [root](http://prntscr.com/pjwiqe) div is empty when I inspect it;
1. It works OK on Chrome

**Comment by elharony** [comment]
To save the project maintainer some time, I've tested it on the following browsers, and it works fine:
- `Brave` - _Version 0.69.135 Chromium: 77.0.3865.120 (Official Build) (64-bit)_
- `Safari` - _IOS 13.1.2_

Does it mean that it works on all major browsers, except `Firefox Quantum`? 🤔 

Btw, do you see any errors in your `Console`?

**Comment by dannypike** [comment]
Well done, @elharony !

My FF was configured to block cookies from websites that I have not visited already and that broke the tutorial. May be worth considering putting a check in it to see that you are able to use foreign cookies? Anyway, problem is fixed, thank you

**Comment by elharony** [comment]
I think it worth a `Warning/Note`, as I guess it's related to [docusaurus](https://docusaurus.io/) (The documentation tool RN use), and if my assumption is correct, it would be affecting many documentation websites as well.

Hope someone gives us some insights here!
