### ISSUE TITLE
tiny_log.png not loaded in Image component on Android 

### ISSUE THREAD

**Issue by nottledim** [facebook/react-native-website#1370]
The tutorial page https://facebook.github.io/react-native/docs/using-a-scrollview introduces the use of Image component which refers to the tiny_logo.png image https://facebook.github.io/react-native/img/tiny_logo.png

This image does not display on Android using the Expo app.  An error 'unknown image format' is generated.

Looking at this file it seems it is not a png file at all; it's an "MS Windows icon resource - 4 icons, 16x16, 32 bits/pixel, 24x24, 32 bits/pixel"   i.e 4 .ico images of different sizes.

These icons can be extracted to png files using a tool such as ImageMagik and the browser does this too but Android doesn't.

The example needs to be amended so it works (please)!

**Comment by elharony** [comment]
Interesting issue. 

I tried to use ImageMagik to export it as png, but I got the following error: `IMDisplayDoc function [DoReadImage] reported an error. imdisplay.exe: improper image header C:\PATH\tiny_logo.png' @ error/png.c/ReadPNGImage/4294`.

Furthermore, I did my research on any tool that converts `MS Windows icon` to `PNG` and no luck, couldn't find any working tool.

Do you have any recommendations here, @notjiam ?

### System Configuration
- Windows 10 Pro
- ImageMagick version: ImageMagick-7.0.9-Q16

**Comment by Simek** [comment]
Current version of [Using a ScrollView](https://reactnative.dev/docs/using-a-scrollview) example is working properly for me on Android. Can you confirm that the issue has been fixed?

**Comment by nottledim** [comment]
Oh!  I gave up with native at that point; I went a different route.  I'll put it on my list of things to do (but don't hold your breath).

**Comment by Simek** [comment]
@nottledim I'm going to close this issue for now, but please reopen this issue or post the new one if you find any problems with the current examples in the docs.
