### ISSUE TITLE
Broken Link - Direct-Manipulation.md

### ISSUE THREAD

**Issue by eyalcohen4** [facebook/react-native-website#143]
Hey! Great docs.

The link referenced to ref-callback in the [Direct-Manipulation](https://facebook.github.io/react-native/docs/direct-manipulation.html) section is broken.

Here's a link to the [code](https://facebook.github.io/react-native/docs/direct-manipulation.html), and the [broken link](https://reactjs.org/more-about-refs.md#the-ref-callback-attribute).

Thanks!

**Comment by yashovardhanagrawal** [comment]
I think this is the link
https://reactjs.org/docs/refs-and-the-dom.html#adding-a-ref-to-a-dom-element
