### ISSUE TITLE
Site is scoring a 96 on accessibility

### ISSUE THREAD

**Issue by tomzmyslo** [facebook/react-native-website#1441]
Current Lighthouse audit only scores 96 for accessibility. Adding `lang` attribute to the `html` element should boost the score to 💯.

**Comment by JoelMarcey** [comment]
cc @endiliey , @yangshun as we look at Docusaurus v2. And maybe a fix to v1 as well.

**Comment by nel417** [comment]
I can confirm, just ran a lighthouse test on the homepage, and adding a lang to the html element and the sufficient color contrast are the big ones. I also ran an Axe audit and there were a few more. Mostly visible labels for forms and closed captions for videos were the biggest hitters.
