### ISSUE TITLE
onSubmitEditing prop works in multiline TextInput if blurOnSubmit passed

### ISSUE THREAD

**Issue by natasha08n** [facebook/react-native-website#1459]
According to documentation: https://facebook.github.io/react-native/docs/textinput#onsubmitediting

```onSubmitEditing is invalid if multiline={true} is specified.```

But it is incorrect because `onSubmitEditing` method is invoked if input is `multiline` and has `blurOnSubmit` prop with `true` value

Example:
```
<TextInput
                ref={textInputRef}
                style={styles.text}
                onSubmitEditing={submitValue}
                defaultValue={currentValue}
                value={value}
                onChangeText={handleChange}
                underlineColorAndroid="transparent"
                placeholder={placeholder}
                autoCorrect={false}
                numberOfLines={2}
                placeholderTextColor="rgba(255, 255, 255, .6)"
                multiline
                blurOnSubmit
/>
```

RN version: 0.59.10
Tested on Android and iOS

**Comment by isa3bel** [comment]
I'll remove this line and submit a PR

**Comment by isa3bel** [comment]
this issue is resolved, how do I resolve/close the issue?

**Comment by charpeni** [comment]
@isa3bel Thanks for letting us know! I'll close it.

**Comment by syedamirali14** [comment]
onSubmitEditing prop is not working in multiline true TextInput if blurOnSubmit passed @isa3bel @charpeni @natasha08n
