### ISSUE TITLE
Non-Working Example Is Used In AppState docs

### ISSUE THREAD

**Issue by iway1** [facebook/react-native-website#1470]
The example used at https://facebook.github.io/react-native/docs/appstate does not work because of a misuse of the `this` keyword in a scope where it doesn't refer to the object the author thinks it refers to. Specifically, the code sets up a listener to call a function that is within a `React.Component`. Within that function, there is a line of code referencing `this.state.appState`... The problem is, `this` does not refer to the React Component when that function is called via event listener. Therefor, the code just throws an undefined error since this.state is undefined when the function is called from the event listener. Also, the code calls `this.setState` which again will not work for the same reason.

The `/appstate` docs need to be adjusted to avoid this common JS scoping error, and to provide a code example that actually runs without an error.

**Comment by Simek** [comment]
Current version of [AppState](https://reactnative.dev/docs/appstate) class component example is working properly for me. Can you confirm that the issue has been fixed?
