### ISSUE TITLE
Accessibility properties: accessibilityValue property not included in 0.61.5

### ISSUE THREAD

**Issue by msalpietro** [facebook/react-native-website#1489]
Looks like the [commit for accessibilityValue](https://github.com/facebook/react-native/commit/7df3eea1a79f12c2dfff1976d0cef605a83232ec) isn't currently included in the latest release, 0.61.5, but made it into the docs.

**Comment by Simek** [comment]
Hi @msalpietro, according to the detailed [release notes](https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#v0620) this commit was a part of 0.62.0 release (search for `7df3eea1a7`).
