### ISSUE TITLE
Links in blog/atom.xml feed are broken

### ISSUE THREAD

**Issue by floriancargoet** [facebook/react-native-website#149]
In the blog's [atom feed](http://facebook.github.io/react-native/blog/atom.xml), links to articles are broken.
They point to, e.g., 
 - /blog/2018/01/18/implementing-twitters-app-loading-animation-in-react-native.html (which redirects to https://code.facebook.com)
 - instead of **/react-native**/blog/2018/01/18/implementing-twitters-app-loading-animation-in-react-native.html

**Comment by hramos** [comment]
Great find! This may require fixing in the Docusaurus project itself: https://github.com/facebook/Docusaurus

**Comment by hramos** [comment]
I've opened a PR to fix this: https://github.com/facebook/Docusaurus/pull/421

**Comment by bcallaars** [comment]
I think the feeds are still not working, as they point to `https://facebook.github.io/blog/atom.xml`.

**Comment by endiliey** [comment]
@bcalaars this will be fixed when this repository updated their docusaurus version 😊

**Comment by charpeni** [comment]
Docusaurus has been updated, it should be fixed by now. Let's close this, thanks!
