### ISSUE TITLE
Error in simulator when visiting the site

### ISSUE THREAD

**Issue by quinlanj** [facebook/react-native-website#150]
When I visit https://facebook.github.io/react-native/docs/flexbox.html , around 15-20 seconds after the page loads, the simulators error with `TypeError: Cannot read property 'undefined' of undefined`, even though nothing has changed in the text box. I'm running osx 10.12.6 with Chrome Version 63.0.3239.132 (Official Build) (64-bit).

![screen shot 2018-01-20 at 10 55 00 am](https://user-images.githubusercontent.com/6380927/35186905-c8b9efee-fdd0-11e7-87d8-f560c6c5fb50.png)

**Comment by hramos** [comment]
I haven't seen this happen, I'll leave it open in case other people see the same issue.

**Comment by charpeni** [comment]
I haven't seen this issue either on OSX or Windows.

It may looks like a memory issue to me, have you tested it on another page with multiple simulators or monitor your RAM?
