### ISSUE TITLE
Links on CameraRoll Documentation are Broken

### ISSUE THREAD

**Issue by bobber205** [facebook/react-native-website#1503]
On https://facebook.github.io/react-native/docs/cameraroll.html#savetocameraroll

![image](https://user-images.githubusercontent.com/5841107/70461881-85b24900-1a6e-11ea-8cf3-af8c325bb430.png)

**Comment by isa3bel** [comment]
ill tackle this one!

**Comment by isa3bel** [comment]
docs/cameraroll.md is not in the repo right now, so not sure how to fix this?

**Comment by bobber205** [comment]
When I looked into this I think it's displaying the 0.58 version

**Comment by isa3bel** [comment]
I was testing on the .58 version and I don't think it was, Ill create a PR anyways to get more feedback

**Comment by isa3bel** [comment]
it isn't working on .61 right now
