### ISSUE TITLE
Enhancement: Add Platform API Doc

### ISSUE THREAD

**Issue by hramos** [facebook/react-native-website#1509]
The Platform module does not have a dedicated API doc (e.g. a dedicated entry under the API sub-group in the API reference). It is documented under Platform specific code at https://facebook.github.io/react-native/docs/platform-specific-code#platform-module. For discoverability and completeness, I believe this module deserves to have its own API doc at https://facebook.github.io/react-native/docs/platform (Under the API -> APIs sidebar menu).

**Comment by Simek** [comment]
The current implementation of this API can be found here:
* [Android](https://github.com/facebook/react-native/blob/master/Libraries/Utilities/Platform.android.js)
* [iOS](https://github.com/facebook/react-native/blob/master/Libraries/Utilities/Platform.ios.js)

**Comment by zanona** [comment]
I completely agree, It's curious that the first example on https://reactnative.dev/docs/platform-specific-code#platform-module starts with
```js
import { Platform, StyleSheet } from 'react-native';
```

Where `StyleSheet` is listed under the API dropdown but `Platform` isn't.
Took me a while to find it. :smiley:

**Comment by Tundeh** [comment]
Can i take on this issue? 
also, I'm new here.

**Comment by Naturalclar** [comment]
@Tundeh are you still willing to work on this issue?
Any help would be appreciated 😄

**Comment by Tundeh** [comment]
> 
> 
> @Tundeh are you still willing to work on this issue?
> Any help would be appreciated 😄

Yes. I'm interested.
