### ISSUE TITLE
Guides for app icon and splashscreen both android & ios

### ISSUE THREAD

**Issue by raajnadar** [facebook/react-native-website#1513]
Already mentioned here https://github.com/facebook/react-native-website/issues/917#issuecomment-491024595

But it is not added in the umbrela thread https://github.com/facebook/react-native-website/issues/929

We really need the guide how to add splash screen as well as app icon for both android and ios in react native application. I didn't find any medium post or any blog post.

**Comment by luism3861** [comment]
try to find in medium posts , create splash screen it;s very easy in RN.

**Comment by raajnadar** [comment]
I tried searching before creating this issue, I found few articles but they are either old, platform specific or they use library.

If you know any good article please share here. I want very simple splash no animation the splash should be visible until data is loaded from db.

**Comment by luism3861** [comment]
i found this article you should read this !!
good luck 
https://whatdidilearn.info/2019/01/13/how-to-implement-a-splash-screen-in-react-native.html

**Comment by elibroftw** [comment]
Can this be reopened? @cpojer , these [goals from 2019](https://github.com/facebook/react-native-website/issues/917#issuecomment-491024595) were never completed
