### ISSUE TITLE
DocumentSelectionState link in TextInput documentation is broken

### ISSUE THREAD

**Issue by seraco** [facebook/react-native-website#1518]
The link to `DocumentSelectionState` in `vendor/document/selection/DocumentSelectionState.js` is broken (see at https://facebook.github.io/react-native/docs/textinput#selectionstate).
<img width="817" alt="Screenshot 2019-12-18 at 12 36 29" src="https://user-images.githubusercontent.com/25517036/71084464-9f057480-2195-11ea-8948-7844ea92cb83.png">

**Comment by evanc** [comment]
looks like this prop will be removed in 0.62:
https://github.com/facebook/react-native/commit/2becdfd4041f7f28138ba3a61c03e17c06dc2e50

**Comment by Simek** [comment]
The described issue has been fixed in the linked PR. It's also true that this property has been removed with `0.62` so the latest docs are not affected. 

I think that this issue can be closed now, feel free to correct me and reopen this if I have missed something!
