### ISSUE TITLE
Add documentation for DevSettingsModule

### ISSUE THREAD

**Issue by rickhanlonii** [facebook/react-native-website#1523]
In https://github.com/facebook/react-native/pull/25848 we added a new method to DevSettings `addMenuItem` which allows users to add additional dev menu options to their app.

This module was previously undocumented because it was mostly only used internally.

Now that there's a method users may use, we should document it.

**Comment by mohamedsgap** [comment]
Can I write a doc for it ?

**Comment by rickhanlonii** [comment]
Yeah that would be awesome!

**Comment by mohamedsgap** [comment]
it sounds good, I gonna work on it and I'll make my PR asap!

**Comment by mohamedsgap** [comment]
@rickhanlonii Where should I write the doc ? in settings.md!!

**Comment by rickhanlonii** [comment]
@mohamedsgap I would add it as an API reference like https://facebook.github.io/react-native/docs/clipboard

**Comment by mohamedsgap** [comment]
Hey @rickhanlonii just need you to review DevSettings API reference #1539 to see if i wrote it correctly or need some changes!

**Comment by estevaolucas** [comment]
@rickhanlonii can we add a reference for `reload` method as well? https://github.com/facebook/react-native/pull/25848/files#diff-bd79be22516654291770eb407afd366fR33-R35

**Comment by rachelnabors** [comment]
Looks like the docs are baked! Thank you, all!

**Comment by rickhanlonii** [comment]
@estevaolucas yeah feel free to submit a PR!

**Comment by estevaolucas** [comment]
@rickhanlonii  it's already fixed. @Simek already added the reference for `reload method here https://github.com/facebook/react-native-website/pull/1722. Thank you!
