### ISSUE TITLE
[Native Modules] Implementing + requiresMainQueueSetup - Swift Part missing

### ISSUE THREAD

**Issue by jitenderbadoni** [facebook/react-native-website#1531]
Below part mentioned only for objective c developer, needed for swift developer as well.

`+ (BOOL)requiresMainQueueSetup
`{`
  return YES;  // only do this if your module initialization relies on calling UIKit!
}`

**Comment by rachelnabors** [comment]
Thanks for your PR! Love it when someone solves their own issue :)
