### ISSUE TITLE
Docs: wrong option info is provided at documentation

### ISSUE THREAD

**Issue by HADMARINE** [facebook/react-native-website#1537]
### Need to enter ### 
<code>npx react-native init TSApp --template typescript</code>
### but written ###
<code>npx react-native init TSApp --template react-native-template-typescript</code>
<br/>
at : <a>https://facebook.github.io/react-native/docs/getting-started</a>

**Comment by Naturalclar** [comment]
Hi @HADMARINE :wave:
I believe this is not a mistake.
`--template typescript` is currently outdated.
[react-native-template-typescript](https://github.com/react-native-community/react-native-template-typescript) is more up to date :)

**Comment by HADMARINE** [comment]
Oh, but when i give a argument <code>--template react-native-template-typescript</code>,<br> it requests an template named **react-native-template-react-native-template-typescript**, <br>and returns error like : <code>error An unexpected error occurred: <br>"https://registry.yarnpkg.com/react-native-template-react-native-template-typescript: Not found".</code>.<br>
Then I tried to give an argument like : **--template typescript**<br> then it worked properly and requested template to **react-native-template-typescript**.

**Comment by Naturalclar** [comment]
@HADMARINE 
I see!
May I ask what version of react-native cli you are using? (either globally or in the package.json of the folder you're running `npx` on)
The behavior may have changed over time.

**Comment by HADMARINE** [comment]
I seem it runs on **0.61.5**

**Comment by HADMARINE** [comment]
oh sorry, it was **2.0.1**

**Comment by Naturalclar** [comment]
@HADMARINE 
Thanks for checking! :)

Indeed, in cli version 2.0.1, it does add `react-native-template-` before the name.
https://github.com/react-native-community/cli/blob/v2.0.1/packages/cli/src/commands/init/templateName.js#L79

cli has removed that header in the latest version (**v2.10.0** or **v3.x**)
If you upgrade the cli, it should work with 

```
npx react-native init --template react-native-template-typescript
```

**Comment by HADMARINE** [comment]
Okay, Thanks for your kindness :)
