### ISSUE TITLE
Add a link to the Canny board in the main React Native repo's README and on the website

### ISSUE THREAD

**Issue by pcowgill** [facebook/react-native-website#1550]
Add a link to the [Canny board for feature requests](https://react-native.canny.io/) in the main React Native repo's README and on the website

**Comment by Simek** [comment]
There is no link to Canny.io in the React Native README or repo files:
* https://github.com/facebook/react-native/search?q=canny&unscoped_q=canny

As far as I know [react-native-community/discussions-and-proposals](https://github.com/react-native-community/discussions-and-proposals) repository is the official place to request features in React Native.

**Comment by pcowgill** [comment]
> As far as I know react-native-community/discussions-and-proposals repository is the official place to request features in React Native.

I wasn't aware of that repo - good to know!

We should make an issue about this over in that repo too.

And this issue should also be about linking out to that repo so people can find it.

**Comment by Simek** [comment]
Discussions and proposals repository is mentioned on the main community/help page (https://reactnative.dev/help) as well as other usefull places.

**Comment by Simek** [comment]
Issue templates has been imported from the React Native repository. Now the disscussions and proposals repo link is also located in the new issue flow: https://github.com/facebook/react-native-website/issues/new/choose

**Comment by pcowgill** [comment]
> Discussions and proposals repository is mentioned on the main community/help page (https://reactnative.dev/help) as well as other useful places.
> 
> 
> This repository is also linked in React Native [README](https://github.com/facebook/react-native#discussions).

This is good to know, thanks!
