### ISSUE TITLE
geolocation API is excluded, however the doc is still accessible

### ISSUE THREAD

**Issue by novalagung** [facebook/react-native-website#1554]
The documentation page of **geolocation API** is still accessible through https://facebook.github.io/react-native/docs/geolocation. Even after in the source (`geolocation.md`) is removed months ago.

I'm not sure why the live website is not yet updated to reflect the current source. This is [causing some confusion](https://stackoverflow.com/a/56909007/1467988) for developers, since when we google using keyword `react native geolocation api` the particular page will showing up as first result.

I suggest to update the live website.

**Comment by Simek** [comment]
@novalagung Deprecation note has been added. Is it enough to fix this issue?

**Comment by novalagung** [comment]
@Simek yes I think it would be enough. thank you
