### ISSUE TITLE
Missing steps to start a brand new project

### ISSUE THREAD

**Issue by tanapaydin** [facebook/react-native-website#1555]
Missing steps about "pod install" command within the "ios" folder. I guess, someone should follow the exact steps in the currrent version of this documentation, and see what other steps are missing.

**Comment by rachelnabors** [comment]
Would you like to update the docs and submit a PR? We'd suuuuuper appreciate it!

**Comment by rachelnabors** [comment]
(I mean, I can only fresh-install so many times on my computer ;)

**Comment by Simek** [comment]
As mentioned in #1444 and #1112 you shouldn't have to install Pods dependencies by yourself, CLI should handle it. 

Getting started guide has been updated so if you still having any problems with installation of latest version of React Native and Pods please create the new issue.
