### ISSUE TITLE
Small enhancement to the animated doc

### ISSUE THREAD

**Issue by kelset** [facebook/react-native-website#1573]
Basically, in the Animated doc is not super clear that you have a callback option for `start()`; the only section mentioning [it is here](https://facebook.github.io/react-native/docs/animated.html#working-with-animations) as far as I can tell.

I think it would be super helpful/clarifying to have a clearer code sample. The closest thing to it is in a reply on a GH issue of the main repo:

`this.animateValue.spring({}).start(function onComplete() {})`
[(src)](https://github.com/facebook/react-native/issues/3212)

Which I think is also outdated, because according to the link above in the docs should be something like

`this.animateValue.spring({}).start((finished) => {})`

(at least, I think - ideally it would be better to go and check source code)

---

BTW I only found out about this via a [StackOverflow issue](https://stackoverflow.com/questions/38053071/react-native-animated-complete-event) so yeah it seems that it's quite relevant.

I'll assign to myself and try to tackle asap, just can't now but don't want to lose track of this.

(also, it's probably a really good first issue for someone trying to do their first contribution so I'll add that tag too)

**Comment by gedeagas** [comment]
hi @kelset , are you still planing to tackle this? if not, I would love to help.

**Comment by kelset** [comment]
Hey @gedeagas - no I haven't had time yet, feel free to do a PR for it if you want :)

**Comment by rachelnabors** [comment]
It would be great if `start` was listed under Animated's methods, too! Please tag this with #1579 to get credit for completing the API docs, @gedeagas!

**Comment by gedeagas** [comment]
@kelset Awesome, i will be taking this then.

@rachelnabors thank you for the information, will do.

**Comment by Simek** [comment]
The issue reported here has been fixed by the merge of PR created by @gedeagas.
