### ISSUE TITLE
[BUG]Doc display error

### ISSUE THREAD

**Issue by DonaldDai** [facebook/react-native-website#1616]
Hi~I'm walking through your doc at [AppRegistry](https://facebook.github.io/react-native/docs/0.8/appregistry#registercomponent) and I find something which is maybe wrong. (check the image showing bellow)

the word `requie`d shoule be `required`.

![error img](https://cdn-std.droplr.net/files/acc_513938/vu0MEo)

I've checked the original doc file and It's fine. So I was thinking about it is something wrong with detecting.

It's not a typo and may affect other docs.

**Comment by florianmari** [comment]
It looks find on the repo, maybe web version is on an older version, after checking history we can see the typo has been already fixed

**Comment by Usamaliaquat123** [comment]
+1

**Comment by cHaLkdusT** [comment]
This has been fix in pull request #533.

By the way, @DonaldDai  you are using v0.8 of the documentation. Please refer to the latest version [v0.61](https://reactnative.dev/docs/appregistry#registercomponent)
