### ISSUE TITLE
Broken link in the "Integrating with Existing Apps" page

### ISSUE THREAD

**Issue by rocboronat** [facebook/react-native-website#1644]
The button `Getting Started guide` points nowhere.

This is the page I'm talking about: https://facebook.github.io/react-native/docs/integration-with-existing-apps

Thanks for keeping the documentation updated!

**Comment by gedeagas** [comment]
i think @rachelnabors pr #1535 fix this.

**Comment by rachelnabors** [comment]
Thanks for the catch, both of you!
![klk_nice-catch](https://user-images.githubusercontent.com/236306/77170016-591cbd00-6ab2-11ea-9e98-ab5ffc914f85.gif)

**Comment by rocboronat** [comment]
Hey @rachelnabors, the link is still broken...
