### ISSUE TITLE
Gitignore template small improvement (ignore HPROF files)

### ISSUE THREAD

**Issue by zatloeri** [facebook/react-native-website#1650]
### I would suggest adding ignore rule for Android-specific Heap/CPU Profiling (HPROF) files into [gitignore template](https://github.com/facebook/react-native/blob/master/template/_gitignore)

They can get easilly generated into the project repo and if these files get commited by accident they can really mess with your git repo since **they can get really large**. 

There are even some issues on stackoverflow tackling this and in this [issue](https://stackoverflow.com/questions/49099131/recommended-gitignore-for-react-native/49099219#49099219) there is even a reference to [gitignore template](https://github.com/facebook/react-native/blob/master/template/_gitignore) with ignore rule for HPROF files added.

**It is a really small change but could save somebody some time**.
Unless there is a reason not to exclude these files from git which I am not aware of.

**Comment by hramos** [comment]
I think it's alright to send a PR for this to the core repo. I'm going to close this, as it's not related to the website.
