### ISSUE TITLE
Documentation links are broken

### ISSUE THREAD

**Issue by suraneti** [facebook/react-native-website#1660]
All links and documents format in https://reactnative.dev/versions seems broken.

**Comment by rachelnabors** [comment]
Can you give us step by step instructions to reproduce? I'm able to get to versioned getting started pages personally

**Comment by suraneti** [comment]
@rachelnabors Right now everything is ok, but two days ago all link returns 404. 

Step to reproduce:
1. Go to link: https://reactnative.dev/versions.
2. Click the link on the documentation (all versions).
3. All links redirect with 404.

**Comment by Simek** [comment]
@suraneti LGTM right now, can we close this issue?
