### ISSUE TITLE
Documentation is broken

### ISSUE THREAD

**Issue by developerantoniosousa** [facebook/react-native-website#1661]
Hi!

[Documentation](https://facebook.github.io/react-native/) is broken.

**Comment by luism3861** [comment]
the domain  change try with.
https://reactnative.dev/docs/getting-started

**Comment by developerantoniosousa** [comment]
@luism3861 thank you!
I had accessed before PR [1662](https://github.com/facebook/react-native-website/pull/1662) is merged
