### ISSUE TITLE
Documentation does not load due to "reactnative.dev" transition

### ISSUE THREAD

**Issue by AJCStriker** [facebook/react-native-website#1663]
It appears that there is an in progress attempt to migrate the documentation from facebook.github.io to reactnative.dev that has broken the documentation.

Currently documentation links are showing a 404 after being redirected to reactnative.dev.

Example - https://reactnative.dev/react-native/docs/getting-started

**Comment by luism3861** [comment]
the domain change try with https://reactnative.dev/docs/getting-started
