### ISSUE TITLE
Versioned links for the current version

### ISSUE THREAD

**Issue by sonicdoe** [facebook/react-native-website#1678]
It’s great to be able to browse and link to documentation from React Native v0.60 all the way back to React Native v0.5. However, it’s not possible to link specifically to documentation of the current version, v0.61. Instead, the link will always point to the latest version of React Native.

In other words, it would be helpful if [`/docs/0.61/getting-started`](http://reactnative.dev/docs/0.61/getting-started) worked before React Native v0.62 is released.

**Comment by Simek** [comment]
Thank you for the suggestion. I like it but unfortunately there is no option to configure Docusurus to work in the suggested way. To read more about paths generation you can visit Docusurus [Versioning](https://docusaurus.io/docs/en/versioning) guide. 

Also upcoming V2 (website is using V1) do not support paths as described above, so if you want to proceed this idea of improvement further I would recommend to create a feature request in the Docusurus [repo](https://github.com/facebook/docusaurus).

**Comment by sonicdoe** [comment]
Thank you for pointing to Docusaurus. I’ve found that this feature has already been requested [for Docusaurus v1](https://github.com/facebook/docusaurus/issues/1312) and [for Docusaurus v2](https://docusaurus-2.netlify.app/feedback/p/permanent-url-support-for-current-version).
