### ISSUE TITLE
React Native Showcase Link Broken

### ISSUE THREAD

**Issue by sazzadsazib** [facebook/react-native-website#1724]
Hello, I was going through react native docs, in this [Showcase](https://reactnative.dev/docs/more-resources#examples) section it has a broken link !

**Comment by Naturalclar** [comment]
@sazzadsazib nice catch! the correct link seems to be `https://reactnative.dev/showcase/`
Would you like to send a PR to fix this?

**Comment by sazzadsazib** [comment]
Alright !
