### ISSUE TITLE
Please add screenshots or snacks for each simple component

### ISSUE THREAD

**Issue by charles-goode** [facebook/react-native-website#1758]
As a front-end react native developer, I spend a lot of time window-shopping for components to use from various libraries. All good libraries always have screenshots from both platforms (where applicable) for a component in its documentation. This would probably take an intern like one afternoon and would make the website pop much more.

**Comment by rachelnabors** [comment]
You should see this in the **/docs/next/** version of the docs right now and shortly Snacks will be included in all APIs and Components in the 0.62 version of the docs. We just completed #1579 to address this. Thanks so much for sharing how important these changes are!

**Comment by rachelnabors** [comment]
(But it did take significantly more than one intern an afternoon to complete this challenge—we had 29 volunteers working over two months! Awesome folks, and I want to give their efforts a shout out!)
