### ISSUE TITLE
Tutorial Expo code editor breaks style object

### ISSUE THREAD

**Issue by tuckerzb** [facebook/react-native-website#1802]
In the first Expo code editor of the Tutorial, it seems the closing `}]` braces of the style object have auto-inserted, breaking the live preview. Oddly, this does not appear in the repo when I check tutorial.md

<img width="1034" alt="Screen Shot 2020-03-30 at 2 14 19 PM" src="https://user-images.githubusercontent.com/55966263/77946957-26807a80-7291-11ea-991b-0e8b09f3bcfb.png">

**Comment by Simek** [comment]
My PR was merged, can you confirm that your issue has been fixed?

**Comment by tuckerzb** [comment]
Fixed! Thanks @Simek

**Comment by Simek** [comment]
Nice to hear that, can you close this issue then?
