### ISSUE TITLE
Faulty closing brackets in "Hello World!" example

### ISSUE THREAD

**Issue by jairaja** [facebook/react-native-website#1804]
Firefox ver - 74.0

Highlighted in Red in below image:
![image](https://user-images.githubusercontent.com/10957486/77985416-0ead0300-7332-11ea-9a26-7631f58e4174.png)

**Comment by mjarraya** [comment]
[#1785](https://github.com/facebook/react-native-website/pull/1785) fixes this

**Comment by Simek** [comment]
My PR was merged, can you confirm that your issue has been fixed?

**Comment by jairaja** [comment]
Thanks mjarraya and Simek...issue is fixed.
