### ISSUE TITLE
How Contribute with Translations for React Native Docs ?

### ISSUE THREAD

**Issue by michaelasumcinei** [facebook/react-native-website#181]
Hello

I would like to translate the React Native Docs in Italian.

I can submit the contributions on Github as I am one of the contributors of Utopian.io

Is there any guide or repository for it?

I look forward to understand how to get started.

Any help appreciated

Thank you

Best Regards
Michael Asumcinei

**Comment by gedeagas** [comment]
Hello @digitalplayer-steemit. 
Currently, there is no official translation method for react-native docs ( there is one but currently not active https://crowdin.com/project/react-native-official ). 

But if you interested in translating the react docs ( not react-native ) to Italian you can do it in here 
https://crowdin.com/project/react

for now, I didn't know the exact date when the crowdin translation for react-native will open. 

cc @ericnakagawa

**Comment by digitalplayer-steemit** [comment]
I started to work on Open Source translations with the Utopian.io project and I translated on crowdin for react. I would like to continue to translate reactjs documentation but Utopian.io is now supporting only contributions done on Github not anymore crowdin and as I can see React team instead doesn't accept Github collaboration :-) if the react translation team could consider my Github contributions I will be happy to continue the job I started

**Comment by hramos** [comment]
We're not yet ready to start accepting translations at this time. We already have the infrastructure in place through our static site generator, Docusaurus, which uses CrowdIn as the source. We might overhaul the doc structure at some point this year, and it would be a shame to throw away all the work people put in on translations when that happens.

**Comment by matheuschagas** [comment]
Any changes? I'll be glade to collaborate translating the docs to Portuguese

**Comment by sboh1214** [comment]
Any changes? I can collaborate with Korean

**Comment by developerantoniosousa** [comment]
Any changes? I can collaborate with Portuguese

**Comment by Simek** [comment]
The i18n support in Docusaurus V2 is in development right now - https://github.com/facebook/docusaurus/pull/3325 - after it will be released and tested for a bit we will work on the implementation of this feature for the RN website.
