### ISSUE TITLE
Wrong link for Watchman Installation guide

### ISSUE THREAD

**Issue by mateNemeth** [facebook/react-native-website#1816]
The link for the Watchman installation on the environment setup page redirects to https://facebook.github.io/watchman/docs/install.html#buildinstall, which doesn't exist (anymore ?).

**Comment by Simek** [comment]
Refs: #1811

**Comment by Simek** [comment]
You could have waited until one of PRs is merged before closing this issue, but thank you for reporting this anyway 👍

**Comment by mateNemeth** [comment]
@Simek sorry, should i reopen it?

**Comment by Simek** [comment]
Probably we will need to wait few days until one of the PRs will be merged by a maintainer, but it might happen earlier. Having this issue open could prevent someone from creating similar one, but it's not that crucial, there are duplicates anyway. I leave the decision to yourself.

**Comment by mateNemeth** [comment]
Ok. I'll reopen it then until a PR is merged.

**Comment by Simek** [comment]
#1809 was merged 😉
