### ISSUE TITLE
Links in props listings don't look like links

### ISSUE THREAD

**Issue by rachelnabors** [facebook/react-native-website#1831]
See also the prop definitions for Color: ![image](https://user-images.githubusercontent.com/249164/78808828-d7b29f00-797a-11ea-98fd-f94459453a3a.jpeg) originally posted by @TheSavior in https://github.com/facebook/react-native-website/pull/1813#issuecomment-611058025

**Comment by Simek** [comment]
I'm on it.

**Comment by TheSavior** [comment]
Woah, I tried tapping on those a bunch of times on mobile and was positive they weren't links. They probably need much larger hitboxes. 

![Screen Shot 2020-04-08 at 11 31 49 AM](https://user-images.githubusercontent.com/249164/78820406-94f9c280-798c-11ea-93ba-a97965598fdb.png)

**Comment by Simek** [comment]
Not every `color` type keyword is linked unfortunately, my PR should make obvious which currently are.

I can add padding to the links inside table, but other links on the website has no padding. I have no issues on desktop. Do you have problem with other, in text, links on mobile? 

Maybe we should adjust all in article links padding but only on mobile?

**Comment by TheSavior** [comment]
I haven't used the docs much to know if i have problem with other text links on mobile. I probably gave up quicker because of the styling. So it is possible that your styling fixes will solve this.

**Comment by rachelnabors** [comment]
Styling issue fixed in #1832
