### ISSUE TITLE
Running on Device: LaunchScreen Storyboard

### ISSUE THREAD

**Issue by hramos** [facebook/react-native-website#1837]
See https://github.com/facebook/react-native/pull/28239#issuecomment-602255876 - we might need to update the docs to account for the new Storyboard based guidance.

**Comment by gedeagas** [comment]
Hi @Simek, is anyone working on this already? I would love to help if not.

**Comment by Simek** [comment]
Hi @gedeagas, awsome, feel free to work on this issue. 

At the first glance it looks like that the docs are not mentioning `XIB`s anywhere (so the `StoryBoard` replacement is not needed) but an extensive check is needed. Also if there is no information about Launch Screen already I would nice few sentences about it.

**Comment by jeswinsimon** [comment]
@Simek There is a section under [pro tips](https://reactnative.dev/docs/running-on-device#pro-tips) on how to keep the Launch Screen visible during loading if the app bundle size is large. The code snippet in this section is no longer relevant as we are not using an `XIB` anymore.

**Comment by gedeagas** [comment]
As @jeswinsimon explained, we are no longer using XIB for our SplashScreen. so `loadNibNamed:@"LaunchScreen"` will not work because the XIB file is no longer exist. I am planing to update the code to use `UIStoryboard`

**Comment by gedeagas** [comment]
haven't had the time to do it for the past few days. I am free today and will send a pr asap. 🙏

**Comment by gedeagas** [comment]
@Simek can you close this, somebody already updated this page. https://github.com/facebook/react-native-website/pull/2031. quite busy for the past few months and can't land the pr :(
