### ISSUE TITLE
No way to monitor memory usage/performance on Android

### ISSUE THREAD

**Issue by dancherb** [facebook/react-native-website#1843]
Seems to be zero about this in the documentation or StackOverflow. How can we monitor memory usage and performance for a React Native project on Android to investigate memory leaks, etc.?

Ideally we'd use the memory management profiler from Android Studio, but this doesn't seem available for a React Native project - the buttons are greyed out, and trying to run "Profile..." from the actions menu opens a template window that I've not had to deal with when working from the CLI (and also isn't documented).

![](https://i.stack.imgur.com/zcFfX.png)

**Comment by Simek** [comment]
I'm sorry but this is the React Native **website** repository. 

To discuss problems, find support or request a feature in React Native please use a guide on the [website](https://reactnative.dev/help) or visit [main repository](https://github.com/facebook/react-native).

If you have a feature request or an issue with Android Studio please use JetBrain [bug tracker](https://youtrack.jetbrains.com/).
