### ISSUE TITLE
Move DynamicColorIOS to its own page

### ISSUE THREAD

**Issue by rachelnabors** [facebook/react-native-website#1850]
When we documentated the `PlatformColor` API, [it came to light that `DynamicColorIOS` needs its own page](https://github.com/facebook/react-native-website/pull/1813). For now it lives on the [Colors page](https://reactnative.dev/docs/colors). Move it into the **API** section of the site, reference it from the colors page and `PlatformColor`, and add an example

**Comment by gedeagas** [comment]
Hi is anyone taking this already? if not I am willing to help 😀

**Comment by mitulsavani** [comment]
Hi @rachelnabors,

I was able to read a full [conversation](https://github.com/facebook/react-native-website/pull/1813) regarding this issue. I am curious if @kikisaints is already working on it? If not, then I wanna give it a shot.

**Comment by Simek** [comment]
Hi @mitulsavani, unfortunately the changes requested in this issue has been proposed. 

As issue actions log shows, there is a PR by Rachel linked to this issue which extracts `DynamicColorIOS` API and introduces few other changes.

If you are interested in contributing, there are few other `Good first issue`s and most wanted for now it's #1509.
