### ISSUE TITLE
Add documentation for Appearance.addChangeListener method

### ISSUE THREAD

**Issue by LuckyLuke19** [facebook/react-native-website#1881]
The `Appearance.addChangeListener` method is not mentioned in the documentation. However, it exists and it works as expected. Shouldn't it be included? I have been using the `react-native-appearance` package for some time and I intended to stop using it once the `Appearance` API got included in the `react-native` core. However, I didn't do so because I thought that the `addChangeListener` method (which I had been using) didn't exist. Incomplete documentation can be confusing to users.

**Comment by Simek** [comment]
Thank you for reporting this issue. Indeed there are two methods missing in the docs according to the [source code](https://github.com/facebook/react-native/blob/master/Libraries/Utilities/Appearance.js#L78):
* `addChangeListener`
* `removeChangeListener`
