### ISSUE TITLE
Using a ScrollView - Example doesn't work?

### ISSUE THREAD

**Issue by armandojsgomes** [facebook/react-native-website#1896]
## Description

Provided example code compiles but doesn't seem to work - throws errors. Only when changed to a function, I'm able to make it work.

## What is the problem?

When executing the sample code, I get an error:

> ReferenceError: Can't find variable: App
> 48 | export default App = () => (

## How can we address it?

I've changed from:

    export default App = () => (

To (with necessary adjustments):

    export default function App() {
        return (

and it worked.

## Why is it important?

Well, I had to spent a bit to understand what was the issue, given everything beforehand has been working out of the box. If this is not an issue _per se_, maybe it should be hinted somewhere.

## Who needs this?

New learners, like me :)

## When should this happen (use version numbers if needed)?

[Latest version available](https://github.com/facebook/react-native-website/commit/1a7c586883b73e1515a208e5adf780308b6b4332)

**Comment by Simek** [comment]
Hi @armandojsgomes, the sample code is correct, there is a problem with your IDE/editor or project configuration.  You can read more about arrow functions in the comment [here](https://github.com/facebook/react-native-website/pull/1875#discussion_r415170616). 

If you would like to avoid that replace inline export in your code with:
```
const App = () => { ... };
export default App;
```

**Comment by armandojsgomes** [comment]
Oh, thanks for the info and sorry about that! :)

**Comment by Simek** [comment]
You can also change the code to:
```
export default (App = () => { ... }); 
```
It looks like ESLint false positive report, at least in the [Snack](https://snack.expo.io/);
