### ISSUE TITLE
Verify and update Animated Values pages code reference

### ISSUE THREAD

**Issue by Simek** [facebook/react-native-website#1897]
## Description

In the #1807 PR Animated values pages ([Animated.Value](https://reactnative.dev/docs/next/animatedvalue), [Animated.ValueXY](https://reactnative.dev/docs/next/animatedvaluexy)) has been added back to the main sidebar. The included example has been updated, but the reference may be outdated.

## What is the problem?

The state of the code reference on the animated pages is unknown.

## How can we address it?

The code reference can be verified by analyzing and comparing the code located in the `react-native` repository to the actual content:
* [Animated.Value](https://github.com/facebook/react-native/blob/master/Libraries/Animated/src/nodes/AnimatedValue.js)
*  [Animated.ValueXY](https://github.com/facebook/react-native/blob/master/Libraries/Animated/src/nodes/AnimatedValueXY.js)

## Why is it important?

Because having up to date docs is important! 😃

**Comment by psjishnu** [comment]
@Simek  Can you state the problem a little bit more clearly . The state of which code reference is unknown ? .

**Comment by Simek** [comment]
> Animated values pages ([Animated.Value](https://reactnative.dev/docs/next/animatedvalue), [Animated.ValueXY](https://reactnative.dev/docs/next/animatedvaluexy))

Pages are listed in the description above and the source code links shows exactly which file need to be reviewed:
* `AnimatedValue.js` should be compared with the reference on the `Animated.Value` page
* `AnimatedValueXY.js` should be compared with the reference on the `Animated.ValueXY` page

**Comment by psjishnu** [comment]
@Simek  Can you please mention a sample page in https://reactnative.dev/docs where reference is already properly done .

**Comment by Simek** [comment]
> When I compared the `AnimatedValue.js `with`Animated.Value` page , the data in the `Animated.Value` page is similar to the data provided as comment in ` AnimatedValue.js`
That was the task. Please do the same with `XY`. If there is no difference (documaentation is up to date with the current code) this issue should be closed.

**Comment by psjishnu** [comment]
@Simek The only problem i saw is description column was empty for setValue(value); and setOffset(offset); in  animatedValue page . I just added a description and PR .
