### ISSUE TITLE
🛠️ Standardize 'export's and functions definition in the examples code

### ISSUE THREAD

**Issue by Simek** [facebook/react-native-website#1921]
## Description

There are many ways to export Node, Component or any other Object. But, unfortunately, some syntaxes cause compatibility/formatting issues with ESLint, Prettier, and some IDEs/Editors. We've noticed some confusion in a few issues over the last weeks because of this and feel that standardizing our example code will help to avoid these issues. 

As such, we need to standardize two things: `export`s and converting `function`s to arrow functions.

### What it looks like now

Inline exports, for example:
```
export default NAME = () => { ... }
```
and 
```
export default function NAME() { ... }
```

### How to fix

Separate the function declaration and exports above like so (and use arrow functions!):
```
const NAME = () => { ... }

export default NAME;
```

## Step 2: switch to arrow functions

We have many instances of both `function()` and arrow function syntax throughout the code. We've decided to align with the syntax used in the React Native [template](https://github.com/facebook/react-native/blob/master/template/App.js)) and switch to all arrows except in cases where `function()` is a feature, not a bug.

### What it looks like now

```
function NAME() { ... }
```

### How to fix

Replace the `function` keyword with [arrow function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) shorthand:
```
const NAME = (...) => { ... }
```

## Why is it important?

- This refactor will fix some incompatibilities and recurring contribution issues, 
- Standardization makes it easier to contribute.

## Contributing tips

- update only the __`current`__ docs
- remember to test your changes at least on the one of the mobile platforms 
  (there are some minor differences between Web and Android/iOS implementations)
- remember to run Prettier on the changed files

## Work batches
The work batches are defined based on the sidebar sections on the website. Since not every page contains code examples there is possibility that only few lines of code will be required to close some of those batches. 

Before you start working on the selected batch let everyone know in the comments below which one you want to handle to avoid duplicates and unnecessary work!

| Work Batch | Author | Status |
| --- | --- | --- |
| The Basics | @lcelso (#1927) | ✔ |
| Environment setup | @psjishnu (#1929) | ✔ |
| Workflow | @psjishnu (#1929) | ✔ |
| Design | @luism3861 (#1930) | ✔ |
| Interaction | @psjishnu (#1929) | ✔ |
| Inclusion | @psjishnu (#1929) | ✔ |
| Performance | @psjishnu (#1929) | ✔ |
| JavaScript Runtime | @psjishnu (#1929) | ✔ |
| Connectivity | @psjishnu (#1929) | ✔ |
| Native Components and Modules | @psjishnu (#1929) | ✔ |
| Guides (Android) | @psjishnu (#1929) | ✔ |
| Guides (iOS) | @psjishnu (#1929) | ✔ |
| Core Components | @luism3861 (#1922) | ✔ |
| Android & iOS Components | @psjishnu (#1929) | ✔ |
| Props | @luism3861 (#1925) | ✔ |
| APIs | @luism3861 (#1926) | ✔ |
| Hooks | @psjishnu (#1929) | ✔ |
| Android & iOS APIs | @luism3861 (#1931) | ✔ |

### Legend
* 👋 TODO
* ⏳ WIP
* ✔ DONE

**Comment by luism3861** [comment]
@Simek can i take Core Components?

**Comment by Simek** [comment]
@luism3861 Go ahead, this section is yours! 😃

**Comment by luism3861** [comment]
> @luism3861 Go ahead, this section is yours! 😃 

Can I take props and apis ? @Simek

**Comment by Simek** [comment]
@luism3861 Of course!

**Comment by luism3861** [comment]
> @luism3861 Of course!

@Simek  i would like to take, Design , The Basics, Android & IOS Apis

**Comment by lcelso** [comment]
@Simek I just went up the basics

**Comment by Simek** [comment]
Thank you for the PRs so far, good work! I have updated the matrix in the main post.

@luism3861 Hope you are fine with accepting @lcelso "Basics" section PR. I have assigned you to the rest of wanted sections.

**Comment by Simek** [comment]
It looks like all the batches are assigned right now thanks to @psjishnu. I was not expecting such quick response from the community and blazing fast issue resolution, you are awesome guys!

**Comment by psjishnu** [comment]
@Simek  but I just closed pr because u told that  that was not the correct way .

**Comment by Simek** [comment]
@psjishnu I just asked you if you can discard the changes which are a part of another PRs or are part of  taken work batches by someone else. You have decided to close the PR and open another one instead (https://github.com/facebook/react-native-website/pull/1928#issuecomment-627959060).

I'm bit confused right now to be honest. Are you going to work on those batches or should I unassign you from them?

**Comment by psjishnu** [comment]
I will  discard the changes which are a part of another PRs

**Comment by luism3861** [comment]
> Thank you for the PRs so far, good work! I have updated the matrix in the main post.
> 
> @luism3861 Hope you are fine with accepting @lcelso "Basics" section PR. I have assigned you to the rest of wanted sections.

no worries thank you @Simek

**Comment by Simek** [comment]
@lcelso Thank you for your offer to help but those sections are done already and no work left to take. Please check out my comment above (https://github.com/facebook/react-native-website/issues/1921#issuecomment-627961570) and the matrix in the initial post. 

It looks like ~95% of this issue is resolved already, that was quick wasn't it?

**Comment by lcelso** [comment]
Okay, I will finish my part and soon I will send the PR

**Comment by rachelnabors** [comment]
Great job everyone! Thank you for working to make the docs ever better!

![shera_entrapta](https://user-images.githubusercontent.com/236306/82097274-7a88d680-96fa-11ea-8aa9-a52b4a191b78.gif)
