### ISSUE TITLE
Link broken: Page Navigating Between Screens

### ISSUE THREAD

**Issue by lai32290** [facebook/react-native-website#194]
At [Navigating Between Screens page](https://facebook.github.io/react-native/docs/navigation.html), links to [React Navigation Getting Started Guide](https://reactnavigation.org/docs/intro/) and [Intro to Navigators](https://reactnavigation.org/docs/navigators/) are getting 404.

![Navigating Between Screens page screenshot](https://user-images.githubusercontent.com/903193/36062297-b823566c-0e50-11e8-8d36-c7ad5755e4d3.png)

**Comment by lai32290** [comment]
Probably

**React Navigation Getting Started Guide** link is changed to https://reactnavigation.org/docs/getting-started.html

**Intro to Navigators** maybe is changed to https://reactnavigation.org/docs/hello-react-navigation.html

**Comment by yassinecc** [comment]
A fix in #179 has been merged but the website still has the broken links

**Comment by yashovardhanagrawal** [comment]
It is working fine, I think this issue is no longer needed
