### ISSUE TITLE
I have seen 300 + security bugs in repo 

### ISSUE THREAD

**Issue by madilraza** [facebook/react-native-website#1961]
## Description

There are more the three hundred security issues in the repo

**Comment by Simek** [comment]
@madilraza Can you explain your findings in more descriptive way?

**Comment by Simek** [comment]
Closing due to no response from the author. 

@madilraza Feel free to reopen this issues when you will be able to provide some more details and the context of those issues.

**Comment by madilraza** [comment]
There are around 300 security and Performance bugs in the website
