### ISSUE TITLE
Navigation links are not clickable on Desktop

### ISSUE THREAD

**Issue by rahsheen** [facebook/react-native-website#1976]
## Description

Navigation header links are no longer clickable since https://github.com/facebook/react-native-website/pull/1974

## Documentation version

n/a

**Comment by rahsheen** [comment]
I did attempt to put a PR together, but I was not able to reproduce the initial issue of not being able to click the nav links on mobile.

**Comment by Simek** [comment]
Hi @rahsheen, thank you for reporting that issue! I have prepared a PR which should fix that issue. I'm waiting for the review from the team before the merge.
