### ISSUE TITLE
The grayscale blanket makes the website difficult to use

### ISSUE THREAD

**Issue by ilyakam** [facebook/react-native-website#1983]
## Description

#1980 adds a `filter: grayscale()` blanket across the entire website following the BLM banner.

https://github.com/facebook/react-native-website/blob/2bfcd0ca120bcb24abcde1288f3c6cf7ef53153b/website/static/css/header.css#L201-L206

As a result, the code examples are difficult to follow. What used to be a colorful syntax highlighter is now a monochromatic text of varying contrast that is heavy on the eyes. Moreover, features like the [Color keywords](https://reactnative.dev/docs/colors#color-keywords) are all but useless with this new change.

### Screenshots

| Expected | Actual |
| :--- | :--- |
| ![rn-text-containers-expected](https://user-images.githubusercontent.com/183227/83959069-2fac3b80-a82e-11ea-92dd-ef488083154b.png) | ![rn-text-containers-actual](https://user-images.githubusercontent.com/183227/83959071-320e9580-a82e-11ea-8e1a-dd6ddfdbc87c.png) |
| ![rn-text-color-keywords-expected](https://user-images.githubusercontent.com/183227/83959146-844fb680-a82e-11ea-8526-31d0edb891df.png) | ![rn-text-color-keywords-actual](https://user-images.githubusercontent.com/183227/83959145-83b72000-a82e-11ea-84db-3d7f34a1c9d0.png) |

## Documentation version

All documentation versions are affected, from [v0.5](https://reactnative.dev/docs/0.5/getting-started) to the [master (version "next")](https://reactnative.dev/docs/next/getting-started).

## Workaround

As a Firefox user, what worked for me is to [override the user stylesheet](https://davidwalsh.name/firefox-user-stylesheet) by creating a `userContent.css` with the following rule:

```css
* {
  filter: none !important;
}
```

**Comment by Simek** [comment]
Refs: reactjs/reactjs.org/pull/3024

The similar, valid points why the grayscale filter may not be the most UX friendly addition has been brought up in the reactjs.org repository also. Since the grayscale filter has been reverted there I'm going to to the same for React Native website.
