### ISSUE TITLE
Update reference to "preferences dialog" as it no longer exists

### ISSUE THREAD

**Issue by YashKumarVerma** [facebook/react-native-website#1985]
## Description
![image](https://user-images.githubusercontent.com/14032427/84074168-c2480880-a9ef-11ea-812a-8f223ff743d1.png)
The preferences dialog/menu entry existed in an older version of the android studio. In the newer versions, it's accessible from `file->settings`. 

Since this is part of the onboarding guide, it needs to be updated with the latest references. 

## Documentation version
0.62

reference: https://stackoverflow.com/questions/30588696/window-preferences-missing-in-android-studio-after-update

As stated in the above thread, it is true that the SDK location has to be accessed from `file->settings->appearance and behavior->system settings->android SDK`
![image](https://user-images.githubusercontent.com/14032427/84074642-7d70a180-a9f0-11ea-95d3-bc43d8def761.png)

---

Sending a pr for it

**Comment by Simek** [comment]
Hi @YashKumarVerma, the note do not specify the path how to open the Preferences/Settings dialog but where inside this dialog user can find the SDK information. I have tested the latest Canary build (4.2 Canary 5) on macOS and Windows and the paths listed for both OSes looks actual for me.

**Comment by Simek** [comment]
Closing because there was no response form the author in last few months.
