### ISSUE TITLE
PLEASE!!! Make that BLM banner collapsable when we are scrolling the content!!! 

### ISSUE THREAD

**Issue by SeasonLeee** [facebook/react-native-website#2013]
## Description

First of all, I know you guys are so great and so saint and so wonderful and so thoughtful of the black community and as a human being I am touched by that move, BUT!!!! you can't just play thing to an extreme, right???? What about the rest of the world??? There are place we don't actually face this BLM issue and we are also the user of this framework, how can you be so selfish and so blindsided by your own insecurity then drag the whole community into this political hell??? 

There are people just want to learn the tech itself and not because we don't care for these crazy issues happening around the world but we have our own problems for god's sake!!! 

The world is really big and not just US this country!!! 

If you intend to put this tech for global user then please consider people come from another place and stop pushing your political agenda!!!! PLEASE!!!!!! 

PLEASEEEEEEE!!!!!!

## What is the problem?

![image](https://user-images.githubusercontent.com/13610283/85938064-2baa9f80-b93c-11ea-976c-99ef266d880d.png)

Only this tiny blue framed space is readable, are you kidding????? 

That banner combined with navigation bar is taking too much space if I am reading doc on my phone!!! This is nuts!!!! We colored people want to bring peace and justice to the world, not to cause any inconvenience but this react native website and that react website is taking things to another extreme!!! 

And we are not extremist!!! 

STOP MAKING US LOOK LIKE ONE!!!! 

THANK YOU!!!!!!

## How can we address it?

Make it auto collapse when we are scrolling down. 

## Why is it important?

It's the matter of readability and usability, or if you never read the doc yourself. 

## Who needs this?

People who just want to learn the technology itself and not because they want to but because it's the company's decision and just want to read the damn doc.

## When should this happen (use version numbers if needed)?

When someone is irrational and so selfish to not care for others' need.

**Comment by ArunEdathadan** [comment]
Support is turning into irritation, fix it

**Comment by rachelnabors** [comment]
Ameliorated in #2018
