### ISSUE TITLE
Bug in React Native code in example comparing state in React vs React Native

### ISSUE THREAD

**Issue by kairstenfay** [facebook/react-native-website#2014]
## Description 
In the React Native tutorial's image of example code comparing state in React vs React Native immediately following [this header](https://reactnative.dev/docs/tutorial#there-are-differences-between-react-and-react-native-to-handle-the-state), the React Native code is missing a `.container` class in the creation of the `StyleSheet` object.  

Here's the image copied from https://reactnative.dev/docs/tutorial
![image](https://user-images.githubusercontent.com/11384464/85966794-a9d76800-b975-11ea-8a6e-949f7e16b884.png)

Here are my edits highlighting the issue. 
![image](https://user-images.githubusercontent.com/11384464/85966960-17839400-b976-11ea-8885-836f2e03c227.png)

Apologies if this is not a real bug. I am new to React Native and only noticed the missing `.container` class because the immediately following code example includes it in the `StyleSheet.create()` function along with `.button`.

**Comment by charpeni** [comment]
Oops! Nice catch, you're right it's confusing and wrong as `StyleSheet` should have a `container` object inside.

**Comment by charpeni** [comment]
Removing `👋 Good first issue` label as this included in an image.

Should we move that to two side-by-side blocks? 🤔
