### ISSUE TITLE
Content of the sidebar cannot be fully viewed

### ISSUE THREAD

**Issue by eduardopelitti** [facebook/react-native-website#2054]
## Description

The content of the navigation sidebar that is displayed on all pages cannot be fully viewed, as it's being pushed down by the Announcement Banner.

<img width="1680" alt="Screen Shot 2020-07-15 at 17 15 55" src="https://user-images.githubusercontent.com/3876078/87592469-4c0a8600-c6c0-11ea-846b-c5fb72bb60d6.png">

Notice in the image above that the section Guides (iOS) is not visible. Removing the announcement banner specific code (top padding on the sidebar and the HTML elements) fixes the issue.

Perhaps the contents of the sidebar should be fully scrollable or the presence of the announcement banner should apply extra styling to the sidebar

Edit: This issue is reported in Chrome Version 83.0.4103.116 (Official Build) (64-bit) from a Macbook Pro with a fixed Dock. In Safari and Firefox I can scroll the content.

## Documentation version

0.63.0

**Comment by realJema** [comment]
![image](https://user-images.githubusercontent.com/16238730/87945304-754c5d00-ca98-11ea-92df-837f736585c4.png)
Mine has a scrollbar, check again and ensure if this is not a browser-specific issue

**Comment by eduardopelitti** [comment]
> Mine has a scrollbar, check again and ensure if this is not a browser-specific issue
> ![image](https://user-images.githubusercontent.com/16238730/87945304-754c5d00-ca98-11ea-92df-837f736585c4.png)

Added some browser specific information to the original report. It is indeed a browser specific issue with Chrome, at least for my setup detailed above.

**Comment by Simek** [comment]
Hi @eduardopelitti, I have tested the website on Chrome and Safari on macOS and I cannot reproduce your problem (I can scroll both sidebars - left and right). Is this issue still present for you with the live version?

**Comment by eduardopelitti** [comment]
> Hi @eduardopelitti, I have tested the website on Chrome and Safari on macOS and I cannot reproduce your problem (I can scroll both sidebars - left and right). Is this issue still present for you with the live version?

Hi! Yes, I still see it, but with further testing I see it's much more narrowly scoped. 

1. I only get the issue in /docs/ pages, on the other sections (Componentes, API) I can scroll the sidebar.
2. I can do _some_ scrolling, but not all that I need. I've attached a video with the issue I see.

![noscrolling](https://user-images.githubusercontent.com/3876078/88490147-d4661200-cf6f-11ea-8a82-64abaf1f262b.gif)
