### ISSUE TITLE
Clarify documentation about when onLayout is called

### ISSUE THREAD

**Issue by evelant** [facebook/react-native-website#2056]
## Description

https://reactnative.dev/docs/view#onlayout

Trying to animate elements in my app to the screen locations of other elements. I get the position of those elements in their onLayout callbacks and cache the results. In some (unknown, undocumented) situations onLayout is not called when an element changes position.

The current documentation states

> Invoked on mount and layout changes with:
>
> {nativeEvent: { layout: {x, y, width, height}}}
> 
> This event is fired immediately once the layout has been calculated, but the new layout may not yet be reflected on the screen at the time the event is received, especially if a layout animation is in progress.

This does not specify that in some situations the layout information will be incorrect or transitional. It also does not specify in which situations `onLayout` will *not* be called. In my case it appears that `onLayout` is only called on mount but not when a parent changing size causes an element to change x/y position but remain the same size.

It would be helpful if the documentation for onLayout were expanded to detail exactly in which situations onLayout will be called and in which situations the position/size information may be inaccurate. What exactly constitutes `layout changes` to fire the event?

edit: here are some related issues detailing the undocumented quirks/bugs with onLayout.
https://github.com/facebook/react-native/issues/28775 (animations of transforms don't trigger onLayout)
https://github.com/facebook/react-native/issues/3282 (measure returns undefined on android unless onLayout or collapsable are specified)
https://github.com/facebook/react-native/issues/24219 (reanimated, standard with expo, changes onLayout behavior)
https://github.com/facebook/react-native/issues/23443 (device rotation doesn't trigger onLayout in some situations)
https://github.com/facebook/react-native/issues/19872 (onLayout removed elevation on Android)

## Documentation version

v0.63

**Comment by olosegres** [comment]
@stale Issue does not fixed

**Comment by dennisbouwpas** [comment]
@Stale Issue does not fixed!

**Comment by chrisbobbe** [comment]
I also think an answer to the following would be great to document: are `x` and `y` relative to the top-left of the whole screen, or to the parent? I [believe](https://github.com/facebook/yoga/issues/787) they're relative to the parent, but I don't want to start a false rumor. 🙂

**Comment by lon9man** [comment]
+1

**Comment by audrew** [comment]
I am trying to find a solution too.  Hopefully, that can help https://reactnative.dev/docs/direct-manipulation

**Comment by J6ey** [comment]
What I'm understanding is that `onLayout` is only called when that View UI is updated, so if you're changing its position or size in the background but is not reflecting the UI, then onLayout will not get triggered.

**Comment by evelant** [comment]
Issues don't become invalid just because nobody has bothered to look at them.

**Comment by evelant** [comment]
Still needs attention

**Comment by topheroes** [comment]
Hello, @evelant, did you solve the problem? In my case onLayout gets fired on mount only. Not on translation, rotation, etc.

**Comment by evelant** [comment]
No, the documentation is still unclear
