### ISSUE TITLE
Nested blocks are not correctly rendered

### ISSUE THREAD

**Issue by sunnylqm** [facebook/react-native-website#2058]
https://reactnative.dev/docs/environment-setup  
See `React Native CLI Quickstart`, all `step 2`s are missing.

![QQ20200717-161509](https://user-images.githubusercontent.com/615282/87765159-0e396900-c84a-11ea-944b-1e77ac2cdeed.png)

**Comment by Simek** [comment]
Hi @sunnylqm, thank you so much for the report! The PR with which fixes the rendering problem has been merged, so after the deployment the sections should display correctly. 

Feel free to reopen this issue if you are still experiencing the problems with the Environment Setup guide.
