### ISSUE TITLE
Infinite Red link 404s

### ISSUE THREAD

**Issue by filiptronicek** [facebook/react-native-website#2073]
## Description
The link to Infinite Red is not functional at the moment. It seems it has been moved from `https://infinite.red/react-native` to `https://infinite.red/technologies/react-native`

## Documentation version
0.63

**Comment by filiptronicek** [comment]
The link seems to be here https://github.com/facebook/react-native-website/blob/611356be6fde0eebba5b32668d5cb8cd6d3667a9/website/pages/en/showcase.js#L142

**Comment by Simek** [comment]
Hi @filiptronicek, thank you for reporting this broken link and researching where it comes from! 👍
