### ISSUE TITLE
App crashes on the TouchableOpacity Snack Expo example

### ISSUE THREAD

**Issue by smakosh** [facebook/react-native-website#2091]
## Description

![Screen Shot 2020-07-22 at 20 25 02](https://user-images.githubusercontent.com/20082141/88220045-5e556880-cc5a-11ea-95df-ab31e2e82fb3.png)

**Comment by Simek** [comment]
Hi @smakosh, can you provide the link to the page with broken example? I have tested `TouchableOpacity` examples in `0.63` version and in the `next` docs and I have not experience any problems or issues. Also including your OS and browser information could be helpful to reproduce the problem.

**Comment by smakosh** [comment]
Seems to be working now
