### ISSUE TITLE
Move ios 'Building your app for production' to 'Publishing to Apple App Store'

### ISSUE THREAD

**Issue by sradc** [facebook/react-native-website#2127]
## Description

Currently, there is a section in the docs on [Publishing to Google Play Store](https://reactnative.dev/docs/signed-apk-android).

However, there is no section in the docs on Publishing to Apple App Store.

The problem is that vital information about building for the Apple App store is buried here: https://reactnative.dev/docs/running-on-device, in the section 'Building your app for production'. For example, this section mentions that you need to [enable app transport security](https://reactnative.dev/docs/running-on-device#1-enable-app-transport-security) before submitting to the App Store. 

I think this information should be moved to a new section called 'Publishing to Apple App Store', which would make it much easier to find.

Happy to PR this, if people agree.

## Documentation version

0.63

**Comment by Simek** [comment]
@sradc Thank you for bringing this up, I think that extracting `Building your app for production` section to the separate file under `Guides (iOS)` is a good idea! Feel free to work on this PR!

Ideally iOS `Running on Device` should also contain the small paragraph with the link to the new page like the Android guide does:
<img width="640" alt="Annotation 2020-08-13 150802" src="https://user-images.githubusercontent.com/719641/90138122-d05f3000-dd76-11ea-8b25-e075f6113f6e.png">
