### ISSUE TITLE
[UI/UX] Improve the announcement on smaller screens

### ISSUE THREAD

**Issue by Wuzado** [facebook/react-native-website#2134]
## Description

The announcement div, currently used for a Black Lives Matter donation link, is too large, and makes using the docs a huge hassle on smaller screens.

## What is the problem?

On a small laptop screen, the actual docs content ends up being about 1/2 of the entire screen, due to the large announcement, navbar and system elements accumulating. With many pictures in the guides and docs, this makes the user experience on smaller screens poor.

## How can we address it?

We can make two things, either:
1. Add a closing button to the announcement. I guess that wouldn't be too hard, just a small change in CSS visibility or otherwise disabling the div.
2. Make it smaller. Vue's banner on their main page is about 40 pixels high, where it's still quite visible, but doesn't interrupt user's workflow. Even main React page has a smaller banner (60px vs Native's 100px).

## Why is it important?

While the BLM movement is really important, and support should be given for it, it shouldn't interrupt average person's work. I'll still use the docs, but it's really uncomfortable for me to not see the whole picture at the same time.

## Who needs this?

Users with small screens.

**Comment by Wuzado** [comment]
Sent it prematurely, updated it now.

**Comment by Thiht** [comment]
Yes please! I'm using a MacBook Pro (pretty standard then), and even with this setup reading the documentation is painful. I just can't focus properly on the text as the banner is just too big. For reference, the announcement + navbar takes a little bit less than one quarter of the viewport height, that's way too much.

I applied the following modifications locally and it's way better, without compromising on the size of the actual announcement:

```diff
.headerWrapper.wrapper {
- padding-top: 100px;
+ padding-top: 30px;
}
.announcement {
- padding: 30px;
+ padding: 0;
}
```

**Comment by Wuzado** [comment]
Huh, wouldn't think that it's also an issue on something like Macbook Pro. My laptop (rather old) is only 1366x768, so I'm surprised that's also an issue on higher-end, more modern hardware with higher screen resolutions. This only makes it more important!
