### ISSUE TITLE
Wrong data type in TouchableHighlight android props

### ISSUE THREAD

**Issue by ayushjainrksh** [facebook/react-native-website#2141]
## Description

While working on the script for docs generation from code comment, I found that the [android props in TouchableHighlight](https://github.com/facebook/react-native-website/blob/master/docs/touchablehighlight.md#nextfocusdown) component contains wrong data types. The data type shown in the column is `bool` whereas it should be `number` according to the [FlowType in the TouchableHighlight.js](https://github.com/facebook/react-native/blob/1f15b8b6c222078336114dd5db1af6c29661c5fd/Libraries/Components/Touchable/TouchableHighlight.js#L25). Although the script I'm using to generate docs, generates the correct data type i.e., `number` but I would suggest updating the wrong data type manually until the script gets merged. I'd be happy to open a PR to fix the problem if assigned.

**EDIT**: The same issue exists with [TouchableOpacity](https://github.com/facebook/react-native-website/blob/master/docs/touchableopacity.md#nextfocusdown) and [TouchableNativeFeedback](https://github.com/facebook/react-native-website/blob/master/docs/touchablenativefeedback.md#nextfocusdown) components.

### The documentation on website
![Screenshot from 2020-08-14 01-05-35](https://user-images.githubusercontent.com/33171576/90178918-5193e280-ddca-11ea-94e9-4d0252a0c0aa.png)

### The FlowType in code
![Screenshot from 2020-08-14 01-06-58](https://user-images.githubusercontent.com/33171576/90179030-79834600-ddca-11ea-9bc0-2244dacedb54.png)

## Documentation version
0.63 and next

**Comment by gedeagas** [comment]
Nice find @ayushjainrksh. Please make a pr 🎉.

**Comment by ayushjainrksh** [comment]
@gedeagas This issue is common with 2 more components [TouchableOpacity](https://github.com/facebook/react-native-website/blob/master/docs/touchableopacity.md#nextfocusdown) and [TouchableNativeFeedback](https://github.com/facebook/react-native-website/blob/master/docs/touchablenativefeedback.md#nextfocusdown).

**Comment by Simek** [comment]
Android TV support in core in the future is unknown, but those are good changes for now. It is interesting that [View](https://reactnative.dev/docs/view#nextfocusdown) have those props updated. 

Regardless of that, thank you for working on those issues! 👍

**Comment by ayushjainrksh** [comment]
Yeah, it was added to the View component in [this PR](https://github.com/facebook/react-native-website/pull/931).
