### ISSUE TITLE
can't sign in to the app

### ISSUE THREAD

**Issue by chareen3** [facebook/react-native-website#2145]
using node j , expo

can't log in to the app get this error message  

Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`
* [native code]:null in __expoConsoleLog
- node_modules\react-native\Libraries\LogBox\LogBox.js:36:4 in console.warn
- node_modules\react-native\Libraries\YellowBox\YellowBox.js:162:6 in registerWarning
- node_modules\react-native\Libraries\YellowBox\YellowBox.js:88:8 in warnImpl
- node_modules\react-native\Libraries\YellowBox\YellowBox.js:66:4 in console.warn
- node_modules\expo\build\environment\muteWarnings.fx.js:18:4 in warn
- node_modules\react-native\Libraries\Animated\src\NativeAnimatedHelper.js:281:4 in shouldUseNativeDriver
- node_modules\react-native\Libraries\Animated\src\animations\TimingAnimation.js:73:49 in constructor
- node_modules\react-native\Libraries\Animated\src\AnimatedImplementation.js:210:26 in start
- node_modules\react-native\Libraries\Animated\src\AnimatedImplementation.js:217:13 in start
- node_modules\native-base\dist\src\basic\ToastContainer.js:1:5724 in closeToast
* [native code]:null in closeToast
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:135:14 in _callTimer
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:387:16 in callTimers
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:425:19 in __callFunction
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:112:6 in __guard$argument_0
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:373:10 in __guard
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:111:4 in callFunctionReturnFlushedQueue
* [native code]:null in callFunctionReturnFlushedQueue

**Comment by Simek** [comment]
Hi @chareen3, this is a React Native **website** repository. If you are having a problem w Expo you should report the issue in [their repository](https://github.com/expo/expo) and If it's a problem with React Native by itself you should post the bug to [React Native repository](https://github.com/facebook/react-native). You can also check the [help page](https://reactnative.dev/help) for the tips to the other ways of resolving issues.

Thank you for your understanding!
