### ISSUE TITLE
LogBox.install documentation

### ISSUE THREAD

**Issue by idkjs** [facebook/react-native-website#2147]
## Description

I am looking at the (LogBox docs)[https://reactnative.dev/docs/debugging#logbox] and can not find an explanation for the function.

## What is the problem?

I would like to understand what the function does.

## How can we address it?

Provide documentation for the function or why we don't need it.

## Why is it important?

I am trying to write a binding to LogBox.js for ReasonML

## Who needs this?

ReasonML/ReScript users.

## When should this happen (use version numbers if needed)?

As soon as possible.

Thank you.

**Comment by gedeagas** [comment]
Hi @idkjs, Great job for the binding. if you using the latest version of `react-native`  `LogBox` is the drop-in replacement `YellowBox`. it serves as a place to display a warning.

I think the docs documentation is sufficient considering that `ignoreLogs` and `ignoreAllLogs` is the only relevant exposed function that user can use. 

`LogBox.install();` is triggered automaticaly on `AppContainer`.

**Comment by idkjs** [comment]
That is what I figured. Did not want to leave it out if I was wrong. Thank you,sir.
