### ISSUE TITLE
Replace Flexbox page images with SnackPlayers and update existing demos to be more interactive

### ISSUE THREAD

**Issue by Simek** [facebook/react-native-website#2163]
## Description

Currently on the [**Flexbox**](https://reactnative.dev/docs/next/flexbox) page there is a lot of images and there are few basic examples in SnackPlayers. 

It will be nice to have fully interactive demos (where user can toggle through or select by click every valid property value and the example part of demo react to that) instead of the images and basic Snack examples. 

The examples design can be fully based on the current screenshots. Since it is not a Component or API page there is no need to write two version of examples (functional components should be enough).

## What is the problem?

Images are boring and they causing an issue in the `images-check.js` script - refs https://github.com/facebook/react-native-website/pull/2157#issuecomment-677705943.

## How can we address it?

Use SnackPlayers!

## Why is it important?

UX + external assets should not be used on the website anyway.

## Who needs this?

Community?

## When should this happen (use version numbers if needed)?

When someone from community wants to work on this 🙂

**Comment by rachelnabors** [comment]
This is a great idea! I sure hope someone will pick it up!

**Comment by Stringsaeed** [comment]
I can address this in a pr @rachelnabors

**Comment by espipj** [comment]
Hey @rachelnabors and @Simek some time ago I updated [Layout Props](https://reactnative.dev/docs/layout-props) which seems that might be kind of the idea that you're suggesting. I think is a good point to take as reference if @Stringsaeed wants to work on that :) I'm more than happy to help if needed :) PR for that was #1750

**Comment by Simek** [comment]
@espipj Thank you for referencing this example! It is exactly what I was thinking about. I was looking for it in Component and APIs, but I have forgot to check the Props 🤦‍♂️

Also approach with the picker component (like on[ Yoga Layout playground](https://yogalayout.com/docs/flex-direction/)) instead of buttons will be fine, feel free to choose @Stringsaeed.

**Comment by espipj** [comment]
Btw for some reason the _Props_ section doesn't show up properly while browsing through Firefox🦊 
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/12865914/90833226-e016df80-e347-11ea-8b42-27a7954eaec9.png">
Shows up okay, after collapsing _Core components_ 
![image](https://user-images.githubusercontent.com/12865914/90833379-2e2be300-e348-11ea-8831-a0bb10aed500.png)

Not sure how we can improve this, but I think UX can be improved 😄 
Works kind of OK in Chrome, but still not easy peasy to see/discover

**Comment by Simek** [comment]
Unfortunately the list of Core Component is so long so you need to scroll to the bottom of the page to see the end of left sidebar:
<img width="945" alt="Annotation 2020-08-21 005647" src="https://user-images.githubusercontent.com/719641/90833882-38021600-e349-11ea-8838-c277ce1a3dc4.png">

Currently we are working with Docusaurus team to migrate site to V2 (#2146), which will fix this issue (and hopefully many more):
https://reactnative-v2.netlify.app/docs/components-and-apis

**Comment by Stringsaeed** [comment]
@espipj I didn't check GitHub notifications 😓, so I did add from scratch but I will copy your code for this

**Comment by Stringsaeed** [comment]
@Simek I'm not following you about (Picker or Buttons) can you illustrate, but I already was trying to reference yoga playground in my implementation but I'm creating a snake for every section to make code and preview more accessible 
but if you suggest to convert it to a root playground for the whole page I can deliver that

**Comment by Stringsaeed** [comment]
that's what I'm creating right now
<img width="653" alt="Screen Shot 2020-08-21 at 1 06 51 AM" src="https://user-images.githubusercontent.com/37156636/90834464-a1ceef80-e34a-11ea-9273-70ebde8bf8fd.png">

**Comment by Simek** [comment]
> I already was trying to reference yoga playground in my implementation but I'm creating a snake for every section 

That is the goal of this issue, you have understood me correctly. In the post above I was referring to the functionality of example. And sorry for suggesting the Yoga solution I forget that [Picker ](https://reactnative.dev/docs/0.62/picker) component has been deprecated.

According to the screenshot, you on the good way, you should leave only the one "screen" and replace `'flex-start'` with buttons with property values (i.e. `flex-start`, `center`, `flex-end`, etc.) switching the example on the light blue background.

**Comment by Stringsaeed** [comment]
@Simek everything is okay but I have a really big problem with selecting colors for boxes 😂😂 (sorry backend background 😓😓, you can tell) 
<img width="322" alt="Screen Shot 2020-08-21 at 2 19 03 AM" src="https://user-images.githubusercontent.com/37156636/90838269-b7491700-e354-11ea-98a0-5f55c3a5bf1d.png">
is there any palette or good references for selecting colors
