### ISSUE TITLE
When can we expect the Black Lives Matter banner to be removed?

### ISSUE THREAD

**Issue by ravirajn22** [facebook/react-native-website#2174]
It's not like I want to fire up a thread between different groups of people. But I think BLM banner has served its ultimate purpose (I hope) of educating people about different racial and ethnic problems.

I feel it's time to remove it. why? Because we cannot have something perpetually considering this being a technical website (unfair) and as time passes it loses its purpose.

Also think for a second about people having different set of views on how racial inequalities has to be handled (I am one of them), instead of throwing BLM banner everywhere they might have some subtle ways of handling it. You never know which one will work, only time will tell. Need to respect difference of opinion.

If the core people are not ready to remove right now, at least start a discussion to fix end date.

Thanks.

**Comment by matheusmonte** [comment]
I think we can define this date to when black people stop to be killed and have equality opportunities on our society.

**Comment by cpojer** [comment]
Thanks, we'll consider your perspective but don't have an update to share right now.
