### ISSUE TITLE
explain more `source` prop of `Image`regarding multi-source

### ISSUE THREAD

**Issue by voxspox** [facebook/react-native-website#2176]
## Description

The [Image docs](https://reactnative.dev/docs/image.html#source) say for the `source` prop:
*This prop can also contain several remote URLs, specified together with their width and height and potentially with scale/other URI arguments. The native side will then choose the best uri to display based on the measured size of the image container.*

I tried to setup multiple local image resources like
```
<Image source={[require('..small_placeholder.png', require('...big_placeholder.png')]} .../>

Error while updating property 'src' of a view managed by: RTCImageView
null
java.lang.Double cannot be cast to ...ReadableNativeMap
```
Some more example how to setup multiple sources would be helpful.

Also please point out if `defaultSource` and `loadingIndicatorSource` are capable of this.

## Documentation version

0.63

**Comment by Simek** [comment]
Hi @voxspox, currently you need to use the object structure in the `source` array (multiple image sources using `require` is not supported):
* https://github.com/facebook/react-native/blob/master/Libraries/Image/Image.android.js#L51

But I agree that an example for multiple source image would be a nice addition.

**Comment by saideepesh000** [comment]
> 
> 
> Hi @voxspox, currently you need to use the object structure in the `source` array (multiple image sources using `require` is not supported):
> 
>     * https://github.com/facebook/react-native/blob/master/Libraries/Image/Image.android.js#L51
> 
> 
> But I agree that an example for multiple source image (with the note about the fact stated above) would be a nice addition.

Hi @Simek, do you mean Iike this

` <Image
        style={styles.tinyLogo}
        source={{uri: 'https://reactnative.dev/img/tiny_logo.png'}, {uri:'https://static.toiimg.com/photo/72975551.cms'},{uri :'https://static.toiimg.com/photo/72975551.cms'}}
      />`

**Comment by Simek** [comment]
You have forgot the array, according to the types shape the content like below should be valid:
```
<Image style={styles.tinyLogo} source={[
    {uri: 'https://reactnative.dev/img/tiny_logo.png'}, 
    {uri:'https://static.toiimg.com/photo/72975551.cms'},
    {uri :'https://static.toiimg.com/photo/72975551.cms'}
]} />
```

But I'm not sure is `width` and `height` are optional or required parameters, you need to test this too.
