### ISSUE TITLE
How to help

### ISSUE THREAD

**Issue by Wanderson77** [facebook/react-native-website#2178]
Hello guys, I would like to better understand this project and how it works and how I could help you in the development.

**Comment by matheusmonte** [comment]
Hi @Wanderson77 , There's a page about how to contribute : https://github.com/facebook/react-native-website#-contributing , basically you can see the open issues and if you feel confidence to solve some of that, use the steps to fork this project and made code changes to solve the issue, after this, you can open a merge request that will be checked by project's maintainers.
