### ISSUE TITLE
ScrollView "StickyHeaderComponent" prop need documentation

### ISSUE THREAD

**Issue by cheolhow** [facebook/react-native-website#2179]
## Description

> https://github.com/facebook/react-native/pull/25428

I found ``StickyHeaderComponent`` is available in the latest version RN's ``ScrollView``. But it's not documented.

## What is the problem?

There is some ambiguity in understanding just as described in PR.
For example, if I use ``StickyHeaderComponent`` with ``stickyHeaderIndices``, it's ambiguous how to handle it.
It similar to ``CellRenderComponent`` prop, but it doesn't keep the sticky behavior.

~~~javascript
    const Test = styled.View`
      background-color: red;
    `;

    _renderStickyHeaderComponent = ({ children, ...props }) => {
        return <Test {...props}>{children}</Test>
    }

    <Animated.FlatList
        ...props
        stickyHeaderIndices={[1]}
        StickyHeaderComponent={this._renderStickyHeaderComponent}
    />
~~~

## How can we address it?

Requires documentation and some use-case of ``StickyHeaderComponent`` prop

## Why is it important?

As explained in the PR link above, the ``CellRenderComponent`` prop can not custom ``ScrollViewStickyHeader ``, but ``StickyHeaderComponent`` property can custom. So it makes us deal with the various situation.

## Who needs this?

It's necessary for everyone. Especially for those who need to implement animation in ``ScrollView``, ``FlatList``.

**Comment by DZuz14** [comment]
@cheolhow You mention ScrollView here, but your code snippet is that of a FlatList?

**Comment by cheolhow** [comment]
@DZuz14 Flatlist is inherits VirtualizedList. And VirtualizedList is inherits ScrollView. Therefore, the issue of ScrollView can be described with FlatList.

**Comment by cheolhow** [comment]
When I check the ScrollView code, it seems that the ``StickyHeaderComponent`` property is completely replaced by a custom component.
 I handled the code of the ``ScrollViewStickyHeader`` component by customizing the code to maintain the default sticky behavior. However, this process seems to be a temporary measure.
 Discussion of improving this part will begin in the react-native repository.
 However, it seems that the document still needs notation and explanation for this property.

**Comment by Simek** [comment]
The code, description and types for missing `stickyHeaderIndices` and `StickyHeaderComponent` props can be found here:
* https://github.com/facebook/react-native/blob/master/Libraries/Components/ScrollView/ScrollView.js#L521

They should be added to the `ScrollView` props.
