### ISSUE TITLE
Graphic problems on official react native page

### ISSUE THREAD

**Issue by JoseMoreville** [facebook/react-native-website#2182]
Hello, i was taking a look on react native page since i want to use it for one of my project and i realized there are some problems with the front-end when you hover some brand icons.

I'm pretty sure it's the size, background color and border of the anchor tags <a></a>

I'm not 100% if this post belongs here but hopefully it does.

Image to show the bug
http://prntscr.com/u7rhgn

**Comment by Simek** [comment]
Hi @JoseMoreville, thank you for reporting the issue! And yes, this is the correct place. 🙂 

I have prepared a small PR which fixes the graphical problem you have reported. 

This issue will be automatically resolved on the PR merge.
