### ISSUE TITLE
Docs: Include "Inherits from <Component>" in the props section of the right-hand sidebar

### ISSUE THREAD

**Issue by DZuz14** [facebook/react-native-website#2190]
When visting a link to a components documentation (ie: https://reactnative.dev/docs/flatlist), it is not apparent that a component inherits from another unless you specifically click the "props" link in the right sidebar. Atleast on desktop view, I feel as though a lot of people may not click the "props" link at all, and just instead scan the list of props that are already visible in the menu.

I ran into the problem where I would just look at the props, and think, "oh, well it looks like this component doesn't support that prop". This is especially misleading when you consider ScrollView and Flatlist. For newcomers to React Native, there is a clear distinction that you should use one or the other, and one would assume that these components are completely distinct. However this is not the case, as FlatList inherits props from ScrollView.

 I wasted a lot of time searching on Google to see if `stickyHeaderIndices` prop was deprecated in FlatList, because I didn't see it listed by glancing at the list of props in the right sidebar. It wasn't until I randomly clicked `props` that I found out it inherited props from ScrollView.

It might be nice to add a note in the sidebar that it inherits props, with a link to that component perhaps. Not sure how it should look, but I'd be surprised if I was the only human on Earth that made this same trivial, but easy to make mistake.

P.S. I included a screenshot of where I think it should go. Section is outlined in red in using the glorious Microsoft Paint.

![react-props-list](https://user-images.githubusercontent.com/19492185/91827013-50f1ad80-ec0c-11ea-8c27-9c8d54ab0099.jpg)

**Comment by Simek** [comment]
Refs #2160, #2168

Hi @DZuz14, I think that the issues you are describing has been fixed lately. You can check the `next` version of docs to see the current solution: https://reactnative.dev/docs/next/flatlist

If you have any feedback about the implementation feel free to share it! 🙂 

If the changes in `next` docs are enough to fix the problem, please close this issue.
