### ISSUE TITLE
Add 'Switch' component examples with images

### ISSUE THREAD

**Issue by SrBrahma** [facebook/react-native-website#2192]
## Description

https://reactnative.dev/docs/switch.html doesn't provides example images of the coloring props.

## What is the problem?

I never used the switch coloring, and the docs doesn't make it very clear about the coloring of the Android and iOS (I don't use iOS and can't test on it right now, would be good if I knew how it would look like without trying)

## How can we address it?

Add images as examples

## Why is it important?

So users can know before having to try out

## Who needs this?

New devs, iOS and Android

**Comment by luism3861** [comment]
you should read this answers it's very easy to add custom colors in switch component!. 
https://stackoverflow.com/questions/39159659/change-color-of-switch-while-turning-off-react-native

**Comment by SrBrahma** [comment]
Indeed, but, this should be on the Native docs

**Comment by Simek** [comment]
Hi @SrBrahma, can you elaborate on what exactly in the current `Switch` example is missing? 

For both platforms the element in example changes track and thumb color on value change.

What an additional information the image would might show you?

#### Preview
<img width="1057" alt="Screenshot 2020-11-03 145910" src="https://user-images.githubusercontent.com/719641/97994461-9fc2eb80-1de5-11eb-9363-f5f199a22584.png">

**Comment by SrBrahma** [comment]
> Hi @SrBrahma, can you elaborate on what exactly in the current `Switch` example is missing?
> 
> For both platforms the element in example changes track and thumb color on value change.
> 
> What an additional information the image would might show you?
> #### Preview
> 
> <img alt="Screenshot 2020-11-03 145910" width="1057" src="https://user-images.githubusercontent.com/719641/97994461-9fc2eb80-1de5-11eb-9363-f5f199a22584.png">

I don't remember this playground when I created this Issue. Isn't an image as I requested in the Issuer, but can answer any remaining questions.

**Comment by Simek** [comment]
@SrBrahma Using blame you can check that the portion of example related to track properties (colors) has been updated 9 months ago as a part of #1594 PR: 
* https://github.com/facebook/react-native-website/blame/master/docs/switch.md#L10
