### ISSUE TITLE
https://reactnative.dev/docs/tabbarios-item.md#systemicon returns 404

### ISSUE THREAD

**Issue by GuillotJessica** [facebook/react-native-website#2201]
## Description

in https://reactnative.dev/docs/tabbarios-item if you click on systemIcon
 the link returns a 404

**Comment by Simek** [comment]
Hi @GuillotJessica, the `TabBarIOS` component has been removed from React Native few versions ago, in [`0.59` release](#2201) (https://github.com/facebook/react-native/commit/02697291ff41ddfac5b85d886e9cafa0261c8b98). 

To address the issue reported by you I have removed the duplicated TOC from `TabBarIOS` and `TabBarIOS.Item pages` (this was a relict of the previous website design) and I have added the note about the component removal in https://github.com/facebook/react-native-website/commit/4ec58c618f6b0423a62458116da5d31b7764f25a commit. 

Hope it will be enough to mark this issue as resolved, but feel free to reopen this issue if you have any additional problems with those pages.
