### ISSUE TITLE
Improve Native UI Components Documentation

### ISSUE THREAD

**Issue by MrGVSV** [facebook/react-native-website#2206]
## Description

There is very little detail in the documentation for Native UI Components. The documentation should be updated for both iOS and Android to reflect the basics of what can be done.

Links: [Android](https://reactnative.dev/docs/native-components-android) | [iOS](https://reactnative.dev/docs/native-components-ios)

## What is the problem?

The documentation is very sparse when it comes to things like:
### Creating Native UI Components in Swift
The documentation only explains how to create a UI Module in Objective-C. I can't speak for everyone, but I much prefer working in Swift. In order to understand how to create a bridge from React Native to Objective-C to Swift took many hours of reading through blog posts and forums. Unfortunately, the documentation on the React Native site only mentions Swift in the Native Modules section.

### Implementing Commands in Android
There is no documentation for calling a Native View's method on Android via `UIManager.dispatchViewManagerCommand`. Furthermore, `receiveCommand(@NonNull ITCameraView root, int commandId, @Nullable ReadableArray args)` is deprecated, and there is no documentation on the updated version. 

## How can we address it?

Add to documentation to better illustrate how to implement a Native UI Component on both iOS and Android. Additionally, organize documentation subsections (e.g. renaming "Handling multiple native views" to "Calling native methods", etc.)

## Why is it important?

Good documentation saves developers hours upon hours of time trying to solve an issue.

## Who needs this?

Anyone who wants to create custom Native UI Components for their own projects or for plugins that spare others having to do so themselves.

## When should this happen (use version numbers if needed)?
This is not a high priority issue, but _could_ be addressed as soon as the current version (0.63).

**Comment by Simek** [comment]
Refs #706, #1064, #1569, #1708 and more.

**Comment by betoharres** [comment]
I agree, and as a newbie that would like to start creating native modules to react-native on android:
Where's the imports? where should I search for such information? I'd like to contribute if at least I'd know where to look at :/
I don't get it why the person omitted such info; I'm scavenging popular repos just to copy/paste these things

**Comment by Simek** [comment]
@MrGVSV, @betoharres please check out the updated Native Modules and Native Components guides pushed lately within #2261 PR:
* https://reactnative.dev/docs/native-modules-intro
* https://reactnative.dev/docs/native-components-android
* https://reactnative.dev/docs/native-components-ios

I would like to know what you think about the pages after the update and if your previous issues has been addressed.

**Comment by betoharres** [comment]
@Simek Thanks a lot for updating the docs! It looks better now! I'll try to make a new ui module and give a better feedback here :)
