### ISSUE TITLE
Request for Dark Theme with theme toggle for developers

### ISSUE THREAD

**Issue by lopeselio** [facebook/react-native-website#2208]
This is just a small feature request. Would do a world good.

Introduction
I'd like to suggest implementing a Dark theme toggle switch, the same way Redux website https://redux.js.org/ and Redux Toolkit website https://redux-toolkit.js.org/ have that small toggle switch at the right upper corner of the top navbar.

Details
It really hurts your eyes when you read other Redux documents with dark theme and suddenly React Native website is bright white, especially while integrating redux.

Discussion points
Would do a lot good for the community

**Comment by Simek** [comment]
Hi @lopeselio, this feature and many more will be available after the Docusuaurs upgrade to V2, which is currently in progress. You can check out the #2146 issue and referenced fork for the details.

**Comment by lopeselio** [comment]
That's amazing. Really waiting ...
