### ISSUE TITLE
Is Website is down?

### ISSUE THREAD

**Issue by Mobashir1995** [facebook/react-native-website#2276]
I see that React Native website is down. When I want to visit the website then it returns the following

```
404
There isn't a GitHub Pages site here. 
```

**Comment by Simek** [comment]
Unfortunately yes, we are working on it.

**Comment by Simek** [comment]
The new website should be shortly up and running. I'm sorry for your inconvenience.

Meanwhile you can take a look at the upcoming changes listed in #2263.

**Comment by slorber** [comment]
fixed :)

**Comment by Simek** [comment]
@Mobashir1995 Can you confirm that website is working for you? 🙂
