### ISSUE TITLE
Wrong link for environment-setup

### ISSUE THREAD

**Issue by MohamadKh75** [facebook/react-native-website#2293]
## Description

There is a link in the [main page](https://reactnative.dev/docs/getting-started/) to `environment-setup` which redirects to [here](https://reactnative.dev/docs/getting-started/environment-setup)!

It's broken and should be [this address](https://reactnative.dev/docs/environment-setup/)

## Documentation version

It's 0.63

**Comment by Simek** [comment]
It looks like another issue related to #2291.

**Comment by MohamadKh75** [comment]
> It looks like another issue related to #2291.

There is an extra `getting-started/` in the URL so I guess it's more than a single slash :grin:

**Comment by Simek** [comment]
This is exactly the same problem 🙂 After the page loads navigate our of it and then navigate back, the link will be correct:
<img width="499" alt="Screenshot 2020-10-31 142721" src="https://user-images.githubusercontent.com/719641/97780489-4d838f80-1b85-11eb-83bf-c1259c92028f.png">

**Comment by Simek** [comment]
Closing in favor of #2291.
