### ISSUE TITLE
Blog RSS and Atom feeds not found

### ISSUE THREAD

**Issue by matt-oakes** [facebook/react-native-website#2295]
## Description

The RSS and Atom feed URLs are now returning 404 errors. I have just received this as a notification from [Feedrabbit](https://feedrabbit.com/), so it's likely broken in the past 24 hours as it was working before that.

The URLs used to be:

* http://reactnative.dev/blog/feed.xml
* http://reactnative.dev/blog/atom.xml

## Documentation version

0.63

**Comment by Simek** [comment]
Hi @matt-oakes, thank you for reporting that! 

I have a PR ready to be merged, but just want to leave note that RSS feed will be now available under URL - http://reactnative.dev/blog/rss.xml - and the Atom feed link would not change. 🙂
