### ISSUE TITLE
RN tutorial link redirects to 404 on load

### ISSUE THREAD

**Issue by kartikcho** [facebook/react-native-website#2298]
## Description

The RN tutorial doc is a [broken link](https://reactnative.dev/docs/tutorial.html) that redirects to `Page not found` on a successful load (which is unusual).

Is this supposed to updated/removed?

![image](https://user-images.githubusercontent.com/48270786/97794899-c63a2880-1c25-11eb-816a-c761acdd7b0b.png)

## Documentation version

0.6.3, but the page seems to be version independent.

**Comment by darshkpatel** [comment]
It's supposed to be https://reactnative.dev/docs/tutorial and not https://reactnative.dev/docs/tutorial.html I believe

**Comment by kartikcho** [comment]
Ah, I was redirected from the Expo CRNA docs to this page, I'll update their documentation to reflect the same. Thanks!
