### ISSUE TITLE
Update Layout doc with link to the new Yoga website

### ISSUE THREAD

**Issue by hramos** [facebook/react-native-website#230]
Yoga has a new website, which includes a neat interactive playground: https://yogalayout.com/

We can link to the new site and let people know it's a good place to try things out if you have any layout-related questions.

**Comment by iAmao** [comment]
@hramos can I have this?

**Comment by hramos** [comment]
Go for it! Anything with this tag is up for grabs.

**Comment by divyanshu-rawat** [comment]
@hramos  Can, I work on this?

**Comment by rickhanlonii** [comment]
Thanks @divyanshu-rawat!
