### ISSUE TITLE
The imagebackground component document props valid was not updated.

### ISSUE THREAD

**Issue by JustaCattt** [facebook/react-native-website#2303]
![image](https://user-images.githubusercontent.com/55068656/97961341-1532ba00-1dee-11eb-880d-a0ef0d91ce15.png)
![image](https://user-images.githubusercontent.com/55068656/97961492-63e05400-1dee-11eb-9878-aa42cf49771f.png)

So,this should be changed to backgroundColor.

**Comment by JustaCattt** [comment]
And, shouldn't it be a URL here.
![image](https://user-images.githubusercontent.com/55068656/97961884-0ac4f000-1def-11eb-9e24-f9f30d706420.png)

**Comment by Simek** [comment]
Hi @JustaCattt, thank you for reporting this issue! 👍 

It looks like a leftover after the migration. I have pushed the PR with fix and I'm waiting for the CI results to merge it.
