### ISSUE TITLE
Handling Text Input

### ISSUE THREAD

**Issue by JacobAMason** [facebook/react-native-website#236]
The page at https://facebook.github.io/react-native/docs/handling-text-input.html is rendering the majority of the documentation twice beginning with the phrase "For example." The markdown document seems fine though, so I'm not sure what's going on.

**Comment by charpeni** [comment]
Nice catch! 

Looks like some recent changes introduced this weird behavior.

**Comment by charpeni** [comment]
Thanks for the reporting, Hector just fixed this and it should be deployed in a few minutes.
