### ISSUE TITLE
Docs should mention that metro caches certain build files

### ISSUE THREAD

**Issue by robinsoncol** [facebook/react-native-website#2388]
## Description

The site should mention that the Metro bundler caches certain build files and that setting `resetCache` in `metro.config.js` can be used to apply files changes in the next build/deployment.

## What is the problem?

Changes to `.babelrc.js` aren't reflected in the app because Metro fetches the previous/cached `.babelrc.js`.

## How can we address it?

Mention this implicit behavior somewhere on the site.

## Why is it important?

The expected behavior is that one can make changes to certain build files and have those changes reflected in the next app deployment. React native doesn't follow that behavior; the docs should explain this.

## Who needs this?

Could be helpful for beginners.

## When should this happen (use version numbers if needed)?

No rush.

**Comment by Simek** [comment]
This information is a part of the [Metro Troubleshooting guide](https://facebook.github.io/metro/docs/troubleshooting/) and configuring Metro docs, but indeed, it would be nice to incorporate the information on the React Native website too.

I think that [Troubleshooting](https://reactnative.dev/docs/next/troubleshooting) page looks like a good place to add this note.
