### ISSUE TITLE
Incorrect image in iOS Native Modules page

### ISSUE THREAD

**Issue by luciancic** [facebook/react-native-website#2443]
## Description
There is an incorrect image under [Create Custom Native Modules Files](https://reactnative.dev/docs/native-modules-ios#create-custom-native-module-files):

<img width="859" alt="Screen Shot 2021-01-15 at 2 57 47 PM" src="https://user-images.githubusercontent.com/17990875/104773148-938ecf00-5742-11eb-83c2-0dbea1a42893.png">

The expected image is about how to create a new file in Xcode but the actual image is about how to open the Xcode project, a duplicate of the image in [Setup](https://reactnative.dev/docs/native-modules-ios#setup).

## Documentation version

0.63

**Comment by luism3861** [comment]
thanks for the issue!-.

**Comment by luism3861** [comment]
> thanks for the issue @luciancic !.

**Comment by luism3861** [comment]
thanks for the issue @luciancic !.
