### ISSUE TITLE
PlatformColor dcos example not running on android in example

### ISSUE THREAD

**Issue by MananDesai54** [facebook/react-native-website#2454]
## Description

I tried to run the example on android on the docs itself but it is crashing the expo app, running fine on ios
![Screenshot (563)](https://user-images.githubusercontent.com/52067783/105625391-fffa8400-5e4e-11eb-9de6-a17395774776.png)

## Documentation version
0.63

**Comment by luism3861** [comment]
@MananDesai54  thanks for the issue!.
