### ISSUE TITLE
There is a broken image.

### ISSUE THREAD

**Issue by Prashoon123** [facebook/react-native-website#2456]
### On one of the MD file, there is a broken image link. Here is the link to the [MD file](https://github.com/facebook/react-native-website/blob/master/website/versioned_docs/version-0.63/getting-started.md). This is the broken image link screenshot -
![image](https://user-images.githubusercontent.com/64588766/105630676-8b384180-5e70-11eb-8fa3-f56729ec9dd5.png)

**Comment by Simek** [comment]
Hi @Prashoon123, on the React Native website we use the Docusaurus 2 engine which renders the MDX files as a doc pages. To preserve the images versioning we had to use the relative asset URLs. So the issue only exist on GitHub, while viewing the MD files,, but not on the website itself (https://reactnative.dev/docs/environment-setup#thats-it). 

AFAIK there is no currently a way to fix the GitHub display without breaking the versioned asset support on the website.
