### ISSUE TITLE
Appearance page documentation also available for 0.60

### ISSUE THREAD

**Issue by dozGrou** [facebook/react-native-website#2487]
## Description

The page Appearance is available for the 0.60.x version and there is any notes to mention that the API is not implemented for this version. This gives bad information about the availability of the API.
To access this page, from the 0.63 version of the page, select 0.60 from the version selector.

## Documentation version

The issue occurs on the version 0.60 and 0.61.

**Comment by Simek** [comment]
Hi @dozGrou, can confirm, thank you for reporting the issue! 👍 

I will push the PR with the fix shortly.
