### ISSUE TITLE
Next page is 'Using a ScrollView' but the text links to handling-touches

### ISSUE THREAD

**Issue by AlbertVilaCalvo** [facebook/react-native-website#2498]
## Description

The last sentence of https://reactnative.dev/docs/handling-text-input says:

> Text input is one of the ways the user interacts with the app. Next, let's look at another type of input and [learn how to handle touches](https://reactnative.dev/docs/handling-touches).

However the next page of the docs is [Using a ScrollView](https://reactnative.dev/docs/using-a-scrollview).

## Documentation version

0.63 (latest)

**Comment by Simek** [comment]
Hello @AlbertVilaCalvo, 

sidebar do not represent the order of pages, it only groups the pages in certain sections, and those sections are changed quite often. If you want to navigate to the next page in the sidebar anyway, there are "Next" (and "Previous") buttons at the bottom of the page.

<img width="643" alt="Screenshot 2021-02-15 134904" src="https://user-images.githubusercontent.com/719641/107948990-e0a9cf00-6f94-11eb-8893-117de6992212.png">

**Comment by AlbertVilaCalvo** [comment]
@Simek I'm not talking about the sidebar, I'm talking about the button 'Next', which points to 'Using a ScrollView', whereas the text says 'Next, let's look at another type of input and learn how to handle touches' and links to https://reactnative.dev/docs/handling-touches

Either the Next button or the text is wrong because they don't match

**Comment by Simek** [comment]
@AlbertVilaCalvo "Next" and "Previous" buttons are generated based on the sidebar content which is an expected and unchangeable behavior.

The last sentence is redirecting you to other, more in-depth page, so you have an ability to choose if you want to learn more details about handling touches, or just go to the next introduction article, which is about ScrollView. 

Sidebar section title, in which this page is located, says "The Basics", and pages in there are usually just the short introduction to get into the React Native.

I'm not sure how to fix your issue, other than removing last sentence or changing the link, but it will be a regression, which doesn't sounds good to me (in my eyes it's a feature not a problem). But if you have another idea how to fix or improve the page, feel free to prepare a PR, I'll be happy to review it. :)

**Comment by AlbertVilaCalvo** [comment]
It's simple to fix. The pages on 'The Basics' are linked. Eg 'Using a ScrollView ends with "let's learn about list views next", and the button below correctly links to 'Using List Views'.

So to fix the issue in 'Using a ScrollView' we should change this:

> Text input is one of the ways the user interacts with the app. Next, let's look at another type of input and [learn how to handle touches](https://reactnative.dev/docs/handling-touches).

to something like this:

> Text input is one of the ways the user interacts with the app. If you are interested in other touch input types see [how to handle touches](https://reactnative.dev/docs/handling-touches).
>
> Next, let's [learn learn about using a ScrollView](https://reactnative.dev/docs/using-a-scrollview).

That's all. Maybe I open a PR next weekend.
