### ISSUE TITLE
Follow set-up instructions for mac does not work with latest environment

### ISSUE THREAD

**Issue by moc89** [facebook/react-native-website#2513]
## Description

I just started from stratch everything and followed Environmen Setup for ;
- CLI : React Native CLI
- Development OS: Mac OS
- Target OS: IOS
- Xcode version : 12.4
- Simulator : iOS 14.4

If you use this command npx react-native init AwesomeProject and create a project latest versions above, you will get compile error (CompileC error about Flipper). 

I've found a solution and I comment below code from POD file and it worked; 
  
```
use_flipper!
post_install do |installer|
flipper_post_install(installer)
end
```

**Comment by safaiyeh** [comment]
@moc89 are you on a M1 Mac? This is expected currently.
