### ISSUE TITLE
Headless JS specific Error import

### ISSUE THREAD

**Issue by GustavoMS97** [facebook/react-native-website#2524]
## Description

When developing a new feature on my app, i needed to use the headless js api, everything went well enough following the website's guide, but when implementing the retry policy, there is an issue with this specific piece of code below:

![image](https://user-images.githubusercontent.com/19798281/109584438-42635080-7ae0-11eb-823b-c60a3117fd26.png)

you see, there is an import for the error from a `'HeadlessJsTask'` library, but when looking inside NPM, this library does not exists, neither does the error exists inside react-native default lib. I need this error to implement the retry as i intend and as the website itself shows us to do, but i just cannot find this specific error and where do i import it from.

## Documentation version

Every version listed in the official website.

**Comment by Simek** [comment]
Hi @GustavoMS97, this is just an example, a pseudocode. You need to put your own import with you own HeadlessJS task in there.

**Comment by GustavoMS97** [comment]
@Simek i created my own HeadlessJS task but the problem is, throwing a simple Error just does not trigger the retry, as the code says, there is a specific Error expected by the library to do that. Is there and example of that? since throwing just an error does not do what is expected to.
