### ISSUE TITLE
[TextInput] autoGrow documentation is missing

### ISSUE THREAD

**Issue by rhazegh** [facebook/react-native-website#255]
Clicking on `autoGrow` in documentation leads nowhere:

<img width="807" alt="screenshot 2018-03-14 14 48 04" src="https://user-images.githubusercontent.com/2200559/37424437-d396d306-2796-11e8-90b5-970ec71588c0.png">

http://facebook.github.io/react-native/docs/textinput.html#autogrow leads nowhere.

**Comment by dooboolab** [comment]
@rhazegh This is removed according to PR #188

**Comment by Simek** [comment]
As @hyochan stated this property has been removed from the React Native. Also currently the links list in the page content are removed due to `onPageNav` component on the right side of the page.
