### ISSUE TITLE
Keyboard (iOS) example exhibits strange behavior

### ISSUE THREAD

**Issue by superguineapig** [facebook/react-native-website#2561]
## Description

The code example (and corresponding Expo emulation) at [https://reactnative.dev/docs/keyboard ](https://reactnative.dev/docs/keyboard) for both `Function Component` and `Class Component`s results in an infinite callback loop for `iOS` devices.

For iOS, it seems that the alert box _temporarily_ dismisses the Keyboard (automatically), causing the `hide` handler to fire. Upon dismissing the alert box, the keyboard is re-shown (automatically), which causes the `show` handler to fire, rinse and repeat...

Android does not exhibit the same behavior. The keyboard remains in a shown state while the alert box is being displayed, thus the handlers are not re-triggered.

I realize the example isn't really a "real-world" situation, but the behavior is unexpected and a bit jarring for an official example. The example code isn't necessarily wrong, but perhaps a note of warning about the automatic hide/show keyboard behavior on iOS could be helpful.

## Documentation version
The errant behavior is present for doc versions `0.62`, `0.63`, `0.64`, and `next`

**Comment by Simek** [comment]
Hi @superguineapig, thank you for reporting this issue and providing the detailed description of the problems! 👍
