### ISSUE TITLE
Lack of documentation of scrollToFocusedInput for ScrollView 

### ISSUE THREAD

**Issue by EvelynGYX** [facebook/react-native-website#2612]
## Description
As a react native developer, trying to look for scrollToFocusedInput documentation, when I worked on a requirement of scrolling to a specific component inside the scrollView, I couldn't find the description of scrollToFocusedInput in the official documentation (Components -> Scrollview -> scrollToFocusedInput). It would be better if it is documented. 

## Documentation version
0.63 and 0.64

**Comment by Simek** [comment]
Hi @EvelynGYX, are you sure that you are referring to the RN core not to the plugin or package?

I was not able to to find the `scrollToFocusedInput` method in the whole codebase React Native codebase.

Only reference I was able to find lead to the `react-native-keyboard-aware-scroll-view` package:
* https://github.com/APSL/react-native-keyboard-aware-scroll-view#auto-scroll-in-textinput-fields
