### ISSUE TITLE
Not seeing the 'Edit' button referred to in the 'Helping with Documentation' subsection of the CONTRIBUTING.md file

### ISSUE THREAD

**Issue by HM-23-HM** [facebook/react-native-website#2641]
## Description

I'm not seeing the 'Edit' button in the upper-right of "most pages" on the website.

## How can we address it?

Please tell us where we can go to make contributions to the documentation if we don't see the 'Edit' button.

**Comment by Simek** [comment]
Hi @HM-23-HM, you need to look for `Edit page` button at the bottom of the page, not at the top:

<img width="1541" alt="Screenshot 2021-06-07 at 17 51 57" src="https://user-images.githubusercontent.com/719641/121051356-ae2d1780-c7b9-11eb-9b2f-bd5b6c8e4d85.png">

Hope this solves your issue. 🙂 However, React Native uses the [versioned docs](https://docusaurus.io/docs/versioning) system, so you need to have in mind that `Edit page` will always lead to the unversioned docs source. You can read more about this in the repository [Readme](https://github.com/facebook/react-native-website#versioned-docs) or on the Docusaurus website.
