### ISSUE TITLE
website: iPad devices,  lost expo simulator in all examples,  after change horizontally.

### ISSUE THREAD

**Issue by luism3861** [facebook/react-native-website#2646]
## Description

this issue it's about,  for all examples in expo simulator lost after change iPad horizontally test in `iPad Air 4 generation` i believe for iPad pro it's the same issue 

![image](https://user-images.githubusercontent.com/36824170/122319032-a40bc700-cee5-11eb-8ca4-b6a3e64c4512.png)

## Documentation version

version: 0.64

**Comment by Simek** [comment]
Hi @luism3861, I'm not sure, but is looks like iPads are categorized/detected by Snack as mobile devices, and on mobile device the preview pane is disabled by default. I don't have an iPad right now, but I will try to use simulator to look at this issue. 

Meanwhile you can always launch Snack example in a new window, which will should redirect you to the Snack website, and the preview should be available (can you confirm that the preview pane is visible on https://snack.expo.io/ when visiting from iPad?).

<img width="265" alt="Screenshot 2021-07-04 100632" src="https://user-images.githubusercontent.com/719641/124378018-885b3b80-dcaf-11eb-83b7-bc56e924baf3.png">

CC: @IjzerenHein

**Comment by luism3861** [comment]
> Hi @luism3861, I'm not sure, but is looks like iPads are categorized/detected by Snack as mobile devices, and on mobile device the preview pane is disabled by default. I don't have an iPad right now, but I will try to use simulator to look at this issue. 
> 
> 
> 
> Meanwhile you can always launch Snack example in a new window, which will should redirect you to the Snack website, and the preview should be available (can you confirm that the preview pane is visible on https://snack.expo.io/ when visiting from iPad?).
> 
> 
> 
> <img width="265" alt="Screenshot 2021-07-04 100632" src="https://user-images.githubusercontent.com/719641/124378018-885b3b80-dcaf-11eb-83b7-bc56e924baf3.png">
> 
> 
> 
> CC: @IjzerenHein 

Hi @Simek i can confirmed example link works in iPad horizontally.
![image](https://user-images.githubusercontent.com/36824170/124532894-082ff580-ddd7-11eb-855b-9934999c86d7.png)

**Comment by IjzerenHein** [comment]
This happens when the width of the Snack window/iframe is less than `700px`. In that case we consider there to be too little room to display the preview pane. The following media-query is responsible for it:
https://github.com/expo/snack/blob/main/website/src/client/components/DevicePreview/DevicePreview.tsx#L47

If you think this behavior is wrong, please create an issue/PR in https://github.com/expo/snack with a suggested change.
