### ISSUE TITLE
Add Disclaimer for Developers using Yarn in "Getting Started" Section

### ISSUE THREAD

**Issue by waleedshkt** [facebook/react-native-website#2649]
## Description/ Problem

For developers got used to using `yarn` in their app projects, running `yarn run android` throws errors related to JAVA_HOME not set and emulator not found. But it all works fine if simply run `npx react-native run-android` instead

## How can we address it?

Better add a disclaimer for those using `Yarn` to use `npx react-native run-android` instead of `yarn run android` as the latter will not work

## Why is it important?

For many developers like me using 'Yarn', the above mistake can be easily made and overlooked with respect to the errors get thrown. And these errors can consume many hours if not days of precious time!

## Who needs this?

All developers using `Yarn`

## When should this happen (use version numbers if needed)?
In all the versions using `npx` to install the latest react native

**Comment by cortinico** [comment]
> running `yarn run android` throws errors related to JAVA_HOME not set and emulator not found.

Which kind of errors? Is this issue still relevant?
I personally have been using `yarn run android` for months without any issue at this stage. Can you please verify if the issue is still there?

**Comment by cortinico** [comment]
Closing as we haven't got a follow up on the questions.
If the issue is still happening, feel free to re-open
