### ISSUE TITLE
Is the sample code for ImageBackground correct?

### ISSUE THREAD

**Issue by camcam-lemon** [facebook/react-native-website#2664]
## Description/Problem

In the ImageBackground sample code, the resizeMode is passed from the styles prop.
It doesn't work this way.

[ImageBackground](https://reactnative.dev/docs/imagebackground)

## How can we address it?

If I pass the resizeMode prop to ImageBackground as shown in the code below, it works.

```tsx
<ImageBackground source={image} resizeMode="cover">
      <Text style={styles.text}>Inside</Text>
</ImageBackground>
```

## Why is it important?

A lot of people read the reference on the official website.
Many people end up using ImageBackground incorrectly.

## Who needs this?

This will help people who have seen the ImageBackground documentation.

**Comment by luism3861** [comment]
hi @camcam-lemon i think this is not an issue, if you take a look docs for` ImageBackground` props doesn't have resizeMode prop only `style` prop, `Image` Component has his own prop for resizeMode.

**Comment by Simek** [comment]
Hi @camcam-lemon,thank you for spotting this issue out! 👍 

Passing `resizeMode` as a style property works in Expo and in RNW, but it don't work correctly on the core-mobile platforms. I will update the example in the upcoming PR. 🙂

**Comment by camcam-lemon** [comment]
Hi @Slmek, thnak you for fixing!!
Thanks also to @luism3861!

I feel good knowing why it didn't work.
