### ISSUE TITLE
Docs are not multilingual. I can convert the docs into Spanish and maybe Mandarin Chinese too.

### ISSUE THREAD

**Issue by EvanErickson** [facebook/react-native-website#2683]
## Description

The docs are written in English and do not have translations for common languages like Spanish and Chinese (Mandarin). I am multi lingual and can write the docs for Spanish and maybe Chinese too. 

## What is the problem?

Non-native english speakers cannot read the docs. 

## How can we address it?

Translate all the docs into multiple languages.

## Why is it important?

Chinese is one of the most common languages in the world, along with Spanish, Portuguese, and Arabic.

## Who needs this?

All devs that speak English as a second language, or do not speak english at all.

## When should this happen (use version numbers if needed)?

It should happen ASAP but it is a massive project. I could probably do Spanish over the weekend but Chinese would take at least 5-7 days. What I would recommend is using Google Translate to quickly convert everything and then having a native dev (like me) who speaks both English and Spanish / Chinese to review it for accuracy. We should do it for at least: Spanish, Chinese, Arabic, Russian, Portuguese, and Hindi.

**Comment by Simek** [comment]
Refs #181

**Comment by luism3861** [comment]
> ## Description
> The docs are written in English and do not have translations for common languages like Spanish and Chinese (Mandarin). I am multi lingual and can write the docs for Spanish and maybe Chinese too.
> 
> ## What is the problem?
> Non-native english speakers cannot read the docs.
> 
> ## How can we address it?
> Translate all the docs into multiple languages.
> 
> ## Why is it important?
> Chinese is one of the most common languages in the world, along with Spanish, Portuguese, and Arabic.
> 
> ## Who needs this?
> All devs that speak English as a second language, or do not speak english at all.
> 
> ## When should this happen (use version numbers if needed)?
> It should happen ASAP but it is a massive project. I could probably do Spanish over the weekend but Chinese would take at least 5-7 days. What I would recommend is using Google Translate to quickly convert everything and then having a native dev (like me) who speaks both English and Spanish / Chinese to review it for accuracy. We should do it for at least: Spanish, Chinese, Arabic, Russian, Portuguese, and Hindi.

@EvanErickson  that's a good idea i can help you in spanish translation!.
