### ISSUE TITLE
The website supports only the english language

### ISSUE THREAD

**Issue by MidouWebDev** [facebook/react-native-website#2704]
## What is the problem?

The website supports only the english language ! It isn't multilingual !

## How can we address it?

Create a repository where developers will help with translating the React Native website !

## Why is it important?

There is some developers that don't speak english and they want to learn React Native so they can't because the React Native website isn't supporting their first language

## Who needs this?

Non-english speakers

## Additional : 

I speak **Arabic** and **French** in addition to **English** so i can help with translating to these languages !

**Comment by luism3861** [comment]
Refs #181
