### ISSUE TITLE
Link to  "curated list of open source React Native apps" takes you to https://infinite.red/ instead of https://github.com/ReactNativeNews/React-Native-Apps

### ISSUE THREAD

**Issue by Maker-Mark** [facebook/react-native-website#2710]
## Description
The live website's showcase has a external link to  "curated list of open source React Native apps" takes you to https://infinite.red/ instead of the correct https://github.com/ReactNativeNews/React-Native-Apps.
This seems to be correct in this repo, but it does not reflect on the live site. 
Check it out for yourself at https://reactnative.dev/showcase by clicking/hovering on "open source React Native apps".

## Documentation version
- Any

**Comment by luism3861** [comment]
#2713

**Comment by Maker-Mark** [comment]
@luism3861 Sweet, glad we fixed it! What a weird bug!!
