### ISSUE TITLE
iOS-2048 and swift-2048 repository does not exist

### ISSUE THREAD

**Issue by Huang-Libo** [facebook/react-native-website#2746]
## Description

There are some demos of the _2048 sample project_ in the documentation, but the project no longer exists on GitHub. Links used in the document:

- https://github.com/JoelMarcey/iOS-2048
- https://github.com/JoelMarcey/swift-2048

## Documentation version

- 0.6.5 ( Last updated on 8/17/2021 )

**Comment by luism3861** [comment]
hi @Huang-Libo  thanks for the link issue, it seems this repo has deleted!

cc: @Simek

**Comment by Simek** [comment]
Hi @Huang-Libo,  thank you for the report on broken links! 👍 

I was able to confirm that we should remove the whole "See the Code" section on the ObjectiveC and Swift partials on "Integration with Existing Apps" page (ideally in `next` and `0.65` docs):
* https://reactnative.dev/docs/integration-with-existing-apps

@luism3861 Would you like to take care of that? 🙂

**Comment by luism3861** [comment]
> Hi @Huang-Libo, thank you for the report on broken links! 👍
> 
> I was able to confirm that we should remove the whole "See the Code" section on the ObjectiveC and Swift partials on "Integration with Existing Apps" page (ideally in `next` and `0.65` docs):
> 
> * https://reactnative.dev/docs/integration-with-existing-apps
> 
> @luism3861 Would you like to take care of that? 🙂

ok @Simek  i will take care of that 👍🏾
