### ISSUE TITLE
Running on device page - Platform selections broken

### ISSUE THREAD

**Issue by colindaly** [facebook/react-native-website#2771]
## Running on device page
https://github.com/facebook/react-native-website/blob/main/docs/running-on-device.md
Cannot change from Android to iOS
Linux is also selected by default and cannot select Windows or Mac

## Documentation version
Latest and previous versions

**Comment by Simek** [comment]
Hi @colindaly, the tabs on the Running On Device page seem to work fine for me on macOS and Windows in Chrome and FF.

Can you provide the details about your OS and browser?

Also, did you try to refresh the local caches? (<kbd>Cmd/Ctrl + Shift + R</kbd>)

**Comment by GijsWeterings** [comment]
Hi @colindaly! I can't reproduce this on my devices on https://reactnative.dev/docs/next/running-on-device .
Are you using a noscript-like browser extension perhaps? Like Simek suggested, let us know your browser details if you think this isn't specific to your device, then we can try and reproduce :)

**Comment by slorber** [comment]
@colindaly we'll need more infos about your env to debug this tag problem.

Please paste the actual page link, not the github md file link.

Can you open your console and check for errors? Maybe React didn't load/hydrate properly and you only got static markup?

In very slow connexions/cpu devices, it may take time to hydrate unfortunately, and clicks do nothing for a few seconds.

Please try to refresh the page and see if it works better.

---

@Josh-Cena made a change on Tabs recently (in beta 6), but I don't see how this could be the reason: https://github.com/facebook/docusaurus/pull/5442

**Comment by slorber** [comment]
Thanks, we found the cause: https://github.com/facebook/docusaurus/issues/5653
