### ISSUE TITLE
iOS toggle disabled on "Setting up the development environment" page

### ISSUE THREAD

**Issue by Dabrown18** [facebook/react-native-website#2790]
## Description

https://user-images.githubusercontent.com/20943614/134602767-6c129489-0103-4949-84fd-40f27ab63bd6.mp4

## Documentation version

0.65

**Comment by slorber** [comment]
@Dabrown18 can you still reproduce this issue? 

Have you refreshed the page? 

Are there any logs in the chrome console or js file loads failures in the network tab?

Is the sidebar working: can you uncollapse a category?
