### ISSUE TITLE
How to submit a component?

### ISSUE THREAD

**Issue by Jerameel** [facebook/react-native-website#280]
Hi,  I have made a component for react native and I would like to submit it the official component list. Is this possible? 

Repository: https://github.com/Jerameel/react-native-snackbar-js

**Comment by charpeni** [comment]
Sorry, only core components are documented here.

Community components could be shared/listed here:
- https://native.directory/
- https://github.com/jondot/awesome-react-native

I'll close this issue, but your contributions to the community are really appreciated.
