### ISSUE TITLE
Documentation for enabling hermes on android is possibly missing setting "enableHermes"

### ISSUE THREAD

**Issue by Adnan-Bacic** [facebook/react-native-website#2813]
## Description

[Documentation to enable hermes for android](https://reactnative.dev/docs/hermes#android) mentions this inside the android/app/build.gradle file:

```
  project.ext.react = [
      entryFile: "index.js",
-     enableHermes: false  // clean and rebuild if changing
+     enableHermes: true  // clean and rebuild if changing
  ]
```

But inside the same file, if you scroll down a little, there is also this part:

```
/**
 * Whether to enable the Hermes VM.
 *
 * This should be set on project.ext.react and mirrored here.  If it is not set
 * on project.ext.react, JavaScript will not be compiled to Hermes Bytecode
 * and the benefits of using Hermes will therefore be sharply reduced.
 */
def enableHermes = project.ext.react.get("enableHermes", false);
```

It seems you must also set this variable to true if you want hermes to be fully enabled for android.

The documentation should also mention this line and tell users to also set this variable to true.

However the same document also mentions this function you can run to check that hermes is enabled:

`const isHermes = () => !!global.HermesInternal;`

when i run this function it returns true for android EVEN when i dont change

`def enableHermes = project.ext.react.get("enableHermes", false);`

to

`def enableHermes = project.ext.react.get("enableHermes", true);`

## What is the problem?

I think its confusing that there seems to be 1 place you must set hermes to true, according to the documentation. However the file itself looks like you must set it 2 places. But when i run the function to check if hermes is enabled, it works with just the part the documentation covers. This makes me question if there is any value in setting the second part to true as well.

## How can we address it?

If setting `enableHermes` to true is important to have hermes fully enabled for android, it should be mentioned in the documentation. Even if it doesnt matter if its true or false, the documentation could still mention that we dont need to change it.

## Why is it important?

To reduce confusion. I dont feel its 100% clear if setting `enableHermes` is needed or not. When the comments in the file tell you to mirror the `project.ext.react` value but the official docs dont mention this part at all.

## Who needs this?

People who work on the android part of a project.

## When should this happen (use version numbers if needed)?

Since this is only a simple change to the documentation, it shouldt have an impact on react-native itself. It could technically be added whenever.

**Comment by Huxpro** [comment]
Thanks @kraenhansen for answering @Adnan-Bacic's question. I'll close this and we can follow up on the PR ;)
