### ISSUE TITLE
Provide additional example for manual linkage of Libraries

### ISSUE THREAD

**Issue by MauriceArikoglu** [facebook/react-native-website#2820]
## Description

Stated here https://reactnative.dev/docs/integration-with-existing-apps for the iOS (Swift) Tutorial is the following sentence:

> It is technically possible not to use CocoaPods, but that would require manual library and linker additions that would overly complicate this process.

I would like to request additional documentation on the specific Build Settings required to manually link the RN libraries. I believe there are many Xcode power users among us wanting to add RN without using cocoapods if possible. Linking for third-party libraries usually follows a streamlined process, although can also derive based on the library-vending parties design decisions. Because I don’t know if manual linking is just the basic incorporation of libraries and linker settings and the documentation cleary states a „We know how but won’t tell“ situation, I would like to request this information be added on the documentation page. Maybe we can add it as a subpage or hide it within a Dropdown to keep the above linked guide accessible and easy for beginners but offer more advanced solutions for power users.

## What is the problem?

Solution for power users is hinted at but not stated.

## How can we address it?

Add the missing documentation part for specific RN libraries to be manually linked 

## Why is it important?

Freedom of choice what dependency managers to use or integrate!

## Who needs this?

iOS developers of all kind (IMO E>junior should be aware of concepts like linking)

## When should this happen (use version numbers if needed)?

Asap would be lovely. I would do it myself, but as I am neither author of the library nor contributor here, I am afraid I would slow the process down unnecessarily (get back to me though if we can change the points above)

**Comment by MauriceArikoglu** [comment]
Maybe we can build on top of this existing page https://reactnative.dev/docs/linking-libraries-ios and bring it up to date (it seems deprecated) as well as add the required steps to „prevent“ the usage of cocoapods specifically when integrating with an existing app.

**Comment by MauriceArikoglu** [comment]
Nope, not updated yet

**Comment by MauriceArikoglu** [comment]
Nice to know at least the bot cares about the issues here :)

**Comment by cortinico** [comment]
Thanks for reporting this @MauriceArikoglu. 

> on top of this existing page [reactnative.dev/docs/linking-libraries-ios](https://reactnative.dev/docs/linking-libraries-ios) and bring it up to date (it seems deprecated)

A lot of the React Native documentation is community driven. Feel free to submit a PR to update this section, I'll be happy to review it (or find someone with iOS expertise to review and provide input).

> I believe there are many Xcode power users among us wanting to add RN without using cocoapods if possible

Also here the best approach would be to start drafting a page and iterating on it. Sadly, I'm not able to help with the exact instructions here. I'm not aware of anyone using RN without cocoapods in the OSS space. If there is someone doing so, having them kicking off those kinds of pages would be great 👍

**Comment by MauriceArikoglu** [comment]
@cortinico Thanks for getting back on that. I am currently not working with RN on a regular basis, but made sure to write a ToDo for me, if I do so. Looking forward to writing this then.
