### ISSUE TITLE
Getting Started MacOS - Outdated for Mac Silicon

### ISSUE THREAD

**Issue by nathanbacon** [facebook/react-native-website#2834]
## Description

Documentation advises the reader to use system version of ruby. However, this [no longer works for Apple silicon](https://github.com/CocoaPods/CocoaPods/issues/9907). The solution is to install a version of Ruby built for arm64 by using rbenv, rvm, or homebrew.

## What is the problem?

System version of Ruby is no longer useful on M1 Macs however the [documentation states otherwise](https://github.com/facebook/react-native-website/blob/9cf006a1831c32d43da802f70f3ce67e2751f6d6/docs/_getting-started-macos-ios.md).

## How can we address it?

Update the documentation to advise the reader to install Ruby on their own prior to running `sudo gem install cocoapods`. The solution is well explained [here](https://stackoverflow.com/a/66556339).

## Why is it important?

The docs are inaccurate for some readers. This causes the setup process to fail on `pod install`.

## Who needs this?

New learners

**Comment by cortinico** [comment]
We partially discussed this here: https://github.com/react-native-community/discussions-and-proposals/discussions/454

I think we can update the docs to _suggest_ the usage of version managers and mention that the default template is already _rbenv-ready_
