### ISSUE TITLE
Are the Hermes Profiler docs outdated?

### ISSUE THREAD

**Issue by leecommamichael** [facebook/react-native-website#2837]
## Description
1. I ran `npx react-native init Whatever`
2. enabled Hermes in the Podfile
3. built the app
4. There is no **Enable Sampling Profiler** item in the debug menu.

The page at https://reactnative.dev/docs/profile-hermes asks me to press the **Enable Sampling Profiler** button in the debug menu. Is this still correct?

<img width="455" alt="Screen Shot 2021-11-02 at 6 30 01 AM" src="https://user-images.githubusercontent.com/13748676/139839100-c8306b60-e12b-46ba-9964-3561e25da4ea.png">

## Documentation version
0.66.1

**Comment by neildhar** [comment]
Hi @leecommamichael, the Hermes sampling profiler is currently only supported on Android. The documentation predates iOS support for Hermes, so that's probably why it's unclear. Sorry about the confusion.
