### ISSUE TITLE
Incorrect Android APIs in requirements. Github's README react-native 0.64

### ISSUE THREAD

**Issue by CyxouD** [facebook/react-native-website#2851]
## Description

When developer opens 0.64 stable build at https://github.com/facebook/react-native/tree/0.64-stable, he sees that `React Native apps may target iOS 10.0 and Android 4.1 (API 16) or newer`. However, API 16-20 are dropped in 0.64 according to https://reactnative.dev/blog/2021/03/12/version-0.64 and minSdkVersion in build.gradle file https://github.com/facebook/react-native/blob/0.64-stable/ReactAndroid/build.gradle
![image](https://user-images.githubusercontent.com/17162008/142195429-d7d5d398-a1fe-47c7-b0cb-6843e31a8814.png) 

## Documentation version

react-native 0.64 stable build https://github.com/facebook/react-native/tree/0.64-stable

**Comment by Simek** [comment]
Hi @CyxouD, thanks for reporting this! 👍 

However it is a problem with `Readme.md` file in the main repository and it is not related to the website, so you need to create the issue in there:
* https://github.com/facebook/react-native
