### ISSUE TITLE
Button to switch to iOS documentation on "Running on device" page doesn't work

### ISSUE THREAD

**Issue by 1mike12** [facebook/react-native-website#2852]
## Description
I thought maybe this was just my browser or a one off problem, but everytime I've come back to the docs over the last month it's been exactly the same. I guess it's a minor issue but still very annoying. 

By default, the docs start you off on android. When I click the ios button, nothing happens. The only way to see the docs for ios is to:

1. go to the docs for another version. Say 0.65
2. Either read the info on this older version or: 
3. go back to 0.66 and miraculously the button can be clicked

I verified this on firefox, safari and chrome. 

![image](https://user-images.githubusercontent.com/4983282/142634194-48327450-2ae2-456a-8e46-17f528147b61.png)

## Documentation version

0.66

**Comment by luism3861** [comment]
Duplicate of #2771.

**Comment by luism3861** [comment]
Hi @1mike12 thanks for the issue.
 Duplicate of #2771.

**Comment by 1mike12** [comment]
how did I not find that haha. I was really wondering how it could be possible I was the 1st reproter. closing as dupe
