### ISSUE TITLE
Environment Setup specifically for macOS

### ISSUE THREAD

**Issue by FavourAmayo** [facebook/react-native-website#2867]
## Description

Request for Environment Setup for macOS, since setup requires additional steps not mentioned. 

## What is the problem?

After doing a global install of Expo CLI, mac users cannot go directly to the command `expo init <Name of Project>`. This is due to the fact that the global install of NPM is not accessible in the path of a mac computer. Also, creating a React Native application requires a simulation of a mobile phone environment, so there should be instructions on how to do initial setup on a mac computer

## How can we address it?

For the not being able to use the `expo init <Name of Project>` command, mac users can first run these commands in their terminal. After running `npm install -g expo-cli`, the mac users should run these commands. 

```
echo $PATH
export PATH=$PATH:~/.npm-global/bin
source ~/.bash_profile
```
Once they have done that, they can create their application with this command:

`npx expo init <Name of Project>`

Since they will want to simulate a phone environment on their computer, they should download, if they don't already have it, XCode and make sure they have the latest command line tools installed by going to File->Preferences->Locations->Command Line Tools.

If they want to start the default simulator, they can go to Xcode->Open Developer Tool->Simulator. When they run the command `npm start`, their code on Visual Studio Code will open up a local host page on the browser. On the browser, they will see the option, "Run on iOS Simulator". Once that option is clicked, their code will reflect on the phone simulator.  

## Why is it important?

These steps allows mac users to be able to start doing development directly on their computer for mobile development instead of scouring the internet for why they cannot just get started.

## Who needs this?

Mac Users

## When should this happen (use version numbers if needed)?

Immediately, on the Setting up the development environment portion of the Environment Setup section.

**Comment by cortinico** [comment]
> This is due to the fact that the global install of NPM is not accessible in the path of a mac computer

The react-native docs assume that you have a correctly set up `npm` installation, with a proper configuration of the `PATH` variable. I believe that we should not adapt the instructions to explaing this specific steps. It's safe to assume `npm` in installed and configured.
We're doing the same with other tools (such as `brew` and others).

> instead of scouring the internet for why they cannot just get started.

The web is full of resources on how to configure this. Perhpas we could find a good guide and link it, but I would refrain from giving specific setup commands related to `npm`.

Closing here as this is not really actionable, but happy to discuss if you wish to link a guide you found useful
