### ISSUE TITLE
[docs] add definition of StatusBar

### ISSUE THREAD

**Issue by gregfenton** [facebook/react-native-website#2870]
## Description

The page for [StatusBar](https://reactnative.dev/docs/statusbar)  does not define what the status bar is.  A screenshot  would be helpful as well.

**Comment by Simek** [comment]
Hi @gregfenton, we usually do not use the screenshot for the APIs or Components, in most cases Snacks are the way to go, which besides the preview also enable users to play and experiment with the API or Component code directly on the page.

Screenshots also are hard to maintain and tends to get outdated quickly. Do you have a problems with opening the example in build-in simulator or running it's code on your own device?

**Comment by gregfenton** [comment]
How about just a description of what a StatusBar is in the preamble of the doc?  Having to open a sample just to figure out what a "StatusBar" is makes the information less accessible.  And...there's a chance the reader still wouldn't know "what to look for".

Also, are there differences between different platforms when it comes to the StatusBar.  I'm not talking  about the differences you get by tweaking configuration, but differences that are native to the platform?

**Comment by Simek** [comment]
Agree, that is a good idea to expand the initial sentences with the general description what exactly `StatusBar` is.

Would you like to try expand that preamble and push a PR?
