### ISSUE TITLE
Conflicting doc for tvParallaxProperties of TouchableOpacity

### ISSUE THREAD

**Issue by KishoreBarik** [facebook/react-native-website#2891]
## Description

The documentation for the the `tvParallaxProperties` of `TouchableOpacity` is conflicting. It shows android flag whereas documentation mentions about Apple TV.

<img width="628" alt="image" src="https://user-images.githubusercontent.com/13726932/146757848-5504d585-eaf6-4042-8620-081e5335c42e.png">

## Documentation version

0.66
https://reactnative.dev/docs/touchableopacity

**Comment by Simek** [comment]
Hi @KishoreBarik, thank you for the report!

It looks like beside the problem with incorrect label, the main problem is that ptobably this pro has been removed in `0.64` release, but there is no entry in Changelog mentioning. 🤔 Last entry of the `RCTTVView` can be seen on `0.63` branch:
* https://github.com/facebook/react-native/blob/0.63-stable/React/Views/RCTTVView.m
