### ISSUE TITLE
Meta instead of Facebook

### ISSUE THREAD

**Issue by raymon-zhang** [facebook/react-native-website#2893]
Small issue, but the website still says Facebook in many places, including the copyright notice at the bottom. 
![image](https://user-images.githubusercontent.com/65573069/146860578-94cd22e0-43e6-4027-a42b-e36563fef976.png)

Given that the Facebook Open Source website has been changed to "Meta Open Source", should these be updated as well?

**Comment by bharadwajduggaraju** [comment]
this is a good point, I think the react website has the same issue, let me check and most likely raise an issue

**Comment by slorber** [comment]
@Simek we updated the logo on Docusaurus website in case you want to copy it 😄

**Comment by cortinico** [comment]
> we updated the logo on Docusaurus website in case you want to copy it 😄

@slorber I still see the old one on https://docusaurus.io/

**Comment by slorber** [comment]
@Simek the PR has been merged but I suggest to wait for the next Docusaurus release as we did some changes on Infima so that logo can be larger by default. (it previously had a small "max-width" + no good way to override it)

**Comment by Simek** [comment]
@slorber TBH, I think that the new logo is too big in comparison to the old one, and in general to the Footer content, so probably we will shrink the size anyway. 😅
