### ISSUE TITLE
Bug in Documentation Page

### ISSUE THREAD

**Issue by BattleOfPlassey** [facebook/react-native-website#2941]
## Description

Found a bug on the documentation page 'docs/running-on-device.md' . Although the highlighted section in RED is not present on markdown file, **unfortunately, it appears on Android/Windows page as evident in the screenshot.**
## Documentation version
![image](https://user-images.githubusercontent.com/35087196/150644595-4777f6e3-9e79-4db6-bce3-a408f77d4da0.png)

0.67

**Comment by luism3861** [comment]
hi @BattleOfPlassey thanks for the issue i sent a PR to fix this, thank you!!.

**Comment by BattleOfPlassey** [comment]
> hi @BattleOfPlassey thanks for the issue , I sent a PR to fix this, thank you!!.

Thanks.

**Comment by BattleOfPlassey** [comment]
PR https://github.com/facebook/react-native-website/pull/2944 and https://github.com/facebook/react-native-website/pull/2943 fix this. So Closing this issue.
