### ISSUE TITLE
React Navigation Page Code does not work

### ISSUE THREAD

**Issue by LFC6times** [facebook/react-native-website#2949]
## Description

As someone trying to get the hang of React Native with Expo, I am trying to use React Navigation. When I copied the code from the documentation page (https://reactnative.dev/docs/navigation#react-navigation, in #usage), and refreshed my app, I get a Render Error stating that "Text strings must be rendered within a <Text> component."
 
![image](https://user-images.githubusercontent.com/72238524/151291157-9cc60a67-2a10-45df-997f-39bd0d65afe9.png)
![image](https://user-images.githubusercontent.com/72238524/151291220-557a7f9e-e3bb-4a38-9c91-c4e65b56fa28.png)

The first image is the error on my phone (Android Pixel 5, latest version of Android and Expo app), and the second image is the error from my Expo CLI.

I do not know how to properly code this, and I have checked at least ten sites, none of which have a working solution.

## Documentation version

Documentation version 0.63 - Next

**Comment by luism3861** [comment]
hi @LFC6times try to read react navigation docs [react navigation docs](https://reactnavigation.org/docs/getting-started)

**Comment by DibyajyotiMishra** [comment]
@LFC6times you might have accidentally added some textual elements outside the <Text>. Please do check your code again. The error doesn’t seem to be coming from React Navigation. To me it seems like a classical typo in your code somewhere.

**Comment by Simek** [comment]
Hello @LFC6times, you might want to try checkout the React Navigation or the Expo docs, which might help you with your issue:
* https://reactnavigation.org/docs/getting-started/
* https://docs.expo.dev/guides/routing-and-navigation/

You can also try to create issues in their repos, unfortunately this tracker is related to the React Native website issues, so I going to close this one. Hope you can understand that!

P.S. Also thank you @luism3861 & @DibyajyotiMishra for the engagement here, your awesome! 🙂
