### ISSUE TITLE
$ adb devices shows the error command not found

### ISSUE THREAD

**Issue by CaptainEboy** [facebook/react-native-website#2969]
## Description
After running the command $ adb devices, I get a message on the terminal, command not found

**Comment by cortinico** [comment]
I don't think this is a problem with the website. The problem you're having is because you haven't set up your Android SDK correctly. Specifically you have to update the `PATH` environment variable.

You can find instructions on how to do it here: https://reactnative.dev/docs/environment-setup

**Comment by CaptainEboy** [comment]
Thanks would check it out
