### ISSUE TITLE
Use `brew install cocoapods` instead of `arch -x86_64 pod install` on M1 MacBook

### ISSUE THREAD

**Issue by bangseongbeom** [facebook/react-native-website#3003]
To solve the `pod install` issue on the M1 MacBook, #2974 suggests `arch -x86_64 pod install` command. You can also find it in [a CocoaPods issue](https://github.com/CocoaPods/CocoaPods/issues/10518#issuecomment-798912624).

However, this approach is inappropriate. You may receive the following warnings when you run `arch -x86_64 pod install`:

https://github.com/facebook/react-native/issues/33017

> [!] Do not use "pod install" from inside Rosetta2 (x86_64 emulation on arm64).
> 
> [!]  - Emulated x86_64 is slower than native arm64
> 
> [!]  - May result in mixed architectures in rubygems (eg: ffi_c.bundle files may be x86_64 with an arm64 interpreter)
> 
> [!] Run "env /usr/bin/arch -arm64 /bin/bash --login" then try again.

This is [a Ruby problem built in macOS](https://betterprogramming.pub/ruby-on-apple-silicon-m1-macs-fb159849b2f5). The built-in Ruby has been [deprecated](https://github.com/ffi/ffi/issues/870#issuecomment-756989318) since Catalina (10.15), so you'll have to find another way.

## Solution

`brew install cocoapods` internally downloads a Ruby suitable for the M1 MacBook.

The whole method I'd like to suggest is:

1. `brew install cocoapods`
2. `pod install`

instead of:

1. `sudo gem install cocoapods`
2. `sudo arch -x86_64 gem install ffi`
3. `arch -x86_64 pod install`

## See also

- https://stackoverflow.com/a/65334677
- https://stackoverflow.com/a/66556339

**Comment by cortinico** [comment]
@cipolleschi What's your take here?

> brew install cocoapods internally downloads a Ruby suitable for the M1 MacBook.

IMHO relying on brew for this sounds "risky", mostly because we have the `.rubyversion` file (https://github.com/facebook/react-native/blob/main/template/_ruby-version) and all the other machinery to handle the proper ruby/cocoapods version. It seems weird that we can't use them and rely on brew giving us a "good" version of cocoapods for M1.

**Comment by danilobuerger** [comment]
Could the instructions be for an older version of ffi? Afaik ffi supports arm64. It seems to me that those steps are no longer required and installing via bundler should just be it.

**Comment by cipolleschi** [comment]
Hi everyone! 
Having a look at [`ffi` changelog](https://github.com/ffi/ffi/blob/master/CHANGELOG.md#1151--2021-05-22) it looks like that, starting from version 1.15.1, they are supporting `arm64`, as @danilobuerger was saying.

I propose that we update the doc for M1 users specifying that, if they encounter issues, they should update the `ffi` gem to at least that minimum version. What do you think @danilobuerger, @bangseongbeom, @cortinico?

**Comment by cortinico** [comment]
Seems great to me 👍

**Comment by bangseongbeom** [comment]
@danilobuerger @cortinico [the Apple ARM CPU patch](https://github.com/ffi/ffi/pull/899) on `ffi` version 1.15.1 won't work well on M1 MacBook's system Ruby. `ffi` filters CPU architecture via `rbconfig`, but the `rbconfig` on the system Ruby provides incorrect CPU arch information (`"host_cpu"` and `"host"` as `"x86_64"` and `"x86_64-apple-darwin21"`).

You can find your `rbconfig` information with the following code (excerpted from [Martin Albrecht](https://betterprogramming.pub/ruby-on-apple-silicon-m1-macs-fb159849b2f5)):

(Make sure you are using system Ruby before running this script.)

```sh
ruby -e 'require "rbconfig"; pp RbConfig::CONFIG' | grep "host"
```

My result:

```sh
 "host_os"=>"darwin21",
 "host_vendor"=>"apple",
 "host_cpu"=>"x86_64",
 "host"=>"x86_64-apple-darwin21",
 "host_alias"=>"",
```

**Comment by danilobuerger** [comment]
Starting with rn 0.68, we are expecting a ruby version of 2.7.4 as set in the Gemfile and .ruby-version. Thats not the ruby shipped from apple anyway.

**Comment by bangseongbeom** [comment]
@danilobuerger Hmm... then we'll need to modify these paragraphs later.

https://reactnative.dev/docs/environment-setup#cocoapods

> CocoaPods is built with Ruby and it will be installable with the default Ruby available on macOS. You can use a Ruby Version manager, however we recommend that you use the standard Ruby available on macOS unless you know what you're doing.
>
> ```sh
> sudo gem install cocoapods
> ```

**Comment by cortinico** [comment]
> @danilobuerger Hmm... then we'll need to modify these paragraphs later.

That's correct. The recommendation would be to use bundler in the near future as it allows us to reduce the variability of ruby/cocoapods versions. The new app template comes with all the necessary files in place and the docs should be updated to reflect this.

**Comment by bangseongbeom** [comment]
Thanks for the detailed explanation! I close this issue as it will be resolved in the near future.

**Comment by javvadigithub** [comment]
This works for me :)
    brew install cocoapods
    pod install

**Comment by madilekci-avena** [comment]
This worked for me on m1 pro Ventura, thanks

**Comment by rahulpunchh** [comment]
Worked For me
