### ISSUE TITLE
Provide JavaDoc documentation for Android API and Java classes of React Native

### ISSUE THREAD

**Issue by cshong87** [facebook/react-native-website#3008]
## Description

Please provide official JavaDoc documentation for all Android APIs and Java classes of React Native, for examples:

1. ReactApplicationContext (package: com.facebook.react.bridge.ReactApplicationContext).
2. ReactPackage (package: com.facebook.react.ReactPackage).
3. NativeModule (package: com.facebook.react.bridge.NativeModule).
4. ReactActivity (package: com.facebook.react.ReactActivity).

The above are just few examples.

## What is the problem?

When developing native modules, I would like to know whether a React Native Java class or API have the functions I need. Currently, I have to look at React Native's source code.

## How can we address it?

With JavaDoc documentation, it will be easier for me to search for classes and look at their methods.

## Why is it important?

It make easier to learn React Native's JAVA classes.

Normally, JavaDoc documentation page will also display the methods of interface implemented by a Java class.

## Who needs this?

I am a Android developer. I am also a new learner for React Native.

**Comment by cortinico** [comment]
> Please provide official JavaDoc documentation for all Android APIs and Java classes of React Native, for examples:

Closing as those classes are already documented with Javadoc 👍
