### ISSUE TITLE
☂️ Help us Kotlin-ify the React Native Website

### ISSUE THREAD

**Issue by cortinico** [facebook/react-native-website#3018]
Hey all 👋 
We're looking for some community support to help us convert our website, https://reactnative.dev to be more Kotlin-friendly. 

A lot of the docs that you can find on the website are currently Java only. We're looking into adding snippets for both Java and Kotlin, using a tabbed view. 

## List of Pages to address.

Those are the pages that needs conversion:

- [x] docs/headless-js-android.md (done by @rokkoo https://github.com/facebook/react-native-website/pull/3125)
- [x] docs/native-modules-android.md (done by @alanjhughes https://github.com/facebook/react-native-website/pull/3030)
- [x] docs/integration-with-android-fragment.md (done by @mdvacca https://github.com/facebook/react-native-website/pull/2977)
- [x] docs/new-architecture-library-intro.md (done by @mbharadwajfb - https://github.com/facebook/react-native-website/pull/3116)
- [x] docs/new-architecture-app-modules-android.md (done by @tusharvars - https://github.com/facebook/react-native-website/pull/3241)
- [ ] docs/new-architecture-app-renderer-android.md (assigned to @dakshbhardwaj)
- [ ] docs/new-architecture-app-renderer-ios.md
- [x] docs/new-architecture-library-android.md (done by @aerrayes https://github.com/facebook/react-native-website/pull/3194)
- [x] docs/custom-webview-android.md (done by @JazibJafri https://github.com/facebook/react-native-website/pull/3060)
- [x] docs/profile-hermes.md (handled here https://github.com/facebook/react-native-website/pull/3193)
- [x] docs/communication-android.md (done by @junaidn https://github.com/facebook/react-native-website/pull/3070)
- [x] docs/native-components-android.md (done by @RickardZrinski https://github.com/facebook/react-native-website/pull/3068)
- [x] docs/_integration-with-exisiting-apps-java.md - (done by @EzequielDeOliveira - https://github.com/facebook/react-native-website/pull/3150)
- [ ] docs/getting-started.md (Specifically the `environment-setup` section would need some mention of Kotlin).

## How to migrate a page.

If you wish to convert one of the page you should:
1. Verify that the page is not claimed yet.
2. Comment here that you claim a page.
3. Start working on adding Kotlin support for the page. 
   1. Use this PR as inspiration: https://github.com/facebook/react-native-website/pull/2977
   1. Make sure you're testing the code you're writing (please take the chance to verify that the doc is also up to date).
   1. If the documentation is not up to date, send a separate PR fixing the inconsistencies with the doc.
   1. You Kotlin code should be formatted with ktfmt (see below).
5. Send the PR for review. Ping @cortinico and @mdvacca for a review.

## Code formatting

Please use KtFmt to format the Kotlin code snippets. 

You can the web UI to reformat directly from the browser:
https://facebookincubator.github.io/ktfmt/

**Comment by rokkoo** [comment]
Hi, I would like take the `docs/headless-js-android.md` an try to migrate it :)

**Comment by cortinico** [comment]
> Hi, I would like take the `docs/headless-js-android.md` an try to migrate it :)

Please go ahead @rokkoo 👍 I've added you in the list.

**Comment by alanjhughes** [comment]
I can take docs/native-modules-android.md

**Comment by cortinico** [comment]
> I can take docs/native-modules-android.md

Added 👍

**Comment by cortinico** [comment]
Just a heads up for everyone involved in Kotlin migration, please make sure references to Java and java specific concepts in the body of the article is also adapted (in other words, converting snipptes might not be enough sometimes).

Example of what I'm referring to:
- https://github.com/facebook/react-native-website/pull/3028

**Comment by JazibJafri** [comment]
Hi, I would like to take on the `docs/custom-webview-android.md` and attempt to migrate it.

**Comment by cortinico** [comment]
> Hi, I would like to take on the `docs/custom-webview-android.md` and attempt to migrate it.

Assigned :+1:

**Comment by junaidn** [comment]
Hi, I would like to take the ` docs/communication-android.md` and try to migrate it.

**Comment by cortinico** [comment]
> Hi, I would like to take the ` docs/communication-android.md` and try to migrate it.

Assigned 👍

**Comment by RickardZrinski** [comment]
👋 I'm giving `docs/native-components-android.md` a go.

**Comment by cortinico** [comment]
> 👋 I'm giving `docs/native-components-android.md` a go.

Assigned

**Comment by EzequielDeOliveira** [comment]
Hi, I would like to take " docs/_integration-with-exisiting-apps-java.md"

**Comment by cortinico** [comment]
> Hi, I would like to take " docs/_integration-with-exisiting-apps-java.md"

Assigned 👍

**Comment by mbharadwajfb** [comment]
Hi, I would like to take docs/new-architecture-library-intro

**Comment by cortinico** [comment]
> Hi, I would like to take docs/new-architecture-library-intro

Assigned 👍

**Comment by aerrayes** [comment]
Hi, I would like to pick up  docs/new-architecture-library-android.md

**Comment by cortinico** [comment]
Assigned

**Comment by tusharvars** [comment]
I would like to pick new-architecture-app-modules-android

**Comment by cortinico** [comment]
> I would like to pick new-architecture-app-modules-android

Assigned 👍

**Comment by dakshbhardwaj** [comment]
Hi i would like to pick  `docs/new-architecture-app-renderer-android.md`

**Comment by cortinico** [comment]
> Hi i would like to pick `docs/new-architecture-app-renderer-android.md`

Assigned 👍

**Comment by cortinico** [comment]
Hey all,
I'm happy to share that our website is now fully bi-lingual with Kotlin & Java snippets!
Thank you all for the suppport

I'd like to personally thank @rokkoo @alanjhughes @mbharadwajfb @tusharvars @dakshbhardwaj @aerrayes  @jazibjafri @junaidn @RickardZrinski @EzequielDeOliveira for their contributions here!
