### ISSUE TITLE
Incorrect ActivityIndicator example

### ISSUE THREAD

**Issue by Naoto-Ida** [facebook/react-native-website#302]
Hi I noticed that the example shown in the simulator(?) on the [docs for ActivityIndicator](https://facebook.github.io/react-native/docs/activityindicator.html) shows an ActivityIndicator which is not true to the implementation.

How can I send you guys a PR for this?

**Comment by charpeni** [comment]
Thanks for the reporting.

You can contribute by reading the [Contributing section](https://github.com/facebook/react-native-website#contributing) and the docs for the `ActivityIndicator` can be edit here: https://github.com/facebook/react-native-website/blob/master/docs/activityindicator.md

**Comment by raajnadar** [comment]
This issue can be closed right??
