### ISSUE TITLE
Environment setup guide specifies Node 12 as minimum but the upgrade to 0.68 says Node 14 is minimum

### ISSUE THREAD

**Issue by Adnan-Bacic** [facebook/react-native-website#3053]
## What is the problem?

On the setup guide: https://reactnative.dev/docs/environment-setup

it says:

> If you have already installed Node on your system, make sure it is Node 12 or newer.

however, under the update for 0.68: https://reactnative.dev/blog/2022/03/30/version-068

it says:

> React Native has been updated to Node 16, the latest LTS. Since on CI we test for LTS and the previous LTS, this change means that users are now required to use a version of Node >= 14.

## How can we address it?

this seems like a simple change to just change the setup guide to specify Node 14.

## Why is it important?

so that people dont install old versions of Node, but use newer versions.

## Who needs this?

everyone

## When should this happen (use version numbers if needed)?

as it shouldt change anything for existing projects, it can be changed asap without waiting for next version of react-native.

**Comment by cortinico** [comment]
> this seems like a simple change to just change the setup guide to specify Node 16.

That's correct. We should mention that users should be on Node >= 14. Don't you mind sending a PR to udpate this in the Environment setup page (for `next` and for version `0.68`)?

**Comment by Adnan-Bacic** [comment]
something that i just noticed which i think could also be better is to streamline Node versions having to be manually updated.

the current guide for windows->android recommends using the LTS version of Node. while macOS->android, macOS->ios and expo all mention a specific version. in this case, 12.

to avoid having to update it manually whenever a new version is LTS, it could perhaps be better to just avoid writing a specific version and instead refer to the LTS version.

**Comment by Adnan-Bacic** [comment]
my first pr to this repo

https://github.com/facebook/react-native-website/pull/3064

how exciting

**Comment by cortinico** [comment]
> actually, if you support current LTS plus previous LTS, that should probably be written. but maybe its better to be explicit with the version, to avoid confusion?

I've answered you on the PR. Yes we do support both prev and current LTS, but I believe the docs should mention the number as well.

**Comment by cortinico** [comment]
Fixed by #3064
