### ISSUE TITLE
Hermes icon causes readability issues on smaller screen sizes

### ISSUE THREAD

**Issue by supmanyu** [facebook/react-native-website#3066]
## Description

When accessing the [hermes setup guide](https://reactnative.dev/docs/hermes), the hermes icon is abnormally large on mobile devices, making the text difficult to read. Attached screenshot below for reference.

![Screenshot_20220410-131946_Chrome.png](https://user-images.githubusercontent.com/13700827/162608446-ba89758c-b11e-4a10-9182-93011560322d.png)

Making the image full width for smaller screens will fix the alignment issues
![reactnative dev_docs_hermes(iPhone 12 Pro)](https://user-images.githubusercontent.com/13700827/162608878-e7716e76-9d16-4f70-9ee0-dc6dcee1c977.png)

## Documentation version
Version 0.68 + Next

**Comment by cortinico** [comment]
Thanks for reporting this @supmanyu

This should be a matter of updating the image style here to don't use absolute sizes:
https://github.com/facebook/react-native-website/blob/b616f13d1222da3d3b368aef5766ae76bd26ad93/docs/hermes.md?plain=1#L9

Do you want to take a stance at it?

**Comment by supmanyu** [comment]
Sure! I have created a PR mentioning this issue
