### ISSUE TITLE
"How to deploy to ios store" is incomplete

### ISSUE THREAD

**Issue by goldylucks** [facebook/react-native-website#3075]
## What is the problem?

on this page:
https://reactnative.dev/docs/publishing-to-app-store

the last step is "build" on xcode. however obviously this doesn't publish to the store, so what's the next step?
what exactly "build" does and how do we go from there?

## How can we address it?

complete the documentation with the next steps

## Why is it important?

w/o publishing to the store this project doesn't do much ;)

## Who needs this?

everybody

## When should this happen (use version numbers if needed)?

ASAP

**Comment by cortinico** [comment]
> the last step is "build" on xcode. however obviously this doesn't publish to the store, so what's the next step?
> what exactly "build" does and how do we go from there?

Correct. Ideally we could add a couple of instructions on where to get the artifacts after it's built and where to upload it to the store. 

This is up for grab if someone went through this process in the past and is willing to contribute to the website 👍

**Comment by Pranav-yadav** [comment]
Thanks @goldylucks for reporting 😇
Since this issue was **_fixed_** by #3077, it should be closed now 👍

Cc: @Simek
