### ISSUE TITLE
Update cocoapods install instructions for M1 Macs

### ISSUE THREAD

**Issue by wqueree** [facebook/react-native-website#3083]
## Description

`cocoapods` should be installed through homebrew with `node` and `watchman`.

## What is the problem?

The existing workaround published on the website is unnecessarily convoluted and often fails.

## How can we address it?

In the documentation, replace the following:

```bash
sudo arch -x86_64 gem install ffi
arch -x86_64 pod install
```

with

```bash
brew install node
brew install watchman
brew install cocoapods
```

## Why is it important?

The additional dependence on `arch -x86_64` adds unnecessary complexity to the environment.

## Who needs this?

- iOS Developers
- Beginners

## When should this happen (use version numbers if needed)?

When setting up a development environment for the first time.

**Comment by luism3861** [comment]
Hi @wqueree i created a PR but it still open PR #3074
