### ISSUE TITLE
Wrong suggested Android System Image for Emulation

### ISSUE THREAD

**Issue by jarno018** [facebook/react-native-website#3088]
## Description

While setting up my Android emulator in Android Studio, I noticed there were no System Images with an API level of 30 named 'Q'. Altough the "setting up" page suggested the before mentioned System Image (Q API 30), according to https://apilevels.com/, this image doesn't exists with that API level.

## Possible solution
I Found that the emulator and react-native/Metro both seem to work with System Image R (API level 31). Maybe this Image can be suggested in the docs ?

## Documentation version

This report was written for documentation on https://reactnative.dev/docs/environment-setup, version 0.68.

**Comment by cortinico** [comment]
Yes that's doable. Suggesting API lvl 31 (S) it's safe. Don't you mind updating the docs?
