### ISSUE TITLE
Update ANDROID_SDK_ROOT to ANDROID_HOME

### ISSUE THREAD

**Issue by leotm** [facebook/react-native-website#3118]
## Description

Context
- https://github.com/facebook/react-native-website/pull/2590

On 23 March Google deprecated `ANDROID_SDK_ROOT` in favour of `ANDROID_HOME`

So we need to basically revert delicately
- https://github.com/facebook/react-native-website/pull/2991

I'll create a PR with relevant updates

Changes appear applicable to all <s>3 platforms</s> 2 platforms
- <s>`windows`</s> we don't mention either in our windows guide
- `macosx`
- `linux`

## Documentation version

- 0.68
- next

**Comment by cortinico** [comment]
> I'll create a PR with relevant updates

@leotm Can you sand over the PR?

**Comment by leotm** [comment]
sry lost track of this ^ sure done
- https://github.com/facebook/react-native-website/pull/3266
