### ISSUE TITLE
Migrate to Google Analytics 4

### ISSUE THREAD

**Issue by lunaleaps** [facebook/react-native-website#3142]
## Description

Google Analytics is sunsetting older versions than 4 https://blog.google/products/marketingplatform/analytics/prepare-for-future-with-google-analytics-4/ by July. 2023.

From [similar issue in docusaurus ](https://github.com/facebook/docusaurus/issues/7221) from @slorber
> Analytics data will not be migrated to the new system

> For sites that want to migrate to Analytics 4 and keep historical data, they can run both analytics side-by-side so when the former analytics system is shut down, they have enough historical data

> For these reasons, we should not wait until the final deadline to support Google Analytics 4 and allow sites to seamlessly/incrementally migrate to Analytics 4.

## Task
Can someone take point on figuring out how to get us ready for GA4?

**Comment by hainguyenphc** [comment]
Hello @lunaleaps Do you mind if I grab this issue? I am looking for a good-first-issue type of issues to kick started :)

**Comment by lunaleaps** [comment]
@hainguyenphc Yes please do!

**Comment by slorber** [comment]
FYI it has been reported on Docusaurus that our existing gtag plutin works with GA4

So this is not something that could be hand-off to an external contributor and is more an admin task: you have to create the GA4 account. I don't know who at Meta is responsible for the GA accounts.

**Comment by lunaleaps** [comment]
I see, I can take a look
