### ISSUE TITLE
Docs: Highlights of 0.69 section link is pointing to 0.68 version of React-Native

### ISSUE THREAD

**Issue by DemonDaddy22** [facebook/react-native-website#3179]
## Description

The website page of [React-Native v0.69](https://reactnative.dev/blog/2022/06/21/version-069) has a section link that is meant to take the user to highlights of 0.69, but it points to highlights of 0.68, thus not scrolling to the desired section.
<img width="1728" alt="Screenshot 2022-06-26 at 9 53 57 AM" src="https://user-images.githubusercontent.com/39908472/175799306-bafd6bb1-31b0-4ceb-a107-2ed7178f349c.png">

## Documentation version

React-Native version -> 0.69.

Will create a PR to fix the same.

**Comment by Simek** [comment]
Nice catch, thank you for the report @DemonDaddy22! 👍
