### ISSUE TITLE
Text Style Prop fontSize lacks documentation

### ISSUE THREAD

**Issue by tibbe** [facebook/react-native-website#3186]
## Description

The [documentation of the `fontSize` property](https://reactnative.dev/docs/text-style-props#fontsize) provides very little documentation (it literally only says: "number"), given how complex it is to navigate the space of converting a design (in e.g. Figma) to React Native and have it match the intention. It would be great if this was fleshed out. For example, is the `fontSize` passed as is to underlying native APIs unchanged? Is it scaled somehow? Is it in DPI?

## Documentation version

0.69

**Comment by agrittiwari** [comment]
It is in DPI. I also had limited clarity for some time coming from web. It is relative to screen size to make text layout screensize agnostic, I guess.
