### ISSUE TITLE
Convert react-native cli project to expo cli project

### ISSUE THREAD

**Issue by ubaid-wp** [facebook/react-native-website#3195]
There is any way to convert my react-native cli project into expo cli project ? I want to eject my react-native project into expo cli, like epxo eject.

**Comment by cortinico** [comment]
This issue tracker is for the reactnative.dev website. You should ask your questions to the Expo CLI tracker: https://github.com/expo/expo-cli

**Comment by Simek** [comment]
@ubaid-wp Just FYI, we do not accept questions as an issue on the repos, but you can ask the community on https://chat.expo.dev or on Expo forums.

However, TL:DR, there is no tool to migrate manually, but we have a few step by step guides in the docs, to help with the process:
* https://docs.expo.dev/bare/existing-apps/
