### ISSUE TITLE
terminology

### ISSUE THREAD

**Issue by bobOnGitHub** [facebook/react-native-website#3213]
## Description

Please refrain from using, and remove the word "truth" in your documentation -  It makes my blood boil and I'm sure I'm not alone here.
I have to read technical documentation and every time I see this "[single] source of truth" I want to vomit added to which it is entirely redundant eg.

"uses JavaScript component declarations as source of truth to generate C++ structs"

"uses JavaScript component declarations as source to generate C++ structs"

The latter makes it perfectly clear what is going on.

Also where "single source of truth" is used - usually for data - you can say "primary data source" or "original" if necessary.

## Documentation version

From the page https://reactnative.dev/architecture/fabric-renderer as at 17/7/22 17:40 BST

"uses JavaScript component declarations as source of truth to generate C++ structs"

**Comment by cortinico** [comment]
Closing/Locking due to violation of our Code of Conduct:
https://github.com/facebook/react-native-website/blob/c429e4996599b0d07881945ce9876e30fbf9d5b7/CODE_OF_CONDUCT.md
