### ISSUE TITLE
"Enabling TurboModule on iOS" section is outdated

### ISSUE THREAD

**Issue by dminkovsky** [facebook/react-native-website#3217]
## Description

The guide at https://github.com/facebook/react-native-website/blob/e1e417789654c4f9a2abe6cb8bf49cec1b2767d0/docs/new-architecture-app-modules-ios.md is outdated. It seems like TurboModules is enabled by default in 0.69, and the contents of this guide are now in [the code](https://github.com/facebook/react-native/blob/8bd3edec88148d0ab1f225d2119435681fbbba33/React/AppSetup/RCTAppSetupUtils.mm). If this understanding is correct, I think it would be better to make that clear in the docs.

## Documentation version

latest release: 0.69.1.
`main` at the time of this writing: e1e417789654c4f9a2abe6cb8bf49cec1b2767d0.

**Comment by cortinico** [comment]
> It seems like TurboModules is enabled by default in 0.69

Nope that's not the case. TurboModules are part of the New Architecture, which is not enabled by default:

https://github.com/facebook/react-native/blob/8a33b75f55ba429e9e7a897179557aa8bb49ab35/template/android/gradle.properties#L35-L40

I believe you're confusing the Hermes engine with the New Architecture which are two distinct things.
