### ISSUE TITLE
[DEPRECATED] "npx react-native link" is not a valid command anymore! 

### ISSUE THREAD

**Issue by runtothedoor** [facebook/react-native-website#3260]
## Description
<p>Documentation has deprecated instructions about <b>react-native link<b/> command</p>

<img width="1000px" src="https://user-images.githubusercontent.com/28831375/184395727-77aa5681-f64a-4ace-9780-662934a1b156.png"/>

<img width="600px" src="https://user-images.githubusercontent.com/28831375/184396222-d0e65664-4c66-4c5f-8978-1b891100e977.png"/>

## Documentation version

0.69, Next

**Comment by cortinico** [comment]
@thymikee can you take this one?

**Comment by thymikee** [comment]
@cortinico https://github.com/facebook/react-native-website/pull/3269
