### ISSUE TITLE
--version flag not working when creating a new React-Native project

### ISSUE THREAD

**Issue by charlieswing** [facebook/react-native-website#3265]
I am following the Environment Setup documentation in the latest version of React Native to create a new React Native CLI project, but using the --version flag to use an older version of React Native (0.63.0).

_npx react-native init AwesomeProject --version 0.63.0_

When I run this command, I instead get the following message in Terminal:

_Need to install the following packages:
  react-native@0.69.4
Ok to proceed? (y)_

Has anyone else run into this? Am I doing something wrong?

**Comment by Simek** [comment]
Hello @charlieswing, the command works for me as expected. Which version of Node and npm do you use?

![Screenshot 2022-08-16 152607](https://user-images.githubusercontent.com/719641/184891483-8a6cda48-cfaf-4604-8a4e-c9c080a42fc5.png)

Also, all issue with CLI should be reported and handled in its repo: https://github.com/react-native-community/cli

**Comment by cortinico** [comment]
> Need to install the following packages:
> react-native@0.69.4
> Ok to proceed? (y)

Although you see this message, you're going to effectively use the version you requested. `npx` needs to download a version of React Native for the `init` command to run, and in this case is suggesting you that you'll end up using the latest.

The project that will be created will use the version you requested though
