### ISSUE TITLE
PermissionsAndroid issue 0.70

### ISSUE THREAD

**Issue by alihussnain-git** [facebook/react-native-website#3331]
## Description

In the latest documentation of [PermissionsAndroid](https://reactnative.dev/docs/permissionsandroid), it is written that latest push [notifications](https://reactnative.dev/docs/permissionsandroid#:~:text=%3A%20%27android.permission.-,POST_NOTIFICATIONS,-%27) permission for android is supported but It is still not available in 0.70.1 version of react native. I have tried it by creating a new project as well but android.permission.POST_NOTIFICATIONS is till not available.
## Documentation version

0.70

**Comment by cortinico** [comment]
We actually introduced in https://github.com/facebook/react-native/pull/33471 which is included in React Native 0.70.x

**Comment by alihussnain-git** [comment]
I have created a new project to test this one, but notification permission is not being show in 0.70.1
<img width="606" alt="Screenshot 2022-09-20 at 15 07 29" src="https://user-images.githubusercontent.com/58841397/191230842-81847984-c06a-448d-8ad7-61025cf1cf5f.png">

**Comment by alihussnain-git** [comment]
> Closing as I believe this is not related to the website but it's related to the version of `@types/react-native` you're using: [facebook/react-native#34731 (comment)](https://github.com/facebook/react-native/issues/34731#issuecomment-1252518189)

yep you were write, notifications permission type is missing here, the snapshot was from there
