### ISSUE TITLE
Changelog does not note when React upgraded from 17 -> 18

### ISSUE THREAD

**Issue by mljlynch** [facebook/react-native-website#3339]
## Description

In [React Native Changelog](https://github.com/facebook/react-native/blob/main/CHANGELOG.md#v0640), there is a note that React is upgraded to version 16, but there is no note when this happens in version 0.69 (I believe). 

> Upgrade to React 17 ([24bca492c3](https://github.com/facebook/react-native/commit/24bca492c349ab90d40f9444df0f477145a4c311) by [@rickhanlonii](https://github.com/rickhanlonii))

This would be a helpful dependency to call out since MANY packages depend on a specific react version.

## Documentation version

https://github.com/facebook/react-native/blob/main/CHANGELOG.md#v0640

**Comment by cortinico** [comment]
This was clearly state in the release notes for 0.69:
https://reactnative.dev/blog/2022/06/21/version-069#react-18

If you wish, you can add the line:

As for the note in the changelog, here it is https://github.com/facebook/react-native/pull/34774

**Comment by mljlynch** [comment]
Thank you!
