### ISSUE TITLE
Wrong Documentation in Turbo Native Modules

### ISSUE THREAD

**Issue by callmemonky** [facebook/react-native-website#3362]
I tried following Turbo Native Modules example i.e https://reactnative.dev/docs/the-new-architecture/pillars-turbomodules#write-the-native-android-code but it didn't work.

Few inconsistencies

1. 
<img width="692" alt="image" src="https://user-images.githubusercontent.com/25193916/194233565-f405e413-0673-4c21-9b02-c9e8f578e873.png">
Here ^ it mentions we need to create RTNCalculatorModule.java & RTNCalculatorPackage.java

But in the final folder structure just below it, it mentions 'CalculatorModule.java' & 'CalculatorPackage.java'

<img width="838" alt="image" src="https://user-images.githubusercontent.com/25193916/194233707-ac206319-35c2-42a6-a548-23e3f3b0940a.png">

Also, right below the above modules we have example of  'CalculatorModule.java' & 'CalculatorPackage.java'

<img width="879" alt="image" src="https://user-images.githubusercontent.com/25193916/194233781-e86157f1-99e3-4014-a5c5-c529952240f4.png">
<img width="879" alt="image" src="https://user-images.githubusercontent.com/25193916/194233782-7d51ffb4-0317-48b2-9880-a6a4e58bbbdd.png">

**Comment by callmemonky** [comment]
Issue i am facing while building the app.

<img width="1415" alt="image" src="https://user-images.githubusercontent.com/25193916/194234245-7a0debba-26f4-427d-aa00-473a039f4c4f.png">

**Comment by cortinico** [comment]
Thanks for mentioning this @callmemonky
You're right and I already fixed this yesterday, but only on the `next` version of the website. You can find the updated documentation here:

https://reactnative.dev/docs/next/the-new-architecture/pillars-turbomodules#write-the-native-android-code
