### ISSUE TITLE
TextInput keyboardType "visual guide" is woefully outdated (Android v8)

### ISSUE THREAD

**Issue by nmschulte-aviture** [facebook/react-native-website#3375]
The "visual guide" referenced on the `TextInput` documentation is a few years out of date, and seems to no longer represent how this option behaves on recent versions of the supported platforms.  Particularly, the reference is for Android v8, though v10, v11, v12 and v13 are popular now.

https://reactnative.dev/docs/textinput#keyboardtype
> See screenshots of all the types [here](http://lefkowitz.me/2018/04/30/visual-guide-to-react-native-textinput-keyboardtype-options/).

Particularly, it seems that on some devices, the `keyboardType='numeric'` doesn't provide a minus/negative key, and it's not clear how to properly resolve this while attempting to support multiple (or even the latest) version(s).

**Comment by cortinico** [comment]
Yup you're right. We should either remove this link or find a more up to date one.

**Comment by nmschulte-aviture** [comment]
no robot
