### ISSUE TITLE
Mobile display screen on the React-Native tutorial site doesn't display certain images

### ISSUE THREAD

**Issue by carpben** [facebook/react-native-website#338]
Mobile display doesn't display certain images. Example: 
https://facebook.github.io/react-native/docs/using-a-scrollview.html  
`<Image source={require('/react-native/img/favicon.png')} /> `
![image](https://user-images.githubusercontent.com/13496178/39564777-3ac09b4a-4ebe-11e8-869d-38ea45fea80d.png)

**Comment by parammittal16** [comment]
Hi @carpben I want to work on this issue.

**Comment by Simek** [comment]
Thank you for the report! I'm happy to say that this issue has been fixed a while ago.
