### ISSUE TITLE
RNCProgressViewManager.java:9: 错误: 程序包com.facebook.react.uimanager不存在

### ISSUE THREAD

**Issue by zhaolong-benhu** [facebook/react-native-website#3413]
android studio 构建错误: 程序包com.facebook.react.uimanager不存在
import com.facebook.react.uimanager.SimpleViewManager;
![image](https://user-images.githubusercontent.com/17918972/201041310-81a7f169-aefe-48ce-9a27-e8ff4c84b21d.png)

                                   ^

**Comment by zhaolong-benhu** [comment]
有没有人遇到过这个问题 请问怎么解决？

**Comment by cortinico** [comment]
Hi,
In this issue tracker, we accept only issues that are in English.
I'm closing this for now, please consider translating it to English and reopening it.
Thanks.
