### ISSUE TITLE
Unable to create an event emitter using Codegen

### ISSUE THREAD

**Issue by friyiajr** [facebook/react-native-website#3417]
## Description

I am trying to create a library using TurboModules that can handle events emitted at a random pace. I have events from a Bluetooth Heart Rate Monitor that can come in at a random pace. Using the old architecture I was able to use RCTEventEmitter but there seems to be no equivalent in the new arch. My codegen interface looks like this.

```
import type { TurboModule } from 'react-native';
import { TurboModuleRegistry } from 'react-native';
import type { DirectEventHandler } from 'react-native/Libraries/Types/CodegenTypes';

export interface Spec extends TurboModule {
  multiply(a: number, b: number): number;
  add(a: number, b: number): number;
  randomEvent?: DirectEventHandler<number>;
}

export default TurboModuleRegistry.getEnforcing<Spec>('RtmPedometer');
```

But trying to run Codegen when I have `DirectEventHandler` written here just creates errors. If I remove it everything works great. 

If there is another way to add event emitters under the new arch please let me know but it doesn't seem to be documented anywhere

The legacy documentation actually outlines how to do this really well https://reactnative.dev/docs/native-modules-android#sending-events-to-javascript . I don't know why the new arch docs don't explain this at all. It's pretty important to native module integrations.

**UPDATE:** I tried to use `RCTResponseSenderBlock` instead in the hope I could call a callback whenever a new event took place. Unfortunately it crashes the app and says I cannot call these more then once. There doesn't seem to be a way to manage events anywhere in the documentation either through event emitting or through callbacks

## Documentation version
Version: 0.70.0
Link to Resource: https://reactnative.dev/docs/next/new-architecture-library-intro#codegen-helper-types

**Comment by mike7866** [comment]
Ok

**Comment by cortinico** [comment]
Related to https://github.com/facebook/react-native/issues/35488
