### ISSUE TITLE
Question about invalidate code in RCTRootContentView

### ISSUE THREAD

**Issue by PuffLady** [facebook/react-native-website#3443]
## Description

Why do you write this code, what problem is it to solve, can you please let me know, I will be appreciate it

- (void)invalidate
{
  if (self.userInteractionEnabled) { //  this line
    self.userInteractionEnabled = NO; //  this line
    [(RCTRootView *)self.superview contentViewInvalidated]; //  and this line

    [_bridge enqueueJSCall:@"AppRegistry"
                    method:@"unmountApplicationComponentAtRootTag"
                      args:@[ self.reactTag ]
                completion:NULL];
  }
}

## Documentation version
0.70.6

**Comment by cortinico** [comment]
Closing as this is a question and should be moved to StackOverflow. This is the issue tracker for the React Native Repo
