### ISSUE TITLE
MacOS build optimization - incorrect ccache setup instructions

### ISSUE THREAD

**Issue by Shakahs** [facebook/react-native-website#3491]
## Description

**Performance->Speeding up your Build Phase** suggests installing ccache for build caching, but the MacOS setup instructions are incorrect. MacOS does not utilize the user's $PATH variable when launching Xcode or other desktop applications, so Xcode will not see the ccache executables symlinked into /usr/local/bin.

It is necessary to change the path MacOS provides applications. This command will copy the user's $PATH to the MacOS application launch $PATH, it requires a reboot to take effect:
`sudo launchctl config user path $PATH`

At this point Xcode will use ccache for some build work. For full utilization it is necessary to disable an Xcode build system integrity setting. This must be done on every boot because the updated value does not persist:
`defaults write com.apple.dt.Xcode UseSanitizedBuildSystemEnvironment -bool NO`

The actual path Xcode is using can be checked this way:
`sudo launchctl procinfo <XCODE PID> | grep -i path`

Additionally, here is the ccache configuration file needed by Xcode:
```
shak@Shaks-Mac-Studio ~ % cat ~/Library/preferences/ccache/ccache.conf
sloppiness=clang_index_store,file_stat_matches,include_file_ctime,include_file_mtime,ivfsoverlay,pch_defines,modules,system_headers,time_macros
file_clone = true  
depend_mode = true
inode_cache = true
```

I am using Xcode 14.2 with MacOS 12.6.2 (Monterey), on Apple Silicon with Xcode running natively. With this configuration and a clean Xcode build folder a debug build of my app takes 30 seconds, without ccache it takes 2 minutes. 

## Documentation version
0.69, 0.70

**Comment by cortinico** [comment]
> but the MacOS setup instructions are incorrect

IMHO we should potentially just remove the setup instructions for `ccache`. We can't explain how to install every tool inside the reactnative.dev website and we should instead link to a realiable guide/source.

**Comment by Shakahs** [comment]
"React Native" is nothing but a toolchain composed entirely of other tools that we need to know of and manage. 
reactnative.dev _is_ the official documentation, it should be the most reliable / thorough source. 
I provided the entire solution already.

**Comment by cortinico** [comment]
> "React Native" is nothing but a toolchain composed entirely of other tools that we need to know of and manage.

Exactly for this point, we should guide you to the best guide of each specific toolchain. We can't re-explain every specific tool and edge case as we'll be duplicating the work of every tool we depedn on.

**Comment by cortinico** [comment]
> > "React Native" is nothing but a toolchain composed entirely of other tools that we need to know of and manage.
> 
> Exactly for this point, we should guide you to the best guide of each specific toolchain. We can't re-explain every specific tool and edge case as we'll be duplicating the work of every tool we depedn on.

Closing as of this

**Comment by Shakahs** [comment]
@cortinico so you're not going to fix the invalid information, or remove the invalid information, you're just going to close this ticket as "completed" without doing anything. Got it.
