### ISSUE TITLE
Environment setup docs point to version of Ruby in non-released source, causing errors on `react-native init`

### ISSUE THREAD

**Issue by AlanSl** [facebook/react-native-website#3501]
## Description

The documentation ["Environment setup"](https://reactnative.dev/docs/environment-setup) page includes this:

> React Native uses [this version](https://github.com/facebook/react-native/blob/main/template/_ruby-version) of Ruby. You can also find which version your specific project needs in the .ruby-version file at root of your RN project.

That link points to the ruby version in the `main` branch, not the ruby version in the actual published release the docs are for.

So, right now, that link says to use Ruby version `2.7.6`, because that's the version in the latest source `main` branch and current `rc` release. But, these are also the docs for the 0.70 stable release, and if you follow them exactly, you'll get this error on `npx react-native init`:

> ✖ Installing Bundler
> error Your Ruby version is 2.7.6, but your Gemfile specified 2.7.5

...because the 0.70 release expects `2.7.5`.

(doing `init` with `--version 0.71.0-rc.5` and Ruby 2.7.6 works)

Suggested fixes:

- Just state the expected Ruby version in the documentation for each release
- Link to `...react-native/blob/${branch}/template/_ruby-version` where `branch` is the appropriate branch for this version (but that might also have issues with not-yet-released changes to rc branches?)

## Documentation version

- `0.70`

**Comment by cortinico** [comment]
> * Link to `...react-native/blob/${branch}/template/_ruby-version` where `branch` is the appropriate branch for this version (but that might also have issues with not-yet-released changes to rc branches?)

Yeah this would be preferred I guess. The problem is that we'll most likely forget to update the link after every version

**Comment by AlanSl** [comment]
Can you access the target RN version as a variable in the docs template? If so, you could generate the branch name from the version number.

**Comment by AlanSl** [comment]
It looks like this change got made, thanks!

I see that now:

- [The current (0.71) docs](https://reactnative.dev/docs/environment-setup?guide=native) link to the [0.71.3 Ruby version](https://github.com/facebook/react-native/blob/v0.71.3/.ruby-version)
- [The 0.70 docs](https://reactnative.dev/docs/0.70/environment-setup?guide=native) link to the [0.70.7 Ruby version](https://github.com/facebook/react-native/blob/v0.70.7/.ruby-version)
