### ISSUE TITLE
Sending Events to JavaScript in https://reactnative.dev/docs/native-modules-android

### ISSUE THREAD

**Issue by Productivix** [facebook/react-native-website#3504]
## Description

I am a "recent" (1 year old) React-Native developer , so I do not understand old syntax. Besides, the old React Native syntax in this § gives me warning.

I  developed a native module that runs on special terminals, so publishing the code will not be useful for you and easy to test also. The Java code is identical and is OK (maybe Kotlin, I did not test)
It is about the React Native code - I make a precision : I have made that on a fresh 0.70.6 React Native app with only the following packages : (so NO "reanimated" that may be involved as I saw on some forums), and  ""react-native-device-info" is NOT involved in that part.

```
"dependencies": {
    "react": "18.1.0",
    "react-native": "0.70.6",
    "react-native-device-info": "^10.3.0"
  },
```
So for the React-Native code, I put the following code , to replace the old syntax : 
```
import { NativeEventEmitter, NativeModules } from 'react-native';
...
useEffect(() => {
     const eventEmitter = new NativeEventEmitter(NativeModules.ToastExample);
    //treat the message return :
    let eventListener = eventEmitter.addListener('EventReminder', event => {
      console.log('the bundle:', event); // the bundle sent by module
    });

    //cut he listening at unmounted
    return () => {
      eventListener.remove();
    };
  }, []);
```

and it displays right the console.log datas but gives the warning message at start : 
```
WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method. 
    at App (http ....
```
This warning desapears at release compilation package.

So this code runs correct. Can we work together on correcting that code on the online doc to improve the tool ?
I remain at your disposal to test your suggestions.

## Documentation versions : 
0.70 and Next ,( may be before, but no interest..)

**Comment by Productivix** [comment]
hi, no news how to update teh online doc  ? may be not the right place ? thks

**Comment by cortinico** [comment]
> hi, no news how to update teh online doc ? may be not the right place ? @cortinico : hat do you think ? thank you

Can you clarify what's your question? Are you asking how to update the website pages?

**Comment by Productivix** [comment]
hi Nicolas, yes I worked here on a proposition to update the website : may be I did not understand the exact mode : how can we copy and validate that work please ?

**Comment by cortinico** [comment]
> WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method. 
>     at App (http ....

This issue is caused by `react-native-device-info`:
https://github.com/react-native-device-info/react-native-device-info/issues/1288

**Comment by Productivix** [comment]
hi Nicolas, (always your habit to shut the door at developers face. = close issue.) 
but :
 1/ I do not have problems with react-native-device-info on other projects , it is may be react-native-device-info + NativeEventEmitter that induce a warning (that desapear at release compilation)
2/ My topic was NOT the warning I do care, it is HOW to modify the online documentation with my code proposal ?
Thank you

**Comment by cortinico** [comment]
> 2/ My topic was NOT the warning I do care, it is HOW to modify the online documentation with my code proposal ?

My apologize but I'm having a hard time reading through this issue to fully understand what is the request.

You can edit the page by submitting a pull request for this file:
https://github.com/facebook/react-native-website/blob/main/docs/native-modules-android.md

**Comment by Productivix** [comment]
ok thanks Nicolas, I will do that

**Comment by Productivix** [comment]
hi @cortinico , I have done the PR :  https://github.com/facebook/react-native-website/pull/3557 , my License Agreement is signed but still blocked : can you please see 
I  am new in that .  Thks al lot
