### ISSUE TITLE
Different signatures of ReactNativeHost/DefaultReactNativeHost from upgrade helper and documentation 0.71

### ISSUE THREAD

**Issue by dnlbox** [facebook/react-native-website#3530]
## Description

In the Upgrade Helper from 0.70.6 to 0.71.0 (and 0.71.1) [here](https://react-native-community.github.io/upgrade-helper/?from=0.70.6&to=0.71.1) it has information to change the `MainApplication.java` from `ReactNativeHost` to `DefaultReactNativeHost`: 

```
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint;
import com.facebook.react.defaults.DefaultReactNativeHost;
import com.facebook.soloader.SoLoader;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost =
      new DefaultReactNativeHost(this) {
        @Override
        public boolean getUseDeveloperSupport() {
          return BuildConfig.DEBUG;
        }
```

There are points in the documentation that mention `ReactNativeHost` but not as `DefaultReactNativeHost` that creates confusion.
- in integration with an Android Fragment [here](https://reactnative.dev/docs/integration-with-android-fragment#2-integrating-your-app-with-a-react-native-fragment)
- in Android Native Modules [here](https://reactnative.dev/docs/native-modules-android#register-the-module-android-specific)

I'll be glad to change if confirmed that `DefaultReactNativeHost` is the correct way to setup.

## Documentation version

`0.71`

**Comment by cortinico** [comment]
You're right thanks for spotting, here the fix: https://github.com/facebook/react-native-website/pull/3543

They're equivalent, but it's probably better to use `DefaultReactNativeHost` as your concrete class.
