### ISSUE TITLE
Integration with an Android Fragment example - errors

### ISSUE THREAD

**Issue by anonym24** [facebook/react-native-website#3549]
So I checked this docs https://reactnative.dev/docs/native-components-android#integration-with-an-android-fragment-example

https://github.com/facebook/react-native-website/blob/main/docs/native-components-android.md?plain=1#L818
It says to create file `MyViewManager.tsx`

https://github.com/facebook/react-native-website/blob/c132ee32dc0554740d01a0f7b981554ca7ec950c/docs/native-components-android.md?plain=1#L835
but here it tries to import some `my-view-manager`, what is that? so I replaced it with `MyViewManager` (I'm not sure) but still when I run the app I get the errors:

```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
Check the render method of `HelloWorldApp`.
    in HelloWorldApp
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in ReactProjectApp(RootComponent)
 ERROR  Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

Also there are three dots at https://github.com/facebook/react-native-website/blob/c132ee32dc0554740d01a0f7b981554ca7ec950c/docs/native-components-android.md?plain=1#L751
I just added the missing method like this:

    override fun createNativeModules(reactContext: ReactApplicationContext): List<NativeModule> {
        return Collections.emptyList()
    }

But not sure if it's correct...

I'm a new to React Native but tried docs, copied the exact same code to my project and it didn't work

In my `App.js` I tried to use it like this:

    import React from 'react';
    import {Text, View} from 'react-native';
    import MyView from './MyView';
    
    const HelloWorldApp = () => {
      return (
        <View
          style={{
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
          }}>
           <MyView style={{ flex: 1, width: '100%', height: '100%' }} /> 
        </View>
      );
    };
    export default HelloWorldApp;

What can be wrong?

If I remove `<MyView style={{ flex: 1, width: '100%', height: '100%' }} />` then there are not errors, so it's the issue of the code from the docs

**Comment by anonym24** [comment]
fixed by `import {MyView} from './MyView';` :)
but anyway should `./my-view-manager` be changed to `./MyViewManager`

**Comment by Simek** [comment]
Hello @anonym24 would you like to propose the change for the incorrect path you have mentioned?
