### ISSUE TITLE
Specify somewhere that React Native doesn't support Node.js v18 in stable yet!!!

### ISSUE THREAD

**Issue by crock** [facebook/react-native-website#3573]
I can make the change if you tell me where it should go, but my recommendation is somewhere noticeable at the top of the installation section.

I wasted hours trying to figure out why `npx react-native init` was failing on Node 18, but as soon as I switched to Node 16, it worked as normal.

**Comment by cortinico** [comment]
Our CI runs on Node 18:
https://github.com/facebook/react-native/blob/1d5103227851ab92de889d5e7e910393b5d8743a/.circleci/config.yml#L50

I also tested `npx react-native init` on Node 18 and I was able to run an app without any problem. Please post on the CLI repo https://github.com/react-native-community/cli/issues as I believe you might have an issue with your local setup.
