### ISSUE TITLE
How to Contribute Guide: Missing information on how to test local changes

### ISSUE THREAD

**Issue by MarkOSullivan94** [facebook/react-native-website#362]
Spent a bit of time reading the [How to Contribute guide ](https://facebook.github.io/react-native/docs/contributing.html)and I couldn't find information on how to run local changes to the React Native project on my existing React Native projects.

Would love it if someone could do a detailed explanation within the guide along with how to run the tests on Circle CI / any other CI services which is used by the React Native project.

**Comment by charpeni** [comment]
Thanks for bringing this up.

Is this what you're looking for? https://facebook.github.io/react-native/docs/building-from-source.html

**Comment by MarkOSullivan94** [comment]
Yep! That's perfect.

Would it be possible for that link to be included in the How to Contribute Guide @charpeni?

**Comment by charpeni** [comment]
Sure, are you up to do the PR?

**Comment by charpeni** [comment]
Thank you, your contributions are really appreciated.
