### ISSUE TITLE
docs broken

### ISSUE THREAD

**Issue by dgamma3** [facebook/react-native-website#3640]
## Description

docs broken

https://reactnative.dev/docs/getting-started
<img width="1487" alt="image" src="https://user-images.githubusercontent.com/1439000/227074551-cb021506-d905-4895-b638-eceaf4c56751.png">

**Comment by Simek** [comment]
Hello @dgamma3, I cannot reproduce the problem on my side. 

Try to disable your browsers extensions or visit the page in incognito mode, if example will be visible after performing the mentioned steps, it means that one of your extensions is blocking the content.

**Comment by dgamma3** [comment]
ahh, it was the companies vpn!

thanks so much
