### ISSUE TITLE
Update Docs Xcode - installing-an-ios-simulator-in-xcode

### ISSUE THREAD

**Issue by Sunset-Kim** [facebook/react-native-website#3644]
## Description

[installing-an-ios-simulator-in-xcode](https://reactnative.dev/docs/environment-setup?platform=ios#installing-an-ios-simulator-in-xcode)

I am using IOS 13.2 and am reporting a different way to install the simulator in Xcode.
There doesn't seem to be a tab called Preferences - Components anymore.
I'm attaching a screenshot of my workaround instead.

![스크린샷 2023-03-24 오전 8 46 49](https://user-images.githubusercontent.com/77092632/227390893-06861d78-13e7-495a-aaba-5ecc0c171a63.png)

<img width="847" alt="스크린샷 2023-03-24 오전 8 47 14" src="https://user-images.githubusercontent.com/77092632/227390908-7f58345e-3dd9-426b-a87a-3e35856c2020.png">

<img width="647" alt="스크린샷 2023-03-24 오전 8 47 24" src="https://user-images.githubusercontent.com/77092632/227390963-44c94af4-25ee-4e9e-832d-6006a74174f8.png">

## Documentation version
next  , 0.71

**Comment by cortinico** [comment]
> There doesn't seem to be a tab called Preferences - Components anymore.

THanks for spotting this, feel free to send over a PR with the fix 🙏

**Comment by jobpaardekooper** [comment]
The documentation has been updated to reflect those changes by #3738 and is now correct. This issue can be closed as far as I know.
