### ISSUE TITLE
Command Need to be complated at  Guides >Workflow > using Typescript

### ISSUE THREAD

**Issue by MeetBhingradiya** [facebook/react-native-website#3690]
## Description

GO -> https://reactnative.dev/docs/typescript#getting-started-with-typescript
You can see command is not fully complated.

```
npx create-expo-app --template
```

instead of

```
npx create-expo-app -t expo-template-blank-typescript
```

Note :  Command is Updated - @cortinico

**Comment by cortinico** [comment]
@Simek Can you cross check here? I believe the correct command would be:
```
npx create-expo-app -t expo-template-blank-typescript
```

**Comment by Simek** [comment]
I would lean into empty param (`npx create-expo-app --template`) since then user can select one of two TS templates available:

<img width="387" alt="Screenshot 2023-04-19 125258" src="https://user-images.githubusercontent.com/719641/233053395-38cc736a-8320-4b91-94c3-053fbdeaf9ea.png">

**Comment by cortinico** [comment]
Oh TIL. I'll leave this to you @Simek to decide then 👍
