### ISSUE TITLE
React Native and tooling: a round up

### ISSUE THREAD

**Issue by kelset** [facebook/react-native-website#370]
I feel like (from looking at the issues that get open constantly) there is an overall incomprehension/misunderstanding of how many moving parts are interconnected to make a React Native app project run.

In particular, there are two kinds of issues I see appearing every now and then:

- the **FOMO effect**: people see a new version of a tool, install it right away without any necessary reason (but simply because it's the latest) and then flip tables because their app breaks.
example: https://github.com/facebook/react-native/issues/19321

- the **Overlord rollout**: some external tool gets 'force updated' / a new minimum version gets enforced and hell breaks lose.
example: https://github.com/facebook/react-native/issues/19259

IMHO, a way to potentially decrease / reduce these effects - which go beyond the control of react native - is to better communicate and educate developers about the existence of these tools and the overall approach to them. In particular, I think it would be a good start to add a table with the 'we know this version of this tool works' approach (ex. tool / creator / latest know version to work well) and a page in the docs with a brief description of each one (or a mix of both?).

So I decided to open this issue - Here is what I would like to discuss:

1) Does this reasoning make sense?

1) What approach should we communicate as the 'best/safest/approved'?

I think the overall reasoning should be "don't update unless necessary, and before upgrading run a search on open issues".

1) What tools should the list comprehend?

My current take of this is 'all of the ones we can think of' - and here's a list of the ones that come into my mind at the moment:
* Metro (+ Haste)
* Watchmen
* iOS (https://github.com/facebook/react-native/issues/19346)
* CocoaPods
* XCode (https://github.com/facebook/react-native/issues/16850)
* macOS (https://github.com/facebook/react-native/issues/19218)
* Android (https://github.com/facebook/react-native/issues/19297)
* Gradle (https://github.com/facebook/react-native/issues/19259)
* ProGuard
* JSC (which I think is the only one that has "its" doc page: https://facebook.github.io/react-native/docs/javascript-environment.html)
* Android's NDK (https://github.com/facebook/react-native/issues/19321)
* Yoga
* Flow

**Comment by GantMan** [comment]
Here's an interesting part to add. Some of those tools are optional.  Like XCode... though it's at the core, if you're doing Android dev on a Windows machine you should never see watchman or Xcode!

I found this problem difficult to solve, but do a pretty ok job for my [solidarity plugin for react native](https://github.com/infinitered/solidarity-react-native).

Things my plugin has noticed that I see missing above are the following.  Even though many of these might be optional, they could be essential if a team is using them.   That's the funny part isn't it?
* Node - yes some people don't have it
* yarn - optional
* mobileCenter - optional
* codePush - optional
* pod - optional
* detox - optional
* typescript - optional

I'd love to have solidarity be a tool we could use for our reports if possible.  It supports plugins, so it can do anything we need it to.  I'm just not always familiar with each person's problem to prescribe it.

I hope this list and offer to extend with plugins helps!

**Comment by kelset** [comment]
Thanks for the feedback Gant!

**Comment by GantMan** [comment]
Let's definitely discuss.  If react-native rolled out with a `.solidarity` file it's a few bytes.  They could then optionally install solidarity and take advantage of it if they have problems.  It wouldn't increase the bundle size.  Or go full-awesome and bring it in as a dev dependency to work hand in hand with envinfo (which it already does).

**Comment by kelset** [comment]
ok I think this one can be closed
