### ISSUE TITLE
Fix out-of-bounds iOS/Android emulators in examples

### ISSUE THREAD

**Issue by NickGerleman** [facebook/react-native-website#3751]
Some of the examples on the React Native documentation are missing part of their content when viewed on Android/iOS.

https://reactnative.dev/docs/image-style-props

<img width="480" alt="image" src="https://user-images.githubusercontent.com/835219/236763258-adb87df3-9a3b-44d7-a64c-fa77ec62765d.png">

<img width="480" alt="image" src="https://user-images.githubusercontent.com/835219/236768374-c3640e40-2f4d-40d8-a46b-9b74acdd8d82.png">

This is because the website sets a fixed height for the player, and the rendering of the device we were showing has changed.

https://github.com/facebook/react-native-website/blob/d67805884a7c0920dcefc1af5894580984918239/website/src/css/customTheme.scss#L1717

@byCedric did great work in #3724 to allow the React Native website to customize the frame the emulator is shown in. We should leverage that, and change our styling + embed to a new value which avoids being cut off.

**Comment by spencerlwahlstrom** [comment]
Hello, I attempted to fix this issue with #3753  by adjusting the height, tested this on multiple pages of the site.
