### ISSUE TITLE
Incomplete description of color variables

### ISSUE THREAD

**Issue by JacobDel** [facebook/react-native-website#3763]
## Description

It is difficult to know which variables in the theming correspond to the colors of each react native paper component. Especially since the big change from MD2 -> MD3.

> dark (boolean): whether this is a dark theme or light theme.
> mode ('adaptive' | 'exact'): color mode for dark theme (See [Dark Theme](https://callstack.github.io/react-native-paper/4.0/theming.html#dark-theme)).
> roundness (number): roundness of common elements, such as buttons.
> colors (object): various colors used throughout different elements.
> primary - primary color for your app, usually your brand color.
> accent - secondary color for your app which complements the primary color.
> background - background color for pages, such as lists.
> surface - background color for elements containing content, **such as** cards.
> text - text color for content.
> disabled - color for disabled elements.
> placeholder - color for placeholder text, **such as** input placeholder.
> backdrop - color for backdrops of various components **such as** modals.
> onSurface - background color for snackbars
> notification - background color for badges
> 

## What is the problem?

It is not clear how to change the color of a certain react native paper component by looking at either the documentation of the component or the theming page.

## How can we address it?

Either by adding to each react native paper component documentation page which color variables correspond to which part or by extending the description of the theming page to complete which 

## Why is it important?

Slows down the developer a lot, as he/she needs to see what colors are changing by trial and error, and be sure other pages stay the same when the developer doesn't know what components are linked to the color variables.

## Who needs this?

Everyone who wants to change the theming, I can't imagine that we need to memorize the meaning behind each variable for every update

## When should this happen (use version numbers if needed)?
?

**Comment by martinyis** [comment]
Hi , can I work on this issue?

**Comment by JacobDel** [comment]
> Hi , can I work on this issue?

Hi @martinyis ,
My apologies, this was supposed to be an issue for react-native-paper. I didn't notice I was in the wrong repo.
