### ISSUE TITLE
Outdated splash screen instructions for iOS

### ISSUE THREAD

**Issue by paulschreiber** [facebook/react-native-website#3768]
## Description
On the [Publishing to Apple App Store](https://reactnative.dev/docs/publishing-to-app-store) page under Configure release scheme > Pro Tips, the docs show:

> If this is the case, you can add the following code to `AppDelegate.m` in order to keep your splash screen displayed during the transition.
```objc
  // Place this code after "[self.window makeKeyAndVisible]" and before "return YES;"
  UIStoryboard *sb = [UIStoryboard storyboardWithName:@"LaunchScreen" bundle:nil];
  UIViewController *vc = [sb instantiateInitialViewController];
  rootView.loadingView = vc.view;
```

However, there is no more `AppDelegate.m`.React Native uses `AppDelegate.mm` instead, and there is no `[self.window makeKeyAndVisible]` in the new file.

**Comment by professorkolik** [comment]
For some people this would be helpful => https://github.com/facebook/react-native/issues/35937
Unfortunately doesn't work for us same way as before

**Comment by paulschreiber** [comment]
Bad bot. No cookie.
