### ISSUE TITLE
Add Codebase explenation docs

### ISSUE THREAD

**Issue by martinyis** [facebook/react-native-website#3779]
## Description

Currently, when beginners open a React Native website's GitHub repository, it can be quite challenging to understand how the code works, even if there are contributing explanations available. In my opinion, it would greatly benefit the community to have separate documentation that provides a clear explanation of the codebase.

## What is the problem?
There is no Codebase explenation

## How can we address it?

This repo holder

## Why is it important?

To bring more contributors.

## Who needs this?

Everyone

**Comment by agrittiwari** [comment]
I also feel this is needed. Would love to write some docs if I find some resource and it is picked.
