### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by wzup** [facebook/react-native-website#378]
Here https://github.com/facebook/react-native/tree/master/ReactAndroid#building-react-native-for-android

This link is broke https://facebook.github.io/react-native/docs/android-building-from-source.html

> See the [docs on the website](https://facebook.github.io/react-native/docs/android-building-from-source.html).
https://facebook.github.io/react-native/docs/android-building-from-source.html

**Comment by charpeni** [comment]
Fixed in https://github.com/facebook/react-native/pull/19450.
