### ISSUE TITLE
Is the "no longer actively maintained" banner accurate?

### ISSUE THREAD

**Issue by liamjones** [facebook/react-native-website#3797]
## Description

I was browsing the 0.71 docs (example: https://reactnative.dev/docs/0.71/accessibilityinfo) and noticed the banner at the top of the page:

![image](https://github.com/facebook/react-native-website/assets/521341/8e0935c6-6138-4e47-a7a6-68e997e40c6f)

This feels at odds with what the react-native-releases repo says currently (**emphasis** mine): 

> [...]the level of support provided by the release crew to the various versions of React Native is weighted to focus on the newer versions, **while maintaining the previous two minors**.

(From https://github.com/reactwg/react-native-releases/blob/76807be7ae7e611c9a8308027337e49dd981dc4a/README.md?plain=1#L7)

I read the banner as talking about RN itself but maybe it's talking about the docs specifically (e.g. 0.72's docs are out so we won't alter 0.71s anymore)?

## Documentation version

0.71

**Comment by cortinico** [comment]
The wording is not exact, but also this is what docusaurus gives us:
https://docusaurus.io/docs/versioning#configuring-versioning-behavior

Maybe @slorber can tell us if there is an easy way to customize the wording/behavior or we'll have to fork `plugin-content-docs`?

**Comment by Simek** [comment]
I think that we can swizzle the Version Banner if we want to customize the wording.
