### ISSUE TITLE
WebView methods missing from Docs

### ISSUE THREAD

**Issue by Mohamed3on** [facebook/react-native-website#383]
Hi, I noticed some WebView methods such as `goBack` and `goForward` are missing from the RN docs, even though they are still working and were present in earlier docs:
https://facebook.github.io/react-native/docs/0.6/webview.html
Is this unintended, or is there a reason behind their removal?

**Comment by rickhanlonii** [comment]
Hey @Mohamed3on thanks for submitting!

Not sure if the methods were removed in previous versions on purpose, but WebView was removed from core and the new docs are [here](https://github.com/react-native-community/react-native-webview)
