### ISSUE TITLE
Missing `--template` argument option list in documentation when create a new react native project

### ISSUE THREAD

**Issue by GabrielGomesBarbosa** [facebook/react-native-website#3853]
## Description

In documentation to create a new project using CLI, is mentioned that is possible create a new project with `--template` flag. See the example that i got from documentation:

`npx react-native@X.XX.X init AwesomeProject --version X.XX.X --template`

Now a replace `X.XX.XX` for the that i want to create

`npx react-native@0.70.13 init AwesomeProject --version 0.70.13 --template ???`

Which arguments is possible to use in `--template`, is not mentioned in docs.

## What is the problem?

I can't see the option list to use as argument option for `--template` when create a new CLI react native project

## How can we address it?

Put a list of valid arguments that is possible to use when create a 

## Why is it important?

It's important know the available templates and options to use

## Who needs this?

All developers that want create a new react native project using CLI

**Comment by cortinico** [comment]
> In documentation to create a new project using CLI, is mentioned

Which page specifically are you referring to?

**Comment by GabrielGomesBarbosa** [comment]
Hello @cortinico sorry for your answer, the page of "Setting up the environment" both Android and iOS

https://reactnative.dev/docs/environment-setup?guide=native&platform=android

**Comment by cortinico** [comment]
I see. The documentation for teh `--template` flag is here https://github.com/react-native-community/cli/blob/main/docs/init.md
I don't think we should add more examples here frankly and the current content is probably sufficient.
