### ISSUE TITLE
`/docs/appstate` page is crashing

### ISSUE THREAD

**Issue by Kingkon963** [facebook/react-native-website#3857]
## Description

As a visitor, when I visit the page [https://reactnative.dev/docs/appstate](https://reactnative.dev/docs/appstate), I get `Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. ` error. It would be better if I could visit the page and read the docs.

![image](https://github.com/facebook/react-native-website/assets/33956213/6e469009-f840-4b73-a124-412403535c03)

## Documentation version

I've checked the listed versions, and the error is present in all of them.
next
0.72
0.71
0.70

**Comment by slorber** [comment]
Hi

Can you open your browser devtools and show us the stacktrace of the error if available?

Can you open the window without any browser extension?

What's your OS/Browser and versions?
