### ISSUE TITLE
Missing step on "Navigating Between Screens" section in react native documentation

### ISSUE THREAD

**Issue by JuszJo** [facebook/react-native-website#3862]
## Description

According to the official react navigation documentation https://reactnavigation.org/docs/getting-started, after installing all dependencies for react navigation to work, there is an extra step required for the "react-screens" package to work properly on android devices that is missing from the "Navigating Between Screens" section in https://reactnative.dev/docs/navigation#react-navigation.

## What is the problem?
It requires an extra configuration in the ```MainActivity.java``` file which is located in ```android/app/src/main/java/<your package name>/MainActivity.java``` in order for react navigation to work properly on android devices.

## How can we address it?
A simple solution would just be to update the documentation for just this problem as it is an important step in process of using react navigation for android devices.

## Why is it important?
It would provide more clarity to the process of setting up a react native app for navigation

## Who needs this?
All devs alike will need this as it is a crucial step in setting up a react native app for navigation

## When should this happen (use version numbers if needed)?
Since this is a documentation issue, I believe it should happen in the next minor updates

**Comment by cortinico** [comment]
> It requires an extra configuration in the `MainActivity.java` file which is located in `android/app/src/main/java/<your package name>/MainActivity.java` in order for react navigation to work properly on android devices.

We should probably update this page to point to the onboarding page of react-navigation rather than having to keep up with the instruction changes

**Comment by JuszJo** [comment]
> > It requires an extra configuration in the `MainActivity.java` file which is located in `android/app/src/main/java/<your package name>/MainActivity.java` in order for react navigation to work properly on android devices.
> 
> We should probably update this page to point to the onboarding page of react-navigation rather than having to keep up with the instruction changes

Yes that can also be a solution

**Comment by cortinico** [comment]
Are you up for sending a PR for it @JuszJo ?

**Comment by JuszJo** [comment]
> Are you up for sending a PR for it @JuszJo ?

Yes, I would like to.

**Comment by JuszJo** [comment]
Hey @cortinico, I have opened a PR for this issue.

**Comment by JuszJo** [comment]
Oh, will do that. thank you

**Comment by cortinico** [comment]
Closed by https://github.com/facebook/react-native-website/pull/3866
