### ISSUE TITLE
MacOS-iOS dependencies failure handling should reference ruby/config.h, universal-darwin symlinks

### ISSUE THREAD

**Issue by ogallagher** [facebook/react-native-website#3868]
https://github.com/facebook/react-native-website/blob/12a04bc3e28c76571452e00e727fb0b85a5b17c6/docs/_getting-started-macos-ios.md?plain=1#L65-L69

I wasn't able to install the gems required for this step until I followed [these instructions](https://stackoverflow.com/a/65481787/10200417). I recommend that a version of them be included in this environment setup page.

I'm using macOS Monterey 12.7.

**Comment by cortinico** [comment]
> I recommend that a version of them be included in this environment setup page.

Which "version of them" are you referring to specifically? (I.e. which command you had to run)

**Comment by ogallagher** [comment]
Note the version numbers for the Mac OS SDK and Ruby version will vary, but can be seen in errors when trying to install some of the gems.

### Symbolic link for `ruby/config.h`

```txt
# results
source/original = /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/Headers/ruby/config.h
target/alias    = /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/config.h

# commands
cd /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby
ln -s ../../../../Headers/ruby/config.h
```

### Symbolic link for `universal-darwin<version>`

```txt
# results
source/original = /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin22
target/alias    = /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin21

# commands
cd /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0
ln -s universal-darwin22 universal-darwin21
```

**Comment by ogallagher** [comment]
I think this troubleshooting info would be useful to include in the macOS instructions.
