### ISSUE TITLE
Failed to generate a signed key

### ISSUE THREAD

**Issue by JnPhJnPh** [facebook/react-native-website#389]
Hi, guys,

I was following the tutorial here to generate a signed APK: https://facebook.github.io/react-native/docs/signed-apk-android.html

But it failed even at step one: Generating a signing key.
"keytool -genkey -v -keystore my-release-key.keystore -alias my-key-alias -keyalg RSA -keysize 2048 -validity 10000
bash: $: command not found"

As I'm completely new to this, any help would be appreciated.
Thank you!

/Jn

**Comment by endiliey** [comment]
Are you on windows:
On Windows `keytool` must be run from `C:\Program Files\Java\jdkx.x.x_x\bin`.

If you are not on Windows:
1. Ensure jre is installed & Search the path where your java was installed
find / -name jre
2. Move to that java directory (where jre was installed)
cd /path/to/jre/location
3. Follow that instruction
keytool -genkey -v -keystore my-release-key.keystore -alias my-key-alias -keyalg RSA -keysize 2048 -validity 10000
