### ISSUE TITLE
Website Security Warning: NET::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by flokol120** [facebook/react-native-website#3890]
## Description

When visiting [https://reactnative.dev/](https://reactnative.dev/) you are greeted with a security warning:

<img width="444" alt="image" src="https://github.com/facebook/react-native-website/assets/22056791/289a55a7-8ed5-4dd1-bc99-5b722623ae36">

I assume this error originates from this certificate:

<img width="226" alt="image" src="https://github.com/facebook/react-native-website/assets/22056791/4ed691c0-cc98-4bed-b0d1-cc7c04e6d3c8">

It is not possible to visit the docs as HSTS is enabled.

## Documentation version

N/A

**Comment by cortinico** [comment]
Closing as this is fully resolved now
