### ISSUE TITLE
RCTSetImageCacheLimits undeclared 

### ISSUE THREAD

**Issue by recallwei** [facebook/react-native-website#3927]
### Description

Is this outdated?

![image](https://github.com/facebook/react-native/assets/62941121/27107a96-da84-4fc4-a2b6-8eeff8c4c839)

---

I try to config RCTSetImageCacheLimits but get an error of undeclared identifier.

![image](https://github.com/facebook/react-native/assets/62941121/e70e55b5-02b6-4b1f-b4a4-3cbf54074496)

### React Native Version

0.72.6

### Output of `npx react-native info`

System:
  OS: macOS 14.0
  CPU: (10) arm64 Apple M2 Pro
  Memory: 79.69 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.9.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.1.0
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.09.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.8.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: 0.72.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

Add `RCTSetImageCacheLimits(4 * 1024 * 1024, 200 * 1024 * 1024);` in `AppDelegate.mm` within `didFinishLaunchingWithOptions`.

### Snack, screenshot, or link to a repository

![image](https://github.com/facebook/react-native/assets/62941121/3a00d6e6-b31e-4321-ac78-786ce5ebe252)

**Comment by Simek** [comment]
Hey @recallwei, can you try adding `#import <React/RCTImageCache.h>` import at the top of your file?

**Comment by recallwei** [comment]
> Hey @recallwei, can you try adding `#import <React/RCTImageCache.h>` import at the top of your file?

![image](https://github.com/facebook/react-native-website/assets/62941121/bc0648c5-fc2b-43d6-ba05-a91c935ba41d)

Still not working.

**Comment by Simek** [comment]
Hmm, not sure what is happening then, it works correctly for me in simple app created from template.

<img width="1012" alt="Screenshot 2023-11-27 at 10 31 40" src="https://github.com/facebook/react-native-website/assets/719641/5bc26c25-bc8c-4cc1-a3ad-d5ce62a3a5a3">

Can you try to reproduce the problem using new app template? If the code still broke in that case, then you should be able to publish the code and share it with us, so we can investigate futrher.

**Comment by recallwei** [comment]
Sorry, it was my spelling mistake. I just figured out that `RCT` means `React`.
