### ISSUE TITLE
No instructions on how to build an APK file

### ISSUE THREAD

**Issue by vresetnikov** [facebook/react-native-website#3932]
## What is the problem?

The documentation provides no information on how to build an .APK file (not AAB). 

## How can we address it?

Please provide detailed information on how to opt for an .APK instead of AAB using React Native.

## Why is it important?

There are scenarios when the app is not ready to be deployed to Google Play but needs to be tested in a semi-production environment over extended periods of time in closed circles. 

## Who needs this?
People who want to build APKs, such as our team. 

## When should this happen (use version numbers if needed)?
Asap please

**Comment by cortinico** [comment]
You can find instructions about it in the Android official documentation:
https://developer.android.com/build/building-cmdline

If you use Expo they also have a dedicated page:
https://docs.expo.dev/build-reference/apk/

**Comment by vresetnikov** [comment]
> You can find instructions about it in the Android official documentation: https://developer.android.com/build/building-cmdline
> 
> If you use Expo they also have a dedicated page: https://docs.expo.dev/build-reference/apk/

Hello, the provided android documentation link does not provide information on how to build a release APK.

**Comment by vresetnikov** [comment]
> You can find instructions about it in the Android official documentation: https://developer.android.com/build/building-cmdline
> 
> If you use Expo they also have a dedicated page: https://docs.expo.dev/build-reference/apk/

Hello, the provided android documentation link does not provide information on how to build a release APK. Furthermore, your reply does not address the main issue, that is why RN documentation contains all the information necessary for building an AAB file, but contains no instructions for building an APK. Looking at other projects, such as Flutter, they provide detailed instructions and commands for both.
