### ISSUE TITLE
Docs for disabling Hermes incorrect in 0.74

### ISSUE THREAD

**Issue by rickhanlonii** [facebook/react-native-website#3950]
### React Native Version

0.73.0

### Description

The docs for ["Switching Back to JavaScriptCore"](https://reactnative.dev/docs/hermes#ios-1) say you can edit the podfile here to disable Hermes:

<img width="757" alt="Screenshot 2023-12-11 at 4 10 15 PM" src="https://github.com/facebook/react-native/assets/2440089/d2920809-55ac-4cbf-9131-d146dbc080c1">

But in https://github.com/facebook/react-native/pull/39389 we removed the lines that these docs reference in the podfile. So in 0.74, the lines this reference no longer exist and the docs don't make sense.

We may just need to update the docs to say "add `:hermes_enabled => false` here", but I wanted to confirm that that will actually work after the changes in facebook/react-native#39389 before updating the docs.

### Steps to reproduce

1. install new project
2. follow these docs: https://reactnative.dev/docs/hermes#ios-1
3. see the podfile isn't the same

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
no
```

### Stacktrace or Logs

```text
no
```

### Reproducer

Run it yourself

### Screenshots and Videos

Above

**Comment by blakef** [comment]
@rickhanlonii looks like it [still works](https://github.com/facebook/react-native/blob/952b32b06dd7837307112e88677f782bba6db674/packages/react-native/scripts/react_native_pods.rb#L136-L140).  I'm happy to update the docs unless you'd like to?

**Comment by cortinico** [comment]
> We may just need to update the docs to say "add `:hermes_enabled => false` here", but I wanted to confirm that that will actually work after the changes in [facebook/react-native#39389](https://github.com/facebook/react-native/pull/39389) before updating the docs.

That's correct. 

We need to update the page to make sure the diff mentions to just **add** the line. The alternative way to enable Hermes is to do `USE_HERMES=1 pod install`. I'm unsure if we want to advertise this.

@blakef can you update `main` and `0.73` docs?

**Comment by rickhanlonii** [comment]
> The alternative way to enable Hermes is to do `USE_HERMES=1 pod install`
 
 Well, it's enabled by default, so you would disable it with `USE_HERMES=0 pod install` right?

**Comment by cortinico** [comment]
> > The alternative way to enable Hermes is to do `USE_HERMES=1 pod install`
> 
> Well, it's enabled by default, so you would disable it with `USE_HERMES=0 pod install` right?

Yup exactly 👍
