### ISSUE TITLE
how to hide header of parent drawer Navigator

### ISSUE THREAD

**Issue by SamarthKadam** [facebook/react-native-website#3956]
We don't have a option to hide the parent header.For example If I have the A Drawer Navigator and its component has got Stack Navigator. In one of the screen in stack Navigator I need to hide the header of Drawer Navigator how is it possible. 

So this is parent navigator
import { createDrawerNavigator } from '@react-navigation/drawer';
import Orders from '../screens/Orders';
import Favourites from '../screens/Favourites';
import Inbox from '../screens/Inbox';
import Settings from '../screens/Settings';
import React from 'react'
import CustomDrawerContent from '../components/Drawer/CustomDrawerContent';
import HeaderRightShop from '../components/Shop/HeaderRight';
import HeaderRightFavourite from '../components/Favourites/HeaderRight'
import ShopNavigator from './ShopNavigator';

const Drawer = createDrawerNavigator();

export default function HomeNavigator() {

  
  return (
      <Drawer.Navigator screenOptions={{headerShadowVisible:false,headerShown:true}}
      drawerContent={(props) => <CustomDrawerContent {...props} />}>
        <Drawer.Screen name="Shopping" options={{headerRight:()=><HeaderRightShop></HeaderRightShop>}} component={ShopNavigator} />
        <Drawer.Screen name="Orders"  component={Orders} />
        <Drawer.Screen name="Favourite" options={{headerRight:()=><HeaderRightFavourite></HeaderRightFavourite>}} component={Favourites} />
        <Drawer.Screen name="Inbox"  component={Inbox} />
        <Drawer.Screen name="Settings" component={Settings} />
      </Drawer.Navigator>
    );
}
this is ShopNavigator
import React, { useEffect } from 'react';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import Shop from '../screens/Shop';
import Overview from '../screens/Overview';
import Results from '../screens/Results';

const Stack = createNativeStackNavigator();

export default function ShopNavigator({navigation,route,options}) {

  return (
    <Stack.Navigator screenOptions={{animation:"fade_from_bottom"}}>
    <Stack.Screen options={{headerShown:false}} name="Shop" component={Shop} />
    <Stack.Screen name="Overview" component={Overview} />
    <Stack.Screen name="Results" options={{headerShorwn:true}} component={Results} />
  </Stack.Navigator>
  )
} 
So I need to hide the DrawerNavigator header when the Results Screen is viewed? 
How can I achieve this

**Comment by cortinico** [comment]
You should ask this question on StackOverflow here:
https://stackoverflow.com/questions/tagged/react-native
