### ISSUE TITLE
What does the 'md' in the event signature mean?

### ISSUE THREAD

**Issue by don-glover** [facebook/react-native-website#3965]
## Description

In onLoad in image.md, the type is defined as 
`md ({nativeEvent: [ImageLoadEvent](image#imageloadevent)} => void`

## What is the problem?

the md usage does not seem to appear else

## How can we address it?

explain the md in this case.

**Comment by Simek** [comment]
Hello @don-glover, this is an indication for Docusaurus that code block content should be treated as Markdown code, and not interpreted as JS(X) code that need to be executed, and it's related to MDX renderer upgrade. In this case adding `md` make sure that Markdown link in code block will render and work correctly.

You can read more about this migration aid in the origin PR:
* https://github.com/facebook/react-native-website/pull/3807

**Comment by lunaleaps** [comment]
Closing this as it seems addressed
