### ISSUE TITLE
More info on environment version JDK

### ISSUE THREAD

**Issue by rishikesh2003** [facebook/react-native-website#3967]
## Description

More info on environment setup adding which JDK version is supported for the current react native version

## What is the problem?

Able to configure the correct jdk version for react native instead of finding it after the error.

## How can we address it?

Add the correct JDK version needed for reactnative eg : 17, 18 or 21 etc

## Who needs this?
Everyone who is getting started and doing an environment setup

**Comment by cortinico** [comment]
This is already described here:
https://reactnative.dev/docs/environment-setup?guide=native

![Screenshot 2024-01-02 at 10 48 22](https://github.com/facebook/react-native-website/assets/3001957/dc950d15-62a0-4628-ac70-77dfd342b09e)
