### ISSUE TITLE
link for example app for integration (2048 game) is broken

### ISSUE THREAD

**Issue by tarunrajput** [facebook/react-native-website#3984]
## Description

link for [app for integration](https://github.com/JoelMarcey/iOS-2048) is broken in Adding React Native to your app docs

https://reactnative.dev/docs/next/integration-with-existing-apps?language=swift#adding-react-native-to-your-app
https://reactnative.dev/docs/next/integration-with-existing-apps?language=objc#adding-react-native-to-your-app

<img width="901" alt="image" src="https://github.com/facebook/react-native-website/assets/34857453/45949668-7ae3-4801-b798-55973510bd8a">

**Comment by cortinico** [comment]
I think we should either remove those links/section entirely, or find a proper replacement + retake all the screenshtos

**Comment by lunaleaps** [comment]
@tarunrajput Would you be interested in investigating where the link for the app integration is? My preference is also slightly removing these instructions. cc @cortinico thoughts?

**Comment by cortinico** [comment]
related to https://github.com/facebook/react-native-website/pull/4076
