### ISSUE TITLE
Deprecated components should be clearly marked deprecated on the website

### ISSUE THREAD

**Issue by flanger001** [facebook/react-native-website#3996]
## Description

Deprecated components should be clearly marked deprecated on the website and they are not.

## What is the problem?

When developing a React Native app with navigation using the guides on the website (https://reactnative.dev/docs/navigation), the browser console emits a warning "Button is deprecated. Please use Pressable." among others:

![image](https://github.com/facebook/react-native-website/assets/1645017/bbb2a7d0-f7bf-4213-99ba-3767b57dc79e)

None of these components are actually marked as deprecated on the website. #3421 addresses Button, but it is the softest possible recommendation I've ever seen and can hardly be considered a deprecation notice.

## How can we address it?

Clearly mark deprecated components and props, using stronger language, and provide clear resolution paths. As a visual suggestion: 

![image](https://github.com/facebook/react-native-website/assets/1645017/1173f646-a049-40b3-9e01-c57b7127290f)

On a related note, accessibility labels are not only for blindness and this language could be made more inclusive. Not trying to be a wokescold, just making a note.

## Why is it important?

If I am learning the most up-to-date version of a framework with the most up-to-date version of that framework's documentation and the prescribed solutions causes my browser to emit a deprecation notice, I am not confident I can trust that documentation and therefore am not confident I can trust my knowledge.

## Who needs this?

Everyone, but particularly learners.

## When should this happen (use version numbers if needed)?

As soon as a component or prop is marked deprecated.

**Comment by lunaleaps** [comment]
Great points! Is this something you'd be interested in helping out on?

**Comment by flanger001** [comment]
> Great points! Is this something you'd be interested in helping out on? 

Most definitely!

**Comment by flanger001** [comment]
@lunaleaps Should I open a PR? I don't know what all of the deprecated stuff is and would need some guidance on finding it.
