### ISSUE TITLE
Docs doesn't show props descriptions

### ISSUE THREAD

**Issue by brunolemos** [facebook/react-native-website#40]
<img width="706" alt="image" src="https://user-images.githubusercontent.com/619186/33725040-26a7a77c-db58-11e7-981c-3479a45e3b4a.png">

**Comment by hramos** [comment]
Can you link to the doc that contains these props?

**Comment by AudyOdi** [comment]
@hramos I think this one is from `VirtualizedList` https://facebook.github.io/react-native/docs/virtualizedlist.html

**Comment by brunolemos** [comment]
^ yes, `VirtualizedList`
