### ISSUE TITLE
TextInput .focus() method is not documented

### ISSUE THREAD

**Issue by nilscox** [facebook/react-native-website#400]
Hi!

I want to programmatically focus a React Native `TextInput`, and as far as I understand from stackoverflow and github issues, there is a `.focus()` method that I can invoke on the `TextInput` ref. This does work as expected.

Sadly, I can't find any documentation about this method. So is it part of the `TextInput` public API? Is it safe to use?

Thanks.

**Comment by jamesgeorge007** [comment]
@nilscox It is mentioned there in the [Official docs](https://facebook.github.io/react-native/docs/textinput)
