### ISSUE TITLE
Add Pressable Component to the Documentation of Core-Components and API, User Interface Section

### ISSUE THREAD

**Issue by totitoti7** [facebook/react-native-website#4022]
## Description

The current React Native documentation, specifically in the section that discusses [User Interface components](https://reactnative.dev/docs/components-and-apis#user-interface) such as Button and Switch, does not include the Pressable component. Including Pressable would provide a more comprehensive overview of the interactive elements available in React Native, enhancing the documentation's utility and accessibility for developers.

## What is the problem?

The omission of the Pressable component from this section may lead to a lack of awareness about this flexible alternative, which offers more customization and control over touch interactions compared to Button and Switch. This gap can hinder developers, especially newcomers, from exploring and utilizing Pressable in their projects.

## How can we address it?
To rectify this, we should update the docs/components-and-apis.md file  to include the Pressable component within the same section as Button and Switch. here is what the code can be updated to: 

## User Interface

These common user interface controls will render on any platform.

<div className="component-grid component-grid-border">
  <div className="component">
    <a href="./button">
      <h3>Button</h3>
      <p>A basic button component for handling touches that should render nicely on any platform.</p>
    </a>
  </div>
<div className="component">
    <a href="./pressable">
      <h3> Pressable </h3>
      <p> A Core Component wrapper that can detect various stages of press interactions on any of its defined children. </p>
    </a>
  </div>
  <div className="component">
    <a href="./switch">
      <h3>Switch</h3>
      <p>Renders a boolean input.</p>
    </a>
  </div>
</div>

## Why is it important?

Incorporating Pressable into the documentation is crucial because it:
- Broadens the toolkit available to developers, promoting more flexible and creative UI designs.
- Ensures developers are fully informed about the components at their disposal, leading to better decision-making in UI development.
- Aligns with the goal of keeping the React Native documentation comprehensive and up to date with the framework's capabilities.

## Who needs this?

This documentation update is beneficial for:
- New learners who are building their foundational knowledge of React Native.
- Experienced Android and iOS developers seeking to leverage React Native's full potential.
- Developers looking to create more customized and interactive user interfaces.

## When should this happen (use version numbers if needed)?
It would be ideal for this update to be included in the next documentation update cycle. If version numbers are applicable, aiming for inclusion in the upcoming release would ensure that the documentation remains current and comprehensive.

**Comment by cortinico** [comment]
> The current React Native documentation, specifically in the section that discusses [User Interface components](https://reactnative.dev/docs/components-and-apis#user-interface) such as Button and Switch, does not include the Pressable component. Including Pressable would provide a more comprehensive overview of the interactive elements available in React Native, enhancing the documentation's utility and accessibility for developers.

Please go ahead and add Pressable in the page in a PR 👍
