### ISSUE TITLE
Issue with "Setting up the development environment" Page version=0.73

### ISSUE THREAD

**Issue by litoco** [facebook/react-native-website#4036]
Update required for **Android SDK Platform 34** in the documentation

## Description

On [this](https://reactnative.dev/docs/environment-setup?guide=native&platform=android&os=macos) page, under <b>Creating a new application</b> section, the command used for creating a new project with name "Awesome Project" is `npx react-native@latest init AwesomeProject`. 

This creates the project with **Android SDK Platform 34**, however in the documentation the **SDK platform** version as well as the **system images** are mentioned for Android SDK Platform 33. This resulted in a lot weird errors.

## Documentation version

Changes needed to be reflected in the following documentation version:
- 0.73
- next

**Comment by cortinico** [comment]
You're right @litoco.
Don't you mind sending over a PR to update the required platform to 34 for 0.73 and next?

**Comment by litoco** [comment]
@cortinico PR sent.

**Comment by Simek** [comment]
Thanks for the quick follow up @litoco! 👍 Closing as done!

**Comment by Voxar** [comment]
Yo. I followed the guide just now and it still says to install Android 13, SDK 33 etc for 0.74.

https://reactnative.dev/docs/environment-setup?platform=android
> Last updated on Apr 22, 2024
