### ISSUE TITLE
Bug: Search functionality not working correctly on react.dev in Safari on iOS real device (iPhone 12 Pro)

### ISSUE THREAD

**Issue by MeetYourCreator** [facebook/react-native-website#4052]
## Steps To Reproduce

1. Open react.dev in Safari on iPhone (real device)
2. Tap search icon: note that search function is working as intended
3. Scroll down to "Write components with code and markup" section
4. Tap search icon: note that action doesn't open search
5. Scroll down again and tap the search icon several times:  note that action doesn't open search
6. Repeat step 5: note that eventually screen freezes

An issue has also been opened [in the react repository](https://github.com/facebook/react/issues/28547)
---

## The current behavior
Search functionality does not work correctly on iOS real device (iPhone 12 Pro). 

https://github.com/facebook/react-native-website/assets/57572988/0dccc556-28dc-41a0-a583-260495e32272

Since search functionality is currently working as expected on macOS, both in Chrome and Safari, the issue might be in implementation of [Algolia InstantSearch iOS](https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/ios/):

https://github.com/facebook/react-native-website/assets/57572988/650ad2b8-fb2b-4572-a1a4-b30fa3d45539

The iOS real device that this behavior was recorded on is using the current iOS version:

![react_github-bug-report_ios-version](https://github.com/facebook/react-native-website/assets/57572988/5add100b-9392-4542-a7b1-0a075b33bbd0)

---

## The expected behavior

Search functionality is working as expected on macOS, both in Chrome and Safari. Should work similarly on iOS real device:

**macOs Chrome**

https://github.com/facebook/react-native-website/assets/57572988/8a73a526-308b-45c1-b35c-318ef3a1b765

**macOS Safari**

https://github.com/facebook/react-native-website/assets/57572988/bc48d3d1-eff9-4d01-9e51-9221f876bc8e

**Comment by Simek** [comment]
Hey @MeetYourCreator, this is repository contains the source code of [reactnative.dev](https://reactnative.dev), not [react.dev](https://react.dev). Those website are separate entities and don not share any code.

Usually I would transfer the issue to the correct repo, or recommend re-creating it in the correct repository, but I have seen that you have already posted this issue in other places, so I'm just going to close this one..
