### ISSUE TITLE
Fix errors in console of home page

### ISSUE THREAD

**Issue by ahmed0saber** [facebook/react-native-website#4054]
## Description

When I enter [this page](https://reactnative.dev/), I find multiple debugging logs and errors in console as shown below:
![Annotation 2024-03-14 230648](https://github.com/facebook/react-native-website/assets/64714761/9e61fce0-f1d9-4a74-913d-96374d24ae0d)

**Comment by apicgg** [comment]
I don't see this as major issue for the homepage.

**Comment by ahmed0saber** [comment]
Hello @apicgg , I don't really know what these errors can affect, and not sure 100% that these logs doesn't contain anything sensitive. Also these logs may throw errors in browsers not supporting dev tools (or just the console), which may affect the overall performance of the page (specially on mobile devices)
