### ISSUE TITLE
Update outdated external links to old React docs in "Using Typescript > Where to find useful advice"

### ISSUE THREAD

**Issue by sebastiancarlos** [facebook/react-native-website#4058]
## Description

The link on ["React's documentation on TypeScript"](https://reactnative.dev/docs/next/typescript#where-to-find-useful-advice) goes to https://reactjs.org/docs/static-type-checking.html#typescript

But the newest version is https://react.dev/learn/typescript

## Documentation version

next, and probably all of them.

**Comment by apicgg** [comment]
Older versions of docs should be skipped as they are not being maintained.
