### ISSUE TITLE
Module 'yoga' is needed but has not been provided, and implicit use of module files is disabled

### ISSUE THREAD

**Issue by Gongzehe** [facebook/react-native-website#4085]

**Comment by Gongzehe** [comment]
1.yarn react-native run-ios  
2.error  Module 'yoga' is needed but has not been provided, and implicit use of module files is disabled
3.<img width="988" alt="image" src="https://github.com/facebook/react-native-website/assets/25748278/8896fce4-7c82-4ab1-96a0-7f5595fafcb6">

Documentation version: Xcode  Version 12.5.1 (12E507)      reactNative Version0.73.7    node Version v18.20.2

how to resolve this question?

**Comment by StefanMiticon** [comment]
@Gongzehe did you find any solution for this?
