### ISSUE TITLE
0.74 Docs have been cut as stale

### ISSUE THREAD

**Issue by cortinico** [facebook/react-native-website#4094]
Yo. I followed the guide just now and it still says to install Android 13, SDK 33 etc for 0.74.

https://reactnative.dev/docs/environment-setup?platform=android
> Last updated on Apr 22, 2024

_Originally posted by @Voxar in https://github.com/facebook/react-native-website/issues/4036#issuecomment-2074960625_

@huntie I believe we cut the docs for 0.74 at a wrong revision.
For example we bumped the suggested SDK version to 34 one month ago:
- https://github.com/facebook/react-native-website/pull/4038

And the docs are still referencing the old value.
I believe when you ran `yarn docusaurus docs:version` your repo was at a old revision.

Could you redo the cut + re-apply all the changes that happened on main?

**Comment by huntie** [comment]
Sure — I'll have to get to this tomorrow though as I'm away from my computer. I also wanted to look at archiving versions up to 0.72, which needs exploration!
