### ISSUE TITLE
Documentation on TextInput style references an abandoned bug

### ISSUE THREAD

**Issue by mjaggard** [facebook/react-native-website#4101]
## Description
On this page https://reactnative.dev/docs/textinput#style the bug https://github.com/facebook/react-native/issues/7070 is referenced but that bug is locked and abandoned. Either the docs should not reference it, or the bug should be revived.

## Documentation version
0.74
next

**Comment by apicgg** [comment]
@mjaggard Does it still make sense to reference the bug ID into the docs even though the bug has been closed? Whoever is visiting the docs for the fist time, it will give them some understanding about this.

**Comment by mjaggard** [comment]
But the understanding it gives is "nobody can be bothered to check which styles work and document it correctly". Or possibly "valid bugs will be closed after some time regardless of whether they're important - even if they're important enough that they're in the documentation pages"

**Comment by apicgg** [comment]
@mjaggard Got it. Thanks for explaining.

**Comment by apicgg** [comment]
@cortinico Would like to know your thoughts on this. Thanks in advance.

**Comment by cortinico** [comment]
We should just remove the reference to the issue from the docs. Happy to review a PR about it

**Comment by apicgg** [comment]
> We should just remove the reference to the issue from the docs. Happy to review a PR about it

@cortinico #4108
