### ISSUE TITLE
App.js is referenced in the Quick Start, but not present.

### ISSUE THREAD

**Issue by naspinski** [facebook/react-native-website#4114]
## Description

The [Quick Start](https://reactnative.dev/docs/environment-setup?guide=quickstart) state:

`Now that you have successfully run the app, let's modify it. Open App.js in your text editor of choice and edit some lines.`

But when you create a new app using this method, there is no App.json file which is a bit confusing in addition to the App.js being referenced in most other documentation.
![image](https://github.com/facebook/react-native-website/assets/835597/d77df7be-80c7-4fea-975b-5f0026d8740a)

Could this please be clarified?

## Documentation version

Apr 22, 2024

**Comment by cortinico** [comment]
> Now that you have successfully run the app, let's modify it. Open App.js in your text editor of choice and edit some lines.

This can be updated to `App.tsx` now. Are you up for sending a PR?
Also the screenshots you show is from a Expo with Expo Router which has a different setup from a vanilla React Native app

**Comment by apicgg** [comment]
@naspinski Which version of docs are you referring here? You should go with 0.74 in case you starting fresh.

**Comment by naspinski** [comment]
Yeah, the confusing text is gone now :D
