### ISSUE TITLE
Instructions for linux not given / unclear

### ISSUE THREAD

**Issue by phadkesharan** [facebook/react-native-website#4122]
## Publishing to Google playstore instructions not given for linux

The react native documentation contains steps for publishing application to play store.
However the steps are provided only for windows and macOs
My  request is to also provide steps for publishing for linux as well

https://reactnative.dev/docs/signed-apk-android

**Comment by phadkesharan** [comment]
I get it that the documentation specifies that the signing can be done using keytool, but it is not explicilty mentioned for linux and hence is confusing. Might be better Idea  to explicitly mention it under Linux

**Comment by apicgg** [comment]
@phadkesharan Linux should be similar to the macOS one. But agreed it should be there.
