### ISSUE TITLE
Fix hover color for "Continue with Expo" link button in dark mode

### ISSUE THREAD

**Issue by jaamaalxyz** [facebook/react-native-website#4124]
## What is the problem?
When hovering over the "Continue with Expo" link button, the color becomes too white, making the text inside the button invisible in dark mode.

## How can we address it?
Go to the [Environment setup](https://reactnative.dev/docs/environment-setup) page and hover over the `Continue with Expo` button

## Why is it important?
This is a visibility issue, and people with low eye contrast may find it difficult to see the text inside the button when using dark mode.

## Who needs this?
Dark mode user

## When should this happen (use version numbers if needed)?
The current react native doc website

## Screenshot

<img width="1437" alt="hover-color-issue" src="https://github.com/facebook/react-native-website/assets/20262255/6c57d9a3-3ee7-4cb4-99e4-5f959503658c">

**Comment by jonsamp** [comment]
Nice find! I will put together a PR to fix this.

**Comment by jaamaalxyz** [comment]
@jonsamp thanks for the quick response. I have already fixed this locally. If you don't mind, I can send the PR.

**Comment by jonsamp** [comment]
@jaamaalxyz You're so fast! I also just put up a PR and then just saw this: https://github.com/facebook/react-native-website/pull/4126. 

I had a few other things to fix along the way so I put it all in one PR. I am going to talk to @cortinico and try to get mine merged. If it merges, then we can safely close your PR. --Thanks for putting it up!

**Comment by jaamaalxyz** [comment]
@jonsamp Thanks for letting me know the update. proceed with your PR.
