### ISSUE TITLE
Command to get zulu path is not correct

### ISSUE THREAD

**Issue by pokhiii** [facebook/react-native-website#4130]
## Description

In the [Set Up Your Environment](https://reactnative.dev/docs/set-up-your-environment) docs, the following command does not output what it intends to do – path to the zulu installation.

https://github.com/facebook/react-native-website/blob/b5789e91e747c796c71dc5e9921d37799c0038b8/docs/_getting-started-macos-android.md?plain=1#L27-L28

This is what it outputs, there is no path in here:
<img width="670" alt="image" src="https://github.com/facebook/react-native-website/assets/11808845/23da1a3b-73b5-4e00-b09c-858f714ac68c">

## Documentation version

`0.74`

**Comment by pokhiii** [comment]
ChatGPT suggested:

```shell
/usr/libexec/java_home -v 17
```

**Comment by tarunrajput** [comment]
@pokhiii, you need to install the cask first

**Comment by pokhiii** [comment]
@tarunrajput, did I miss something in the setup steps? is that mentioned there?

**Comment by tarunrajput** [comment]
yes, you need to run `brew install --cask zulu@17`

**Comment by pokhiii** [comment]
is there an issue with my system?
![image](https://github.com/facebook/react-native-website/assets/11808845/848c356f-e277-4687-b110-be85440926ce)

**Comment by apicgg** [comment]
@pokhiii 
After installing with `brew install --cask zulu@17`, make sure to update the `JAVA_HOME` env var. Add `export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home` into your `~/.bash_profile` or `~/.zshrc`. 

This makes sure that if your `java` command will use the `zulu@17` edition.

Also do check if this path `/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home` exists in your system after installation with `ls -la /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home`.
