### ISSUE TITLE
Help us migrate to GitHub Actions

### ISSUE THREAD

**Issue by cortinico** [facebook/react-native-website#4137]
## Description

We're looking for community support to help us migrate from CircleCI to GitHub Actions.

The CircleCI file is here:
https://github.com/facebook/react-native-website/blob/main/.circleci/config.yml

It's pretty simple so it should be easy to migrate over to GitHub Actions.

If you intend to work on it please comment before starting the work.

**Comment by apicgg** [comment]
@cortinico I can help with this one.

**Comment by cortinico** [comment]
> @cortinico I can help with this one.

Great I've assigned it to you 👍
