### ISSUE TITLE
Free RN course from Harvard on edX: Add link somewhere?

### ISSUE THREAD

**Issue by lll000111** [facebook/react-native-website#414]
This is not an ad - I get an edX newsletter because I took (and still take) lots of free courses on that platform. Today a new course was announced, from Harvard:

https://www.edx.org/course/cs50s-mobile-app-development-with-react-native

> CS50's Mobile App Development with React Native
> Learn about mobile app development with React Native, a popular framework maintained by Facebook that enables cross-platform native apps using JavaScript without Java or Swift.

13 weeks at 6-9 hours per week.

Maybe that should/could be added somewhere?

**Comment by kelset** [comment]
I think that maybe it could be added to a newly dedicated section in this page https://facebook.github.io/react-native/docs/more-resources.html or maybe just add it to the [awesome-react-native](https://github.com/jondot/awesome-react-native) repo.

**Comment by charpeni** [comment]
I agree with kelset, you can submit it to [awesome-react-native](https://github.com/jondot/awesome-react-native) repo whose more resources section is referring to.

**Comment by lll000111** [comment]
"Awesome RN" is under "Popular libraries".

Okay guys, if nobody gives enough of a f...k to even consider the category, why should I as a complete outsider care. Yeah, issue closed, I agree.

**Comment by charpeni** [comment]
I'm sorry you take this that way.

I mean your link to the course is interesting, but I don't think we should maintain a list of tutorials, videos, and books when awesome-react-native is already doing that job.

Let's reopen it then and discuss how we can reword the introduction of awesome-react-native in the more resource section. How'd you see that?

**Comment by kelset** [comment]
@lll000111 I **highly** recommend you tone down your wording. Your behaviour is not acceptable.

**Comment by lll000111** [comment]
@kelset *You* don't decide what **I** find acceptable.
