### ISSUE TITLE
Platform Version is listed as Android only and also iOS and Android

### ISSUE THREAD

**Issue by mjaggard** [facebook/react-native-website#4144]
## Description
The docs show a [table of properties](https://reactnative.dev/docs/platform#properties) where `Version` is listed as `Android only` and then [further down the page ](https://reactnative.dev/docs/platform#version) the same property is listed as a `number` on Android and a `string` on iOS.

## Documentation version
`next`

**Comment by cortinico** [comment]
That's because `Version` is a constant on Android:

https://github.com/facebook/react-native/blob/14ccf6bc9c40a51e913bb89a67b114f035bf77cd/packages/react-native/Libraries/Utilities/Platform.android.js#L36

But it's also a method `Version()` which works for both Android & iOS.

**Comment by mjaggard** [comment]
@cortinico

**Comment by cortinico** [comment]
> But the documentation doesn't say that. It has `Version` listed as a property in both places.

Sorry I wasn't 100% exact. There is a `Version` property that works for both Android & iOS.
Moreover, inside the `constant` property, you can access the `Version` property that is Android only.

The documentation is correct as it is:

![Screenshot 2024-06-13 at 11 41 48](https://github.com/facebook/react-native-website/assets/3001957/9377f1b7-1d1b-462f-83ae-815c445f205f)

**Comment by mjaggard** [comment]
Oh I see. That's very confusing but I understand now. Thanks.
