### ISSUE TITLE
Executable file permissions

### ISSUE THREAD

**Issue by petertoth-dev** [facebook/react-native-website#4157]
## What is the problem?
- After cloning a react-native project from a git repo, I couldn't run `npm run android`
- The only error message I've got is: `Failed to install the app` without any further details or information regarding the error. 
It was extremely difficult to figure out what's the issue, after a day of struggling I realized `/android/gradlew` file had no executable permission and this caused this issue.

## How can we address it?

1) In this case the CLI should throw an error:
"./android/gradlew" Permission Denied or even better "/android/gradlew" is not executable
2) Add this to the documentation to double check permissions for these executable files
3) react-native doctor could check and fix these automatically

## Why is it important?

To avoid unnecessary support tickets, and frustrated devs :)

## Who needs this?

Everbody

## When should this happen (use version numbers if needed)?
-

**Comment by cortinico** [comment]
Hey @petertoth-dev 
Please report this issue against the community CLI:
https://github.com/react-native-community/cli/issues

Also consider using Expo as that is our reccomended solution 👍
