### ISSUE TITLE
react-native doctor doesn't work properly without Android SDK Command-line tools

### ISSUE THREAD

**Issue by petertoth-dev** [facebook/react-native-website#4158]
## What is the problem?
react-native doctor reports missing SDK when it's actually installed.
After installing Android SDK Command-line tools everything is working as expected

## How can we address it?
Add  to the Environment Setup documentation where you list what packages should be selected.

## Why is it important?
It fixes react-native doctor's response

## Who needs this?
everybody

## When should this happen (use version numbers if needed)?
-

**Comment by cortinico** [comment]
Hey @petertoth-dev 
It seems like this issue is actually unrelated to the website. Please open this issue against this other repository:

https://github.com/react-native-community/cli/issues
