### ISSUE TITLE
Outdated documentation on running dev on a port other than 8081

### ISSUE THREAD

**Issue by NathanP-7West** [facebook/react-native-website#4162]
## Description

https://reactnative.dev/docs/troubleshooting#using-a-port-other-than-8081

While it does mention the folllowing:

> You will also need to update your applications to load the JavaScript bundle from the new port. If running on device from Xcode, you can do this by updating occurrences of 8081 to your chosen port in the ios/__App_Name__.xcodeproj/project.pbxproj file.

This is no longer true in the latest versions of react native. (At least 0.73-0.74) There are no instances of the port `8081` in the `ios/__App_Name__.xcodeproj/project.pbxproj` file.
(Checked on a fresh template from `npx @react-native-community/cli@latest init`)

(As a side note, it would be appreciated if anyone does know how to reconfigure this with the newer versions, trying to run two apps in dev at once. I'd be happy to raise a PR to update the section with the info too.)

## Documentation version

Next, 0.74, 0.73

**Comment by RohithThulasidharan** [comment]
Is there an update on this?
