### ISSUE TITLE
Wrong information mentioned in description of react-native's Image components source prop.

### ISSUE THREAD

**Issue by akash13625** [facebook/react-native-website#4165]
According to react native's documentation of Image component's source props, the supported props are
`The currently supported formats are png, jpg, jpeg, bmp, gif, webp, psd (iOS only)`
However, when trying to use webp images, present in xcode assets catalogue, it does not work. Also, it is mentioned in react-native code repo inside `Image.d.ts` that webp is only supported in android. However, webp works when bundled with JS in ios.
Please sync both the documentation and provide which information is correct.

**Comment by neehhaa06** [comment]
Hello @akash13625 

```
Check RN version
Set iOS target ≥ 11 in Podfile
Bundle WebP images in assets
Import with require
Run npx react-native run-ios
Check console for errors
```
