### ISSUE TITLE
Objective-C's integration documentation was outdated

### ISSUE THREAD

**Issue by ziggear** [facebook/react-native-website#4173]
## Description

In [this discussion](https://github.com/facebook/react-native/issues/45889#issuecomment-2270717660) with @cipolleschi @okwasniewski , I think the both Objective-C and Swift version of [Integration with Existing App - Configuring CocoaPods dependencies](https://reactnative.dev/docs/integration-with-existing-apps?language=objc#configuring-cocoapods-dependencies) part was outdated.

## What is the problem?

1. In [this discussion](https://github.com/facebook/react-native/issues/45889#issuecomment-2270717660), developers who follow the instructions in this section will mistakenly add pods to their Podfile instead of using the `use_react_native!` function. 
2. The [Swift's integation guide](https://reactnative.dev/docs/integration-with-existing-apps?language=swift#configuring-cocoapods-dependencies) had a 404 issue (#4170) , is resolved in the "Next" version, but it still seems to persist in version "0.74". When people first open this documentation, the top navigation bar's version filter defaults to "0.74" instead of "Next", which can cause confusion.

> Ultimately, your Podfile should look something similar to this: [Podfile Template](https://github.com/facebook/react-native/blob/main/packages/react-native/template/ios/Podfile) 

## How can we address it?

Please review and update the 'Integration with Existing Apps' section of the documentation, including both the Objective-C and Swift versions.

## Why is it important?

I believe that there are still many projects that have not yet integrated with React Native, especially some are written in Objective-C. I hope that the 'Integration with Existing Apps' section of the guide can be kept up-to-date, so that more people can easily adopt React Native. Thank you very much!

## Who needs this?

iOS Developers

## When should this happen (use version numbers if needed)?

N/A

**Comment by cipolleschi** [comment]
Just open https://github.com/facebook/react-native-website/pull/4239 that contains the updated version.
