### ISSUE TITLE
Integration with existing apps documentation is lack of New architecture

### ISSUE THREAD

**Issue by orange4glace** [facebook/react-native-website#4208]
Currently [Integration with existing apps](https://reactnative.dev/docs/integration-with-existing-apps) only works without New architecture. I think there should be a instruction with new architecture, like [here](https://www.callstack.com/blog/simplify-your-ios-brownfield-integration-with-react-native-host)

**Comment by cortinico** [comment]
Closing as this has been fixed now: https://reactnative.dev/docs/integration-with-existing-apps
