### ISSUE TITLE
Update Documentation for Starting a New React Native Project with Expo

### ISSUE THREAD

**Issue by ssj9685** [facebook/react-native-website#4209]
## Description
The documentation for starting a new React Native project with Expo does not reflect the latest version of the create-expo command. The current documentation can be found here: [React Native Environment Setup](https://reactnative.dev/docs/environment-setup#start-a-new-react-native-project-with-expo).

## What is the problem?
The documentation does not include the latest version of the create-expo command.

## How can we address it?
Update the documentation to include the latest commands for creating a new Expo project:

```sh
# Usage for bun, npm, pnpm, and yarn
npx create-expo
bun create expo
pnpm create expo
yarn create expo
```

For reference, the latest updates can be found here: [Expo GitHub Repository](https://github.com/expo/expo/tree/main/packages/create-expo).

## Why is it important?
Updating the documentation is crucial for new beginners to ensure they follow the correct steps and use the latest commands. Additionally, it is important to include the latest commands for various package managers (npx, bun, pnpm, yarn) to provide a comprehensive guide for users with different setups.

## Who needs this?
This update is particularly important for beginners who are starting a new project with React Native and Expo.

## When should this happen (use version numbers if needed)?
This update should be implemented as soon as possible to ensure the documentation is accurate and up-to-date.

**Comment by cortinico** [comment]
> The documentation for starting a new React Native project with Expo does not reflect the latest version of the create-expo command

Where specifically are you referring to?
