### ISSUE TITLE
The link to  NativeMethodsMixin.js returns a 404 screen

### ISSUE THREAD

**Issue by ighotouch** [facebook/react-native-website#421]
<img width="918" alt="screen shot 2018-06-24 at 6 05 27 am" src="https://user-images.githubusercontent.com/3287439/41816136-c7510df4-7774-11e8-84cb-e8a83603a40f.png">

The link `NativeMethodsMixin` redirects user to a 404 page on github `https://github.com/facebook/react/blob/master/src/renderers/native/NativeMethodsMixin.js`

Here is the link to the page showing this bug: https://facebook.github.io/react-native/docs/direct-manipulation#setnativeprops-with-touchableopacity

**Comment by ighotouch** [comment]
Hello i like to help out with this issue, is there any specific implementation you have in mind?

**Comment by charpeni** [comment]
Thank you for reporting this issue!

Sure, your help would be much appreciated.

I'd say we can remove the `.js` extension from the file name and instead link to https://github.com/facebook/react-native/blob/fb2ec1ea47c53c2e7b873acb1cb46192ac74274e/Libraries/Renderer/oss/ReactNativeRenderer-prod.js#L5793-L5813.

**Comment by ighotouch** [comment]
Thanks @charpeni for the clarification. Will do so.
