### ISSUE TITLE
docs/profiling.md still references Chrome profiler

### ISSUE THREAD

**Issue by kiranjd** [facebook/react-native-website#4221]
## Description
As titles suggests, this is the phrase on [this](https://reactnative.dev/docs/profiling) page.
> Another way to profile JavaScript is to use the Chrome profiler while debugging. This won't give you accurate results as the code is running in Chrome but will give you a general idea of where bottlenecks might be. Run the profiler under Chrome's Performance tab. A flame graph will appear under User Timing. To view more details in tabular format, click at the Bottom Up tab below and then select DedicatedWorker Thread at the top left menu. 

## What is the problem?
As per my understanding, the latest RN version if using the new architecture, cannot be debugged on Chrome

## How can we address it?
Suggest actual ways we can profile Javascript code

**Comment by huntie** [comment]
@kiranjd Thanks, have noted this page as part of WIP updates to our debugging guidance in 0.76.
