### ISSUE TITLE
React Native Getting Started Guide - App Crashes on iOS Simulator

### ISSUE THREAD

**Issue by niStee** [facebook/react-native-website#4225]
## Description

When trying to run the interactive examples on the React Native website (https://reactnative.dev/docs/getting-started#interactive-examples), the app crashes immediately after starting on the integrated iOS simulator.

## Environment

    React Native version: 0.75
    LibreWolf version: 130.0.1-1

## Steps to Reproduce

    Navigate to the React Native getting started guide (https://reactnative.dev/docs/getting-started)
    Click on the "Interactive Examples" section
    Attempt to run the example app on the integrated iOS simulator
    Observe that the app crashes immediately after starting

## Expected Behavior

The example app should run successfully on the iOS simulator without crashing.

## Actual Behavior

The example app crashes immediately after starting on the iOS simulator.

**Comment by JuliusKoronciCH** [comment]
I was about to raise a bug but none of the simulators in getting started work on chrome on my mac

**Comment by cortinico** [comment]
cc @Simek as that's part of Snack/Expo's infra

**Comment by Simek** [comment]
Hello @niStee, thank you for the report! Unfortunately I cannot reproduce the problem using the latest version of LibreWolf on macOS.

![Screenshot 2024-12-02 at 11 44 47](https://github.com/user-attachments/assets/f1d51637-2bbf-4f88-8b04-0825d00820ca)

Can you attach a screenshot showing the crashed state you are seeing?

I would also recommend checking the browser console for any errors in there, and extensions/blockers settings if they allow connection to Appetize which is the cloud simulators provider. You can also check if simulators are working for you on their home page: https://appetize.io/

**Comment by Simek** [comment]
Hello @JuliusKoronciCH, unfortunately I'm not able to reproduce your issue too. Similarly, I would recommend to check the browsers console and extensions/blockers settings. 

Quite a significant part of website visitors use macOS/Chrome combination, and if there would be an issue on the website side, I would expect few more reports about not working examples.

**Comment by niStee** [comment]
can't reproduce it
