### ISSUE TITLE
install cask zulu@17 is error, no exists

### ISSUE THREAD

**Issue by Markuuuu** [facebook/react-native-website#4227]
When I start the project fllowing the document, run "brew install --cask zulu@17" is error:Running `brew update --auto-update`...
Warning: Cask 'zulu@17' is unavailable: No Cask with this name exists.
==> Searching for similarly named casks...
Error: Cask 'zulu@11' is unavailable: No Cask with this name exists.
zsh: command not found: #
Error: Cask 'zulu@17' is unavailable: No Cask with this name exists.

**Comment by cortinico** [comment]
You should run `brew update` before if you're hitting this error
