### ISSUE TITLE
How to build React Native from source in RN 0.75?

### ISSUE THREAD

**Issue by tcloudAce** [facebook/react-native-website#4250]
Description:
I am currently using Expo SDK version 51.0.28 and I would like to build React Native from source. However, the method outlined in the official documentation ([React Native: How to build from source](https://reactnative.dev/contributing/how-to-build-from-source)) doesn’t seem to work with this version of Expo.

I have tried following the steps from the documentation, but encountered issues that prevent the build from succeeding. Specifically, it appears there may be incompatibilities or missing steps when trying to integrate this with Expo.

Could you provide updated guidance or clarify how to achieve building React Native from source for Expo 51.0.28?

Environment:

	•	Expo SDK Version: 51.0.28
	•	React Native Version: [0.74.5]
	•	Platform: [Android]

Steps to Reproduce:

	1.	Follow the steps outlined in the official [React Native Build from Source guide](https://reactnative.dev/contributing/how-to-build-from-source) while using Expo SDK 51.0.28.
	2.	Encounter issues during the build process.

Expected Behavior:
The build should successfully complete with React Native being built from source in the Expo environment.

Actual Behavior:
* What went wrong:
Plugin [id: 'com.facebook.react'] was not found in any of the following sources:

**Comment by cortinico** [comment]
> Description:
> I am currently using Expo SDK version 51.0.28 and I would like to build React Native from source. However, the method outlined in the official documentation ([React Native: How to build from source](https://reactnative.dev/contributing/how-to-build-from-source)) doesn’t seem to work with this version of Expo.

You should report this on Expo's side: https://github.com/expo/expo/issues
