### ISSUE TITLE
Step-by-step instructions on the "Getting Started Without a Framework", missing command to install react-native.

### ISSUE THREAD

**Issue by BarbaraRamalho** [facebook/react-native-website#4256]
## Description

Step-by-step instructions on the [Getting Started Without a Framework](https://reactnative.dev/docs/next/getting-started-without-a-framework), can be misleading as it's missing command to install react-native.

That missing command should be added to make the step-by-step guide more understandable.

## What is the problem?

When following the [Getting Started Without  a Framework](https://reactnative.dev/docs/next/getting-started-without-a-framework) guide, the first instruction a command to remove any previous react-native-cli installations. The guide then goes on to ask the user to start a new project, without indicating the command to install the most recent react-native-cli version. 

This can lead to confusions, and silly miskates, as the user might not have react-native-cli installed when following the instructions step-by-step.

## How can we address it?

We can address this by adding a step to install the latest version of react-native-cli as it appears in the normal [Getting Started](https://archive.reactnative.dev/docs/getting-started) guide.

## Why is it important?

It's important to make new learners ease into how to start a react-native project without a framwork.

## Who needs this?

New learners need this when starting a react-native-cli project, without a framework.

**Comment by cortinico** [comment]
> That missing command should be added to make the step-by-step guide more understandable.

You should not install `react-native` globally. 

The message says:

> If you previously installed a global react-native-cli package, please remove it as it may cause unexpected issues:

In the past we used to recommend global `react-native-cli` installation. This got discouraged long ago, but there could still be users out there with installed global package.

Not sure how we could word it differently.
