### ISSUE TITLE
Missing documentation for Animated.ValueXY

### ISSUE THREAD

**Issue by wh1t3cAt1k** [facebook/react-native-website#426]
Encountered today, but https://github.com/facebook/react-native/issues/16967 was closed due to being stale.

https://facebook.github.io/react-native/docs/animated#valuexy does not describe the signature of the `ValueXY` constructor.

For example, it is not clear what is the difference between creating a `ValueXY` with an explicit set of coordinates vs. no coordinates at all.

**Comment by Simek** [comment]
Hi @wh1t3cAt1k, thank you for pointing that! Unfortunately Animated value pages has been removed from the sidebar by the mistake. Page was you was looking for was available under the https://reactnative.dev/docs/animatedvaluexy URL but not from the menu on the left. I have updated the [`next`](https://reactnative.dev/docs/next/animatedvaluexy) version and added the pages back to the sidebar. This docs will become the current one with `0.63` release.
