### ISSUE TITLE
Is https://facebook.github.io/react-native/ Offline?

### ISSUE THREAD

**Issue by OtacilioN** [facebook/react-native-website#427]
I am trying to access the page https://facebook.github.io/react-native/ and also https://facebook.github.io/react-native/docs/getting-started.html and it is returning an error 404 File not found, it is just here?

**Comment by OtacilioN** [comment]
I asked for some friends to open the link in different internet connections and everyone is getting a 404. We are all in Brazil, is that some problem with our DNS?

**Comment by OtacilioN** [comment]
Now also asked for friends from different countries, everybody reported a 404.

**Comment by hramos** [comment]
The latest commit was missing a necessary file. @sophiebits fixed this over in the React Native repo, and I'm pushing an updated commit to this repo now.
