### ISSUE TITLE
How to access a Turbo Module from a Fabric Component?

### ISSUE THREAD

**Issue by gastonmorixe** [facebook/react-native-website#4347]
Without retro-compatibility, in the new architecture, how can I access a **Turbo Module** from a **Fabric Component**?

In iOS before I was able to do:

```objc
  RTNTWVideoModule *videoModule = [[RCTBridge currentBridge] moduleForName:@"RTNTWVideoModule"];
```

Now that the new architecture has no bridge I would like to know if there's another way and better way to do this.

That still works in but would like to know if this is still the official way to do it. Would like to avoid `RCTBridge` since in the new arch it should be no bridge. 

I see the current bridge is a proxy bridge, and the turbo modules are managed by `RCTTurboModuleManager` but couldn't find a way to access it from a fabric component without `RCTBridge`.

Thank you

**Comment by cortinico** [comment]
Please use this issue tracker only for Website related bugs.

You can ask this type of questions over here instead:
https://github.com/reactwg/react-native-new-architecture/
