### ISSUE TITLE
The upgrade help website seems like nothing from 0.76.4 to 0.76.5

### ISSUE THREAD

**Issue by llr101** [facebook/react-native-website#4398]
## Description

The upgrade help website seems like nothing from 0.76.4 to 0.76.5

https://react-native-community.github.io/upgrade-helper/?from=0.76.4&to=0.76.5

**Comment by pvinis** [comment]
fixed!

thank you for noticing and reporting. it just needed the old diff-regeneration-roo trick.

**Comment by cortinico** [comment]
Closing as it's now fixed
