### ISSUE TITLE
Getting started macOS+Android missing step to add device

### ISSUE THREAD

**Issue by iffy** [facebook/react-native-website#453]
In the [Using a virtual device](https://facebook.github.io/react-native/docs/getting-started#using-a-virtual-device) section of the getting started docs, it says:

> You can see the list of available Android Virtual Devices (AVDs) by opening the "AVD Manager" from within Android Studio. Look for an icon that looks like this:

But if you've just installed Android Studio (like I have), there's no such icon.  This is all I've got:

<img width="778" alt="screen shot 2018-07-10 at 11 19 11 am" src="https://user-images.githubusercontent.com/161727/42526453-15a739fe-8433-11e8-85b4-30f71d1a3231.png">

I assume I need to start a new Android Studio project, maybe?  Or open the one I just created with `react-native init`, but I'm not sure how to open that project.  What's the missing step here?

**Comment by patrickkempff** [comment]
@iffy You can click the "Configure" button (located bottom right in the dialog) and select 'AVD Manager'. 

PR's are welcome to improve this :)
