### ISSUE TITLE
Improving UX Guide (ongoing)

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native-website#47]
@frantic wrote in https://github.com/facebook/react-native/issues/14979

> As discussed with @brentvatne and other during ChainReact '17, it would be great to have a section in the docs that lists mobile-specific important UX details.

This is a rough checklist:

- [x] hitSlop
- [ ] tab bar
  - tab selected tab to pop
  - if empty stack, scroll to top
- [x] touchable with ripple
- [ ] keyboard:
  - [x] autofocus and return key
  - [x] space under keyboard and dismissing
  - [x] keyboard type, capitalization and autocorrect
- [ ] animated with useNativeDriver
  - only some properties supported -- no layout properties. use
    transforms whenever you can rather than width/height/margin,
    so you can take advantage of this
- [ ] nativedriver for animated.event in scroll view or it'll be janky
- [ ] loading states
  - onPressIn trick for preloading
  - placeholder elements
  - using data that you already have to partially render
  - loading state for image: what do you see when it's not there? maybe
    grey placeholder, maybe gradient, maybe activity indicator, maybe
    low-res version
- [ ] deferring rendering expensive (eg: maps) when possible
- [ ] status bar color, size
- [ ] fading in network images
- [ ] cancellable gestures
- [ ] meaningful animations -- shared transitions for example
- [ ] respect battery state
- [ ] prompt before asking permissions
- [ ] portrait / landscape: lock if you don't support
- [ ] android back button: navigation library can do some things but not all
  for you, need to consider where else users expect it to work
- [ ] compress images properly, provide 2x/3x
- [ ] sometimes text should be selectable
- [ ] ellipsize truncated text
- [ ] respect network status
- [ ] splash screen (white flash)
- [ ] maybe don't add an inline submit button to your form (use keyboard submit or add to navbar!)
- [ ] iphonex safe areas

**Comment by calvinmikael** [comment]
This is a great idea and I support you fully in your endeavors.

**Comment by raunaqss** [comment]
Any guidelines for anyone who wants to contribute towards completing the above checklist?

I've worked on a lot of the above in my react native apps, would love to help others save a bunch of time (and/or face).

**Comment by raunaqss** [comment]
@brendanv 

Hi Brent, I wanted to know if the repo was open to PRs with added content for the above list? If yes, what are the constraints within which the new content should be added (length, screenshots, links to resources, etc)?

As I've mentioned above, I'd love to contribute towards completing the above checklist. Look forward to your response!

Thanks

**Comment by kelset** [comment]
Just seen this right now, sorry @raunaqss !

> Any guidelines for anyone who wants to contribute towards completing the above checklist?

AFAIK there are no big constraints, but by looking at the current page ideally every point of the list should have a GIF showing the improvement & a link to an Expo Snack that shows the code to improve the UX.

cc @brentvatne

**Comment by frantic** [comment]
To be honest I think we set the bar for this document a little too high, I
myself stopped contributing because I simply didn’t have enough time to
craft gif+snack for every example.

**Comment by kelset** [comment]
maybe worth closing this since it's been open for over 2 years. We should probably instead open small issues per each actionable.
