### ISSUE TITLE
Getting started referencing Android API 23

### ISSUE THREAD

**Issue by Stan64** [facebook/react-native-website#472]
0.56 now runs on Android API 26. Should not the documentation also help users install the right testing environment?

Below **Getting Started > macOS > Android** it shows you how to install the API 23 SDK to use with the Android Virtual Device.

**Comment by kelset** [comment]
Can you submit a PR to update it? I'll merged it ASAP

**Comment by Stan64** [comment]
@kelset I've never done this before so I hope I did this correct:
https://github.com/facebook/react-native-website/pull/492

**Comment by kelset** [comment]
Hey thanks :)
I'll check it asap :)

**Comment by Stan64** [comment]
Closing this as it was merged and is now in the documentation.
