### ISSUE TITLE
Videos broken on Improving UX section

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native-website#48]
A bit ironic, but yeah, no videos play for me. https://facebook.github.io/react-native/docs/improvingux.html

![](http://url.brentvatne.ca/nBDAKX.png)

**Comment by hramos** [comment]
Taking a look. Seems like the mp4 assets are missing:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
img/ripple.mp4 Failed to load resource: the server responded with a status of 404 (Not Found)
img/hitslop.mp4 Failed to load resource: the server responded with a status of 404 (Not Found)
img/textinput.mp4 Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by spencercarli** [comment]
I'm happy to tackle this but not sure where to find the resources that are MIA. I found a [KeyboardAvoidingView gif](https://github.com/facebook/react-native-website/blob/master/docs/assets/KeyboardAvoidingView/example.gif) but no mp4s in the project.
