### ISSUE TITLE
Support Link is fails

### ISSUE THREAD

**Issue by lwinkyawmyat** [facebook/react-native-website#50]
- [other channels](https://facebook.github.io/react-native/support.html) link is fails in [How to contribute](https://facebook.github.io/react-native/docs/contributing.html) page.

![How to contribute](https://user-images.githubusercontent.com/13135332/33750580-4628b2d4-dc03-11e7-8ad0-9c2ec6e04809.png)
> Screen shot on [How to contribute](https://facebook.github.io/react-native/docs/contributing.html) page

**Comment by charpeni** [comment]
Thank you for bringing this up, I'll fix this.
