### ISSUE TITLE
Version Numbers in Getting Started Doc 

### ISSUE THREAD

**Issue by holographicleah** [facebook/react-native-website#509]
Hello, I've been working on my first project with React Native and have been [following the guidelines for Windows and developing for Android.](https://facebook.github.io/react-native/docs/getting-started). 

I have noticed that the version numbers on the text and the images aren't matching up: 
![screenshot 78](https://user-images.githubusercontent.com/20614250/43953014-960ff684-9c8f-11e8-8594-f9c170a06d03.png)
![screenshot 77](https://user-images.githubusercontent.com/20614250/43953015-962c668e-9c8f-11e8-9df2-4f1e136e997f.png)

I checked the [github page for editing it here](https://github.com/facebook/react-native-website/blob/master/docs/getting-started.md) but the text is up to date on there somehow! 

Would have saved me a bunch of time had the version numbers been up to date in the text! Thanks :)

**Comment by rickhanlonii** [comment]
Hey @holographicleah, sorry for the delay here!

Looks like this section has been removed so I'm going to close this, but thanks for your feedback!

**Comment by rickhanlonii** [comment]
@holographicleah how did your first project go? Would love to hear more feedback from you!
