### ISSUE TITLE
<SectionList> requires renderItem

### ISSUE THREAD

**Issue by stephenhuh** [facebook/react-native-website#510]
Render function from create-react-native-app:
```
  render() {
    return (
      <View style={styles.container}>
        <SectionList
          sections={[
            { title: 'Title1', data: ['item1', 'item2'] },
            { title: 'Title2', data: ['item3', 'item4'] },
            { title: 'Title3', data: ['item5', 'item6'] },
          ]}
        />
      </View>
    );
  }
```
With this code we get an "Invariant Violation: no renderItem".
[Doc Links](https://facebook.github.io/react-native/docs/sectionlist)
The docs only list `sections` as required. I tried to find the appropriate code in the original react-native repo to point this in case this is a bug, but was unsuccessful.

**Comment by charpeni** [comment]
Fixed by #665.
