### ISSUE TITLE
Documentation inconsistency

### ISSUE THREAD

**Issue by DonGiulio** [facebook/react-native-website#516]
I found in the docs an inconsistency in the versions required for the installation of Android for Mac. 

the text mentions `Look for and expand the Android 6.0 (Marshmallow)` and `Android SDK Platform 23` but the screenshot shows that Android 8.0 is used and different packages selected. and version 26 is checked.

similarly, below the text mentions: `then make sure that 23.0.1 is selected.` while the screenshot show 26.0.3 selected. 

I'm installing this stuff for the first time, and this is very confusing, I'll try to use the newer versions, mentioned in the screenshots.

**Comment by hramos** [comment]
We've been bumping the Android SDK deps in recent weeks. Docs have fallen out of sync, unfortunately. We'd appreciate a PR to bring them up to speed. You can look at the changelogs to understand the actual recommended versions.
