### ISSUE TITLE
useNativeDriver does not explicitly define supported properties

### ISSUE THREAD

**Issue by dennishansen** [facebook/react-native-website#525]
Does it work for colors? Would be nice to have a list of supported/non-supported properties.

**Comment by Simek** [comment]
Hi @dennishansen, is it still an issue? If yes can you give me an example of properties for `useNativeDriver` that are missing?

**Comment by Simek** [comment]
Closing due to lack of response from the author. 

Feel free to create a new issue, if information which you were looking for, is still missing in the documentation. :)
