### ISSUE TITLE
Search functionality not working

### ISSUE THREAD

**Issue by thepeted** [facebook/react-native-website#547]
MacOS High Sierra, 10.13.6
Chrome: Version 68.0.3440.106 (Official Build) (64-bit)

Type a search phrase in to the search bar (top right of screen) and hit enter:  Nothing happens.
I had a look in the console for any errors, could not see anything.

**Comment by TVke** [comment]
I get a 404 error for asset: [https://cdn.jsdelivr.net/docsearch.js/1/dist/cdn/docsearch.min.js.map](https://cdn.jsdelivr.net/docsearch.js/1/dist/cdn/docsearch.min.js.map)

**Comment by audiolion** [comment]
+1 search is broken on 0.57 version of the site

**Comment by feargswalsh92** [comment]
![image](https://user-images.githubusercontent.com/19194339/45590959-ce299800-b8f9-11e8-8e77-896a1d6362cb.png)
Definitely still working in 0.56 version on the site so it's gotta be something that was introduced inbetween.

**Comment by feargswalsh92** [comment]
Seemingly fixed by magic or #560 can be closed.

**Comment by audiolion** [comment]
working again 👍
