### ISSUE TITLE
0.57 Getting Started docs

### ISSUE THREAD

**Issue by elios264** [facebook/react-native-website#551]
React native 0.57 updated it's android dependencies so `Android SDK Platform 23` is no longer valid, 

So do these docs need to be updated?

`Next, select the "SDK Tools" tab and check the box next to "Show Package Details" here as well. Look for and expand the "Android SDK Build-Tools" entry, then make sure that 23.0.1 is selected.`

**Comment by charpeni** [comment]
Resolved.
