### ISSUE TITLE
Broken links 'CRNA user guide' @ upgrading to new React Native versions

### ISSUE THREAD

**Issue by filmhomage** [facebook/react-native-website#576]
Broken links @ upgrading to new React Native versions

<img width="938" alt="crna_broken_link" src="https://user-images.githubusercontent.com/4126751/45949569-9a86f600-bffc-11e8-90e1-1405dbef47b4.png">

### Line
https://github.com/facebook/react-native-website/edit/master/docs/upgrading.md#L12

### Broken link
[CRNA user guide](https://github.com/react-community/create-react-native-app/blob/master/react-native-scripts/template/README.md#updating-to-new-releases)

**Comment by charpeni** [comment]
Resolved.
