### ISSUE TITLE
Alternative to CRNA - Update Documentation

### ISSUE THREAD

**Issue by nicostuhlfauth** [facebook/react-native-website#592]
The [Quick Start](https://facebook.github.io/react-native/docs/getting-started.html) recommends using `create-react-native-app`, though it has been merged with expo CLI. I really want to build my first RN app, but without using expo. So, how do we get started now? Any tips? Please update the documentation 😄

**Comment by stam** [comment]
create-react-native-app now is deprecated in favor of expo-cli. But expo-cli by default builds your app on their servers, which is a no-go for most companies.

I normally use `react-native init` to start, but wonder why this isn't reflected in the react-native docs.

**Comment by brentvatne** [comment]
> create-react-native-app now is deprecated in favor of expo-cli. But expo-cli by default builds your app on their servers, which is a no-go for most companies.

It doesn't default to this, you can do this if you need an account but if you'd like to build it on your own you can do [this stuff](https://github.com/expo/expo#standalone-apps) or detach/eject.

I don't think it's a no-go for most companies to do this either, many companies use CI services like CircleCI to run builds, it's no different in this case.

**Comment by ecreeth** [comment]
@nicostuhlfauth I think you can close this issue
