### ISSUE TITLE
Algolia DocSearch dropdown is not shown when viewing versioned docs

### ISSUE THREAD

**Issue by ravirajn22** [facebook/react-native-website#61]
### Is this a bug report?

Yes 

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

 Environment:
    OS:  macOS Sierra 10.12.6
    Node:  6.11.0
    Yarn:  1.3.2
    npm:  5.4.2
    Watchman:  4.7.0
    Xcode:  Xcode 8.3.3 Build version 8E3004b
    Android Studio:  2.3 AI-162.4069837
    Chrome - 63.0.3239.84
    Firefox - 57.0

 Packages: (wanted => installed)
    react-native: 0.48.1 => 0.48.1
    react: 16.0.0-alpha.12 => 16.0.0-alpha.12

 Target Platform: iOS (10.3)

### Steps to Reproduce

(Write your steps here:)

1. Open Website https://facebook.github.io/react-native/
2. Search for Switch component using the search bar
3. Modal drop down appears with appropriate search results
4. Select Switch component
5. Inside Switch component docs, search for Button component. 
6. Nothing happens.

But,
7. Go back again to home page i.e https://facebook.github.io/react-native/
8. Search for Button, it shows all search results again.

### Expected Behavior

When you search for Button component inside Switch Component docs, a Modal dropdown must appear with all the search results

(Write what you thought would happen.)

### Actual Behavior

Nothing happens! the search bar does nothing.

(Write what happened. Add screenshots!)

![bug](https://user-images.githubusercontent.com/10977864/33930837-3a8e613e-e014-11e7-8a90-136e29783c0b.gif)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by hramos** [comment]
Looks like the dropdown is only triggered when viewing the latest version's docs. After navigating to 'next' or to a previous release, the drop down is not shown. Looks like anything that changes the base URL of the docs will cause this to happen.

**Comment by ravirajn22** [comment]
Please fix it soon, kind of tough to navigate and find features without search option.

**Comment by hramos** [comment]
You'll probably want to take a look at the `pages/` files in this repo. It may also be a bug with Docusaurus itself. Ping me here if you open a PR on either repo and I can take a look.

**Comment by hramos** [comment]
@s-pace has some insight about this, copying over from another issue:

> 
> 👋  guys,
> 
> React Native features [DocSearch](https://community.algolia.com/docsearch/).
> 
> @MoOx the issue isn't coming from our side but from the DocSearch snippet 
> 
> 🏓  @hramos (@vjeux)
> 
> It look like the `master` pages aren't using the right tag (The latest version is hardcoded instead of `master`).
> 
> I have made a [quick fix in order to don't stop the search in production](https://github.com/algolia/docsearch-configs/commit/dd8bd78c306e0929f2285409bdfaff5af9544c77) but please update [your tag from your DocSearch snippet](https://github.com/s-pace/react-native/commit/4bf072ad4e93152c88fceeedc1ee633cecbc6499). I can't do a PR on the `gh-pages` according to your Contributing Guide.
> 
> It is not [the first time this issue happen](https://twitter.com/yrezgui/status/946530587451576332). 
> 
> Feel free to ask us for any other point, we would be happy to help.

I think this may need to be fixed upstream in Docusaurus (see my comment here https://github.com/s-pace/react-native/commit/4bf072ad4e93152c88fceeedc1ee633cecbc6499).

**Comment by hramos** [comment]
https://github.com/facebook/Docusaurus/pull/418

**Comment by ericlewis** [comment]
This seems to not be broken anymore.

**Comment by methodbox** [comment]
Are you guys aware this is still broken? The docs are effectively unusable without search.

This seems to break every couple of weeks.

**Comment by s-pace** [comment]
The crawl is pretty long and was stopped. Can you check now @methodbox ? Should be fine

![image](https://cl.ly/93ae54c67bf8/download/Image%202019-06-11%20at%209.58.37%20AM.png)

**Comment by methodbox** [comment]
> The crawl is pretty long and was stopped. Can you check now @methodbox ? Should be fine
> 
> ![image](https://camo.githubusercontent.com/016edabd82ce7ceb6cd5cc1406a7b69137b8a378/68747470733a2f2f636c2e6c792f3933616535346336376266382f646f776e6c6f61642f496d616765253230323031392d30362d31312532306174253230392e35382e3337253230414d2e706e67)

Not sure what you mean by, "the crawl is pretty long...". Can you clarify?

It seems to be working now. However, your test image shows the actual home page; note that this was particularly and issue **after** searching and/or on the actual docs page. Both seem to work okay now, though.

**Comment by s-pace** [comment]
The daily crawl was too long so it was not correctly done. Should be fixed now :)

**Comment by Simek** [comment]
It also looks like a fixed issue for me. @methodbox Feel free to reopen this issue or create the new one if the problem persist.
