### ISSUE TITLE
Are Stylesheet.create({}) docs outdated?

### ISSUE THREAD

**Issue by ethanneff** [facebook/react-native-website#645]
Following this comment here https://github.com/DefinitelyTyped/DefinitelyTyped/issues/29265#issuecomment-430783289.

It seems that `Stylesheet.create({})` no longer offers performance gains. Is this true? Should the docs (https://facebook.github.io/react-native/docs/stylesheet) be updated to reflect this change?

**Comment by hramos** [comment]
#629 has been merged.

**Comment by slorber** [comment]
does anyone know why the StyleSheet behavior was modified?
