### ISSUE TITLE
Documentation requiresMainQueueSetup missing

### ISSUE THREAD

**Issue by teameh** [facebook/react-native-website#671]
As asked [before](https://github.com/facebook/react-native/pull/16916#issuecomment-347106733). There are no docs on `requiresMainQueueSetup`. 

[The docs only state](https://facebook.github.io/react-native/docs/native-modules-ios#threading):

> For example, if it needs to use a main-thread-only iOS API, it should specify this via:
> 
> ```
> - (dispatch_queue_t)methodQueue {
>     return dispatch_get_main_queue();
> } 
> ```

But this seems to be not enough since I'm getting: 

```
2018-11-08 10:31:12.591 [warn][tid:main][RCTModuleData.mm:67] 
Module XXXXXX requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`. 
In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.
```

I could write some docs if someone can explain why `- (dispatch_queue_t)methodQueue` is not enough and in which cases one would need to implement `requiresMainQueueSetup` as well.

**Comment by renankof** [comment]
+1

**Comment by stormriderc** [comment]
+1

**Comment by lhcgoncalves** [comment]
+1

**Comment by ptellesfilho** [comment]
+1

**Comment by charpeni** [comment]
Thanks for reporting.

Please use GitHub's reactions.

**Comment by EricAtPlanGrid** [comment]
We can close this issue now that #813 landed.

**Comment by teameh** [comment]
Ah that is great 😃👍. 

But not completely, since `methodQueue` is still not explained. can we reopen it?

**Comment by teameh** [comment]
Ping @charpeni @EricAtPlanGrid
