### ISSUE TITLE
Missing Getting Started Instruction for iOS

### ISSUE THREAD

**Issue by wolfe719** [facebook/react-native-website#676]
When doing an initial install for MacOS and iOS, the step "cd AwesomeProject; react-native run-ios" will fail without running "npm install" in the AwesomeProject directory.

I have no idea why (newbie to React Native), but it was very hard to figure out.

Could the instructions be:

  cd AwesomeProject
  npm install
  react-native run-ios

**Comment by Simek** [comment]
Getting Started guide has been updated a lot since this issue has been posted. 

The current guide can be found [here](https://reactnative.dev/docs/environment-setup).

If you still experiencing the problem with the initial installation of the latest version of React Native please create new issue.
