### ISSUE TITLE
I want the click event of the Section list header

### ISSUE THREAD

**Issue by renishdeveloper** [facebook/react-native-website#680]
How to make the section list header clickable in the Section list https://facebook.github.io/react-native/docs/sectionlist#rendersectionheader

**Comment by charpeni** [comment]
Not sure what you mean?

**Comment by adriancuco** [comment]
Hi,
How about adding  onPress inside renderSectionHeader as follows?

 renderSectionHeader={({ section }) => (
            <Text style={styles.SectionHeaderStyle}> {section.title}   onPress={this.DoSomething.bind(this, 
                     section.title)}>
          )}

**Comment by Simek** [comment]
Hi @renishdeveloper, unfortunately this is the React Native website repository. 

If you having a question about React Native usage you should head to the [StackOverflow](https://stackoverflow.com/questions/ask?tags=react-native) or any other resource or community listed on the [Help](https://reactnative.dev/help) page. Hope you can understand that!
