### ISSUE TITLE
React Navigation documentation is outdated

### ISSUE THREAD

**Issue by hrastnik** [facebook/react-native-website#684]
React Navigation has recently released version 3.0.0 of the library. The library has changed the API while the API used on the React Native docs is not working.

https://github.com/facebook/react-native-website/blob/master/docs/navigation.md

**Comment by KeevanDance** [comment]
I'll go ahead and try and submit a pull request for this one!

**Comment by charpeni** [comment]
Thanks for doing this @KeevanDance!

I'll close this issue.
