### ISSUE TITLE
Native Modules Setup page vague and/or wrong

### ISSUE THREAD

**Issue by techieyann** [facebook/react-native-website#706]
There's an [open issue](https://github.com/frostney/react-native-create-library/issues/65) for react-native-create-library regarding the Haste map. Basically, it boils down to metro not following sym-links when building the haste module map (which is the [very first issue](https://github.com/facebook/metro/issues/1) of the metro bundler).

As I commented in the react-native-create-library issue, I don't fully understand the instructions on the [Native Modules Setup](https://facebook.github.io/react-native/docs/native-modules-setup) page.

How are we supposed to successfully follow this instruction:
> - add your newly created module as a dependency in your package.json

Doing it by file reference creates a sym-link and the haste map won't load it. So it seems we are required to put changes directly into the node-modules directory or push every change to a remote repo to test it.

Is there some better way that I am unaware of, and if so can we make the instructions more clear?

**Comment by Joao-Leite** [comment]
Hi,

Were you able to make your module from an external library folder work somehow?
I'm trying to follow the tutorial on react's documentation page (and some others) , but im not managing to make it work. I tried to copy the module to the node-modules directory but I still get errors like "Unable to resolve module.." and others.

How did you manage to do it?

Thanks,
João Leite

**Comment by techieyann** [comment]
I didn't make it work directly, but I was able to develop a package.

I directly made changes in the `./node_modules/my_new_package` directory and copied to the external library folder to use git.
Once it's functional you can install it directly from the GitHub repo or publish to npm as you wish.

**Comment by Joao-Leite** [comment]
Thank you for you reply.
I finally managed to make it work by sending the module to a GitHub Repo, but I didn't understand why copying the folder directly to the node_modules didn't work before downloading the dependency from git, as the end result is the same.
Thanks again

**Comment by techieyann** [comment]
It sounds like you were trying to just add a directory into `./node_modules` but you need to have an equivalent line in your `./package.json` for npm to make it available.
