### ISSUE TITLE
Can't click on link/button that appears next to each prop title

### ISSUE THREAD

**Issue by rigdern** [facebook/react-native-website#71]
Each prop title has a link/button to the left of it:

![image](https://user-images.githubusercontent.com/199935/34018662-be3a100c-e0df-11e7-9067-678e120d4d81.png)

This link/button only appears when you hover over the text representing the prop name. Consequently, you cannot click on the link/button because it disappears when you attempt to hover over it in order to click it.

Adam Comella
Microsoft Corp.

**Comment by Tonours** [comment]
Can i take this one ?

**Comment by hramos** [comment]
Thanks for the report. Looks like an issue with Docusaurus, the site generator. I've duplicated this issue in their repo. I'll leave this open until it's fixed in Docusaurus.

**Comment by hramos** [comment]
@Tonours's comment hadn't loaded when I posted above (I had an old tab open). Thanks for looking into it, interesting to see it might be an issue with our CSS and not on Docusaurus's side. Let me take a look and make sure this is not something we need to upstream to Docusaurus.

**Comment by hramos** [comment]
Fix looks great, merged.

**Comment by Tonours** [comment]
@hramos Hi ! Yes at the beginning i thought it was in Docusaurus but this is an override in react-native.css :-)
