### ISSUE TITLE
Missing documentation for UIManager

### ISSUE THREAD

**Issue by jginsburgn** [facebook/react-native-website#725]
I was trying to find out how to use a [`PopupMenu`][1] with RN. While browsing the documentation, I found no mention of how this would be possible without an external plugin. I jumped to searching in Google and found a small snippet, in a comment of [#3004][2] of react-native's git, referring to `UIManager` and its `showPopupMenu` API. I believe this is a powerful native feature of which documentation shall be not only in the [source code][3], but also in the docs website.

[1]: https://developer.android.com/reference/android/widget/PopupMenu
[2]: https://github.com/facebook/react-native/issues/3004#issuecomment-202598006
[3]: https://github.com/facebook/react-native/blob/39b68903463062f69c9120fab7e79fa2735b0b07/ReactAndroid/src/main/java/com/facebook/react/uimanager/NativeViewHierarchyManager.java#LC777

**Comment by EricAtPlanGrid** [comment]
I’m happy to write this up, at least for iOS. I haven’t gotten to the Android port yet. Should this be a separate document or part of one of the existing ones?

**Comment by jginsburgn** [comment]
Acually `Popup Menu` is only applicable in Android.

**Comment by dsernst** [comment]
These remain missing. 

The 3rd-party typescript definitions have descriptions and type signatures for many of the `UIManager` methods:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/da93d7b13094bacb170ead3f4a289f3b8687e4e5/types/react-native/index.d.ts#L8001

But it's still missing some methods, like [`.viewIsDescendantOf`](https://github.com/facebook/react-native/blob/fb627dac6a03f4ab52def4375812fbaf4804dcac/Libraries/ReactNative/NativeUIManager.js#L62).

**Comment by jginsburgn** [comment]
Searching for `showPopupMenu` still yields no results in the documentation site.
