### ISSUE TITLE
AccessibilityState - What does it mean to say a button that has focus is selected?

### ISSUE THREAD

**Issue by SteveGF** [facebook/react-native-website#747]
From the docs:
"AccessibilityState tells a person … the state of the element currently focused on. … 
selected - Used when the element is in a selected state. For example, a button is selected."

I'm wondering what it means to say a button with focus is "selected".  I can understand how this could apply to a checkbox being checked (i.e. selected) or a radio button being selected.  Is that what this means?  Is there any meaning for a push-button being selected?

**Comment by Simek** [comment]
Hi @SteveGF, lately the [Accessibility](https://reactnative.dev/docs/next/accessibility#accessibilitystate-android-ios) page content has been rewritten. 

Please let me know if the current `accessibilityState` description is clear enough.
