### ISSUE TITLE
ScrollView method getScrollResponder is not listed in the document

### ISSUE THREAD

**Issue by ghost** [facebook/react-native-website#768]
The getScrollResponder method  of ScrollView is not listed in the document. I dont realize this method is exist and I waste hours to try to handle scrollview scroll animation problem by myself in a weird way. This method would save me a lot time if I know this method in advance. I hope the team would include the method in the document. Thanks.

![image](https://user-images.githubusercontent.com/23181321/51898092-1ea61b80-23eb-11e9-94b8-2e265d3d957f.png)

**Comment by glauberfc** [comment]
#929

**Comment by Simek** [comment]
In the current version of the docs we no longer use listings in the content. There is an automatically generated secondary navigation menu on the right side of the page and `getScrollResponder()`  method now appears on the list.
