### ISSUE TITLE
Animated doc missing property type defs

### ISSUE THREAD

**Issue by hramos** [facebook/react-native-website#77]
Scroll to the bottom of http://facebook.github.io/react-native/docs/animated.html - there's a few empty prop types.

**Comment by jaredly** [comment]
srsly
![image](https://user-images.githubusercontent.com/112170/41491939-3ddad01c-70b9-11e8-948a-9a330bae445f.png)

**Comment by hramos** [comment]
For anyone interested in fixing this - you can look up the docblocks in the react-native repo and get the missing text there. Shouldn't be much trouble to add these back, we just missed them during the migration to plain markdown docs.
