### ISSUE TITLE
Remove NavigatorIOS from the docs

### ISSUE THREAD

**Issue by hramos** [facebook/react-native-website#773]
This component was removed in https://github.com/facebook/react-native/commit/0df92afc1caf96100013935d50bdde359b688658. References to it need to be removed from navigation.md, and the navigatorios.md doc will need to be updated.

I believe that simply removing navigatorios.md from versioned_docs/0.58 and docs/ may not work, as Docusaurus might have trouble handling the removal. We may need to add a notice instead, explaining the component has been removed from core.

**Comment by gedeagas** [comment]
PR Submitted https://github.com/facebook/react-native-website/pull/776. 
what do you think about the wording @hramos?
