### ISSUE TITLE
Installing react-navigation not enough if not using expo

### ISSUE THREAD

**Issue by alexabruck** [facebook/react-native-website#784]
The documentation suggests that you just need to install `react-navigation`, import it and you're ready to go. But this is only true if you're using expo! 

If you're not using expo, and you're targeting ios, you also need to install `react-native-gesture-handler` and link all native dependencies with the command`react-native link react-native-gesture-handler`. If you're targeting Android even more steps are involved.

That's what I learned after finally hitting the reactnavigation website (https://reactnavigation.org/docs/en/getting-started.html). But before I spend a lot of time trying to understand this obscure error "null is not an object (evaluating RNGestureHandlerModuleState)" (image below).

![simulator screen shot - iphone x - 2019-02-09 at 17 05 27](https://user-images.githubusercontent.com/5918060/52523023-0789e800-2c8d-11e9-887d-7d36648ef077.png)

**Comment by Simek** [comment]
Current version of [Navigating Between Screens](https://reactnative.dev/docs/navigation) guide contains correct list of required packages and commands are divided for `expo` and `react-native` users.

If you still having problems with navigation packages using the latest guide please create the new issue.
