### ISSUE TITLE
GIF and WebP support on Android is outdated

### ISSUE THREAD

**Issue by charpeni** [facebook/react-native-website#785]
[GIF and WebP support on Android](https://facebook.github.io/react-native/docs/image#gif-and-webp-support-on-android) seems outdated according to this comment: https://github.com/facebook/react-native/issues/21216#issuecomment-460297264

**Comment by jatinkumarg** [comment]
I think changing the **animated-gif** from ` 'com.facebook.fresco:animated-gif:1.10.0' ` to ` 'com.facebook.fresco:animated-gif:1.12.0' ` should work. 
If correct, can I update the document?
