### ISSUE TITLE
Document how React is upgraded in React Native

### ISSUE THREAD

**Issue by hramos** [facebook/react-native-website#787]
Upgrading React in React Native is a multi-step process that requires re-building the renderer, [among other things](https://github.com/facebook/react-native/issues/21967#issuecomment-434113687). This is not clear to folks using React Native (see https://github.com/react-native-community/discussions-and-proposals/issues/88). Let's document somewhere that upgrading React yourself is not encouraged.

We have a similar situation with dependencies like Flow. Flow needs to be upgraded across all of Facebook, and PRs that bump Flow will not be accepted in the main repo.

**Comment by kelset** [comment]
I feel this one should be kept open

**Comment by kelset** [comment]
(I think we can close it tbh)

**Comment by cortinico** [comment]
> (I think we can close it tbh)

Do we have it documented somewhere or why this has changed?

**Comment by kelset** [comment]
good question - as far as I know there's no documentation about this, but I don't know who would be able to create the documentation for this. Basically, if I understand/recall correctly, this is about explaining to the larger audience why a specific version of React Native needs to be "paired" with a precise version of React in package.json.

**Comment by cortinico** [comment]
> Basically, if I understand/recall correctly, this is about explaining to the larger audience why a specific version of React Native needs to be "paired" with a precise version of React in package.json.

I'll be pushing some docs about this with the release of React 18 (so this is not stale)
