### ISSUE TITLE
Broken link in docs/javascript-environment

### ISSUE THREAD

**Issue by adyouri** [facebook/react-native-website#798]
> Here's a full list of React Native's enabled transformations.

*enabled transformations* points to `https://github.com/facebook/react-native/blob/master/babel-preset/configs/main.js#L16`.

**Comment by charpeni** [comment]
Thanks for reporting, I'll submit a PR.

**Comment by adyouri** [comment]
Thanks!

Also:
[Direct Manipulation](https://facebook.github.io/react-native/docs/direct-manipulation): `see receiveComponent in ReactNativeBaseComponent.js` is also outdated.
