### ISSUE TITLE
Document how to upgrade React Native without react-native-git-upgrade

### ISSUE THREAD

**Issue by hramos** [facebook/react-native-website#799]
react-native-git-upgrade was removed from React Native. Let's update the Upgrading doc and remove references to git upgrade.

**Comment by nexus0212** [comment]
I would like to take this up 👏

**Comment by ecreeth** [comment]
@hramos I think the [upgrade-helper](https://github.com/react-native-community/upgrade-helper) solves part of this problem

**Comment by vj-codes** [comment]
Heyy @hramos I'm a newbie and Facebook open source immersion participant , can I work on this?

**Comment by Simek** [comment]
@hramos Currently, there are no references left to the `react-native-git-upgrade` package (besides the old blog posts). 

The [Upgrading to new versions](https://reactnative.dev/docs/next/upgrading) page also seems to contain most of needed information. There is also a section dedicated to the mentioned above Upgrade Helper (which was introduced along the `0.61` release - https://reactnative.dev/blog#more-upgrade-support).

I'm going to close this issue, but please feel free to create new one, if you have any tips on improving the Upgrading page! 🙂
