### ISSUE TITLE
Feeback for React Native's website/documentation

### ISSUE THREAD

**Issue by unbug** [facebook/react-native-website#815]
**I'll keep updating this issue, let me know you guys want to hear any specific part of the docs.**

# Missing the basic of ReactJS
You might expect many FE(web) start to build client apps with RN, but the fact is FE(web) don't really have much chance to build the client app. because, in many companies, FE(native) and FE(web) are a totally different team. FE(native) focus on Object-c/Swift/Java/Kotlin but not JavaScript, so they have to understand how ReactJS work before get started to RN. So in the [basic tutorial](https://facebook.github.io/react-native/docs/tutorial), it should be step by step like https://reactjs.org/tutorial/tutorial.html, especially the part of "think in ReactJS" should not be missing in RN docs. 

# Missing the architecture
How do we organize the structure of an RN app? How do we write a model, and how do we interact with the view and the controller? We're not going to write a fetch method in our component like https://facebook.github.io/react-native/docs/network, right? Flux?  Redux? But how? Apple even documented the MVC model in its Cocoa Touch Framework. We're about to build an app, which might have millions of users, but we can't find a best practice of the architecture for RN, seriously? I don't have the confidence to scare my RN app.

# Missing the detail of Flexbox model
The most important skill to build a fancy app is how to layout, but in [RN's docs](https://facebook.github.io/react-native/docs/flexbox) tell us nothing about Flexbox model, an FE(web) know we can learn Flexbox model in [CSS-Trick](https://css-tricks.com/snippets/css/a-guide-to-flexbox/), I also use it for my [React Native Traning Book](https://github.com/unbug/react-native-train/blob/master/README.md#31-flexbox), but its a totally different story for an FE(native),  we should cover that in the docs.

# Mixin
1. Data persistent is missing in the docs, which is a pretty common usage for Native Apps.

# Missing a cross-platform UI library
I understand what I am trying to say here is beyond the documentation. But to make RN popular is to make the developing processing easier, right? A fancy UI library could make that happen, it will bring a huge community to RN, a successful example is Google Flutter.

**Comment by unbug** [comment]
@cpojer

**Comment by charpeni** [comment]
👋 Hey @unbug!

We're always trying to make the documentation better, so thanks for your well-organized feedback, it's really appreciated. We'll keep that in mind.

**Comment by MoOx** [comment]
Some things that bother me...:
- lots of props are missing in various components
- order of props in docs is sometimes totally random (that's seems totally a weird choice)

I still don't get why docs for components aren't close to them. Because when a change is made to a component, it's VERY (too) easy to not update docs...

@cpojer is there any plan for RN docs to make them better? I think the 2 points above are really an issue atm (I am writing docs for reasonml bindings, & I am constantly missing things & have to check RN codebase & constantly find issues, so many that I am too lazy to update all those inconsistencies, but I think we should really tackle this someday...)

**Comment by cpojer** [comment]
@MoOx Yes! We hope to redo most of the website. If you could document the inconsistencies, that would help a ton!

**Comment by cpojer** [comment]
Thank you so much for writing up this issue. I am currently working on an umbrella task for the new React Native website and I'm including many of the things you listed. I'll close this issue for now but be on the lookout for a new master task soon :)
