### ISSUE TITLE
Docs example not running

### ISSUE THREAD

**Issue by CyberMew** [facebook/react-native-website#824]
In https://facebook.github.io/react-native/docs/text, the examples are not running and it shows `TypeError: Cannot read property 'undefined' of undefined`

**Comment by charpeni** [comment]
I do not have any issues on my side with Chrome 73.

What's your browser?

**Comment by CyberMew** [comment]
I’m using Chrome 72 but just updated to 73 with the same problem.

**Comment by CyberMew** [comment]
<img width="1196" alt="Screen Shot 2019-03-23 at 9 51 26 PM" src="https://user-images.githubusercontent.com/4715911/54866948-e05b2600-4db5-11e9-9a1d-f790e529afdd.png">
Screenshot of issue.

**Comment by CyberMew** [comment]
Nevermind, could be an extension messing with the example, since incognito seems to be working. Closing issue.
