### ISSUE TITLE
i'm newbie, get error

### ISSUE THREAD

**Issue by dodicandra** [facebook/react-native-website#826]
i've only started react native,but every run on my devices is always an error for it,i've tried fixing nothing 
![image](https://user-images.githubusercontent.com/48325708/54088034-e8659f80-438b-11e9-898d-b5a6e32f9b90.png)

**Comment by rickhanlonii** [comment]
Hey @dodicandra, thanks for trying React Native!

Unfortunately this issue tracker is not a help forum

We [StackOverflow](https://stackoverflow.com/questions/ask) where there is an active [react-native](https://stackoverflow.com/questions/tagged/react-native) tag for questions
