### ISSUE TITLE
Remove references to deprecated lifecycles

### ISSUE THREAD

**Issue by charpeni** [facebook/react-native-website#844]
We have some references to `componentWill*` which are deprecated lifecycles.

### Native Modules Android

> JavaScript modules can then register to receive events by addListenerOn using the Subscribable mixin.

```js
import { DeviceEventEmitter } from 'react-native';
...

var ScrollResponderMixin = {
  mixins: [Subscribable.Mixin],


  componentWillMount: function() {
    ...
    this.addListenerOn(DeviceEventEmitter,
                       'keyboardWillShow',
                       this.scrollResponderKeyboardWillShow);
    ...
  },
  scrollResponderKeyboardWillShow:function(e: Event) {
    this.keyboardWillOpenTo = e;
    this.props.onKeyboardWillShow && this.props.onKeyboardWillShow(e);
  },
```

> You can also directly use the DeviceEventEmitter module to listen for events.

```js
...
componentWillMount: function() {
  DeviceEventEmitter.addListener('keyboardWillShow', function(e: Event) {
    // handle event.
  });
}
...
```

#### Location

- [/docs/native-modules-android.md](https://github.com/facebook/react-native-website/blob/852a035c116fdcdf78ffa1ba53d7499c2bf3e3a9/docs/native-modules-android.md)

#### What to do?

- [x] The first part on mixins could be simply removed as mixins are not the future (sorry gaearon).
- [x] Then `componentWillMount` could be replaced with `componentDidMount` using the usual ES6 method declaration without `componentWillMount: function() { }`.

### Communication iOS & Android

> **Note:** Currently, JS functions `componentWillReceiveProps` and `componentWillUpdateProps` of the top level RN component will not be called after a prop update. However, you can access the new props in `componentWillMount` function.

#### Location

- [/docs/communication-ios.md](https://github.com/facebook/react-native-website/blob/e0570a5ea4ea903b66b40ea21bb4fad5f204a325/docs/communication-ios.md)
- [/docs/communication-android.md](https://github.com/facebook/react-native-website/blob/0d36c27ef53c78f706fc2e303f0ca26bdb925217/docs/communication-android.md)

#### What to do?

- [ ] `functions` these are more a lifecycle than a "function".
- [x] `componentWillReceiveProps` is deprecated without a direct replacement, could probably be simply removed.
- [ ] `componentWillUpdateProps ` doesn't seems like a valid lifecycle? 🤔
- [x] `componentWillMount` could probably be replaced with `componentDidMount` which will also be called on the initial render (or native props changed in this case). Also, `static getDerivedStateFromProps` is also available to compute a state from props, both on the initial mount and on subsequent updates.

**Comment by jamesgeorge007** [comment]
@charpeni I would like to take this up 👏

**Comment by charpeni** [comment]
Sure, let me know if you have any questions.

**Comment by jamesgeorge007** [comment]
@charpeni Kindly have a look at #849 and suggest the required changes :+1:

**Comment by jpbulman** [comment]
Can this be closed now that the pr has been merged?
