### ISSUE TITLE
Broken link to "packager config file" in the Images guide

### ISSUE THREAD

**Issue by AlbertVilaCalvo** [facebook/react-native-website#863]
There's a broken link on the Images guide page:

http://facebook.github.io/react-native/docs/images

The borken link is on the this text:

> You can add support for other types by creating a packager config file (see the [packager config file](https://github.com/facebook/react-native/blob/master/local-cli/util/Config.js#L68) for the full list of configuration options).

The current URL is https://github.com/facebook/react-native/blob/master/local-cli/util/Config.js#L68 which gives a 404.

**Comment by rickhanlonii** [comment]
This file was moved to `react-native-community/cli`, @thymikee any idea where the new link should go?

**Comment by thymikee** [comment]
These should now be defined in `metro.config.js` file, see the docs on where to put this: https://facebook.github.io/metro/docs/en/configuration#assetexts

**Comment by rickhanlonii** [comment]
Thanks @thymikee!

@AlbertVilaCalvo want to submit the PR?

**Comment by AlbertVilaCalvo** [comment]
@rickhanlonii I've opened a PR: https://github.com/facebook/react-native-website/pull/960
