### ISSUE TITLE
TextInput's autoComplete prop isn't available it but it's documented as available

### ISSUE THREAD

**Issue by elucaswork** [facebook/react-native-website#882]
I just found misinformation in the docs: in [TextInput](https://facebook.github.io/react-native/docs/0.58/textinput#autocomplete) says the `autoComplete` prop is available (since 0.58) but this feature is not available it in any version, it's only in #master, as can be seen here https://github.com/facebook/react-native/commit/f15145639dab1e8d7a1c79a127b7d45c91d025a8.

`autoComplete` prop's PR https://github.com/facebook/react-native-website/pull/606.

Is there a way to update 0.58 & 0.59 docs to remove it?
Just let me know how If I can help to solve this issue.

cc @charpeni

**Comment by elucaswork** [comment]
cc @cpojer

**Comment by charpeni** [comment]
Thanks for flagging that, I'm sending a PR.
