### ISSUE TITLE
Typo in ScrollView documentation

### ISSUE THREAD

**Issue by wagnermaciel** [facebook/react-native-website#883]
There seems to be a typo here in scroll view documentation for the `keyboardShouldPersistTaps` prop. In particular, the sentence describing the "handled" option.

**Current**:
"the keyboard will not dismiss automatically when the tap was handled by a children"

**Proposed change**:
"the keyboard will not dismiss automatically when the tap was handled by children of the scroll view"

[Link to the documentation](https://facebook.github.io/react-native/docs/scrollview.html#keyboardshouldpersisttaps)

**Comment by rickhanlonii** [comment]
Fixed, thanks!
