### ISSUE TITLE
Edit button is linking to versioned_docs instead of docs

### ISSUE THREAD

**Issue by liamsheppard** [facebook/react-native-website#9]
I was confused when clicking the Edit button that I was being taken into the `versioned_docs/version-X.XX` folder.

I'm assuming this is incorrect, based on this quote from `README.md`:

> Do not edit the auto-generated files within 'versioned_docs/' or 'versioned_sidebars/' unless you are sure it is necessary. Edits made to older versions will not be propagated to newer versions of the docs.

**Comment by gaearon** [comment]
This also confused me. It directed me to the versioned page for a very old version of the docs.

**Comment by hramos** [comment]
For now, you may have noticed I've been merging changes made against `docs/` as well as `versioned_docs/`. These are mostly changes that fix broken links and other issues related to the transition, as we do want those changes to be applied to past versions.
