### ISSUE TITLE
Touchables Document

### ISSUE THREAD

**Issue by ramyareye** [facebook/react-native-website#907]
Hello,

According to https://kmagiera.github.io/react-native-gesture-handler/docs/component-touchables.html shall react native Touchable docs like https://facebook.github.io/react-native/docs/touchableopacity be updated? 

It came to my mind cause I had problem with TouchableOpacity from react-native package.

Regards

**Comment by rickhanlonii** [comment]
Hey @ramyareye, sorry that I don't quite understand - what would our docs be updated to say?

**Comment by ramyareye** [comment]
We faced an unusual problem on touching a button last week! so we replaced TouchableOpacity imported from react-native with the same one from react-native-gesture-handler . 
So it came to ma mind to guide users to use that library if there is a need for a pure native one!

**Comment by rickhanlonii** [comment]
Not sure what that issue was but the React Native docs will continue to document the React Native core Touchable component 👍
