### ISSUE TITLE
collapsible sidebar & on page navigation

### ISSUE THREAD

**Issue by hemith** [facebook/react-native-website#918]
I have added 2 lines to siteConfig.js in my local env.

>   onPageNav: 'separate',
>   docsSideNavCollapsible: true,

I think It have given a nice navigation experience.
How about commit these config lines as default ?

<img width="1430" alt="nice_navigation" src="https://user-images.githubusercontent.com/10476866/57514300-20b53a00-734b-11e9-993a-a586b0822b9f.png">

**Comment by rickhanlonii** [comment]
Thanks for the suggestion @hemith!

We have the collapsible sidebar on now - I think the issue with the on page nav is that our doc pages aren't all correctly organized into the correct headers so the nav isn't organized well

We can consider turning it on after #929 👍
