### ISSUE TITLE
React Native CLI Installation Link Unclear

### ISSUE THREAD

**Issue by hawthord** [facebook/react-native-website#955]
Installing React Native CLI as a prerequisite to contributing is simple, but finding the instructions to do so is not. The link on [https://github.com/facebook/react-native/wiki/How-to-Contribute](https://github.com/facebook/react-native/wiki/How-to-Contribute) is still several jumps short of providing clear instructions, and searching online leads to other sites with different instructions.

Since the code to install it is so short, may I suggest adding a simple line or two of code onto the How to Contribute page describing how to install it using npm or yarn?

<code>npm install -g react-native-cli</code>
<code>yarn global add react-native-cli</code>

Another possibility is to link directly to the installation instructions at [https://github.com/react-native-community/cli/tree/master/packages/global-cli](https://github.com/react-native-community/cli/tree/master/packages/global-cli) or at https://facebook.github.io/react-native/docs/getting-started.html[https://facebook.github.io/react-native/docs/getting-started.html].

**Comment by rickhanlonii** [comment]
Hey @hawthord thanks again for the feedback!

Have you see our new guide for [Submitting Your First PR](https://github.com/facebook/react-native/wiki/Pull-Requests#getting-ready-to-submit-your-first-pull-request). This is designed to provide more specific instructions with explanations of each step

I'd support your updates as well if you want to submit a PR and tag me!

**Comment by rickhanlonii** [comment]
Also, please continue to give us this feedback, it is super useful!

Feel free to comment on our umbrella issue for the website/docs rewrite as well https://github.com/facebook/react-native-website/issues/929
