### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by madeleke** [facebook/react-native-website#985]
After pressing enter to search, nothing happens...literally nothing.

**Comment by ecreeth** [comment]
It seems that the search is only enabled in the [API](https://facebook.github.io/react-native/docs/0.59/getting-started) and [DOCS](https://facebook.github.io/react-native/docs/0.59/activityindicator) pages

**Comment by Schacal** [comment]
I also encountered with the search problem. When I'm trying to use search box in react-native website - nothing happens...

**Comment by madeleke** [comment]
> It seems that the search is only enabled in the [API](https://facebook.github.io/react-native/docs/0.59/getting-started) and [DOCS](https://facebook.github.io/react-native/docs/0.59/activityindicator) pages

Nothing changes on there

**Comment by methodbox** [comment]
FYI:  https://github.com/facebook/react-native-website/issues/61 and https://github.com/facebook/react-native-website/issues/998

**Comment by methodbox** [comment]
In the meantime, try this; it seems to work on docs prior to the latest version (0.60-rc ... which you don't seem to be able to change without specifying the initial URL):  https://facebook.github.io/react-native/docs/**0.59**/getting-started

**Comment by madeleke** [comment]
I dig that
