### ISSUE TITLE
No travis in this repository

### ISSUE THREAD

**Issue by abhinavsagar** [facebook/react-native-website#997]
Should we add a `travis.yml` ?

**Comment by idindrakusuma** [comment]
I think `react-native-website` already use Circle CI for Continous Integration. So, we don't need to add `travis.yml`.

**Comment by rickhanlonii** [comment]
Hey @abhinavsagar, we're using Circle for CI here. Is there a reason we should have a travis.yml if we're not using it?

Going to close but I'm happy to keep the discussion open!
