### ISSUE TITLE
Broken URL - Memory Use in Extensions

### ISSUE THREAD

**Issue by kphillisjr** [facebook/react-native-website#999]
I was reading the documentation over IOS and noticed a broken link. The page needing updates is  https://facebook.github.io/react-native/docs/app-extensions  and the broken link is to the video for Conrad Kramers talk on Memory Use in Extensions. The current link is leading to a parked website ( along with complaints about invalid SSL certificates). Either way, a more current link for this video can be found on the Philadelphia CocoaHeads ( aka Philly CocoaHeads) youtube channel. The website for the Philly CocoaHeads channel is http://phillycocoa.org/ and the updated video link is https://www.youtube.com/watch?v=GqXMqn6MXrM

**Comment by ecreeth** [comment]
@kphillisjr now you can close it

**Comment by rickhanlonii** [comment]
It will be fixed in the next version release, but the broken link is still live on the site. We would need to update the 0.59 version to fix on the live site
